/* Ambient presentation. Does not own progression, combat or inventory. */
(() => {
'use strict';
const qualityPresets={low:{dpr:1,particles:12,walkers:4},medium:{dpr:1.5,particles:24,walkers:10},high:{dpr:2,particles:36,walkers:10}};
class AmbientLife {
 constructor(defs){this.actors=defs.map((d,i)=>({...d,x:d.route[0][0],y:d.route[0][1],waypoint:1,distance:0,pause:i*.5,moving:false,transform:new window.AstraeonMotion.CharacterTransform(d.route[0][0],d.route[0][1]),kind:d.kind||(i<2?'guild':i===4?'craft':'market')}))}
 tick(dt,time){for(const a of this.actors){if(a.pause>0){a.pause-=dt;a.moving=false;a.transform.tick(a.x,a.y,dt);continue}let [x,y]=a.route[a.waypoint],dx=x-a.x,dy=y-a.y,n=Math.hypot(dx,dy);if(n<.1){a.waypoint=(a.waypoint+1)%a.route.length;a.pause=2+(a.waypoint%3)*1.4;a.moving=false;a.transform.tick(a.x,a.y,dt);continue}const step=Math.min(n,a.pace*dt);a.x+=dx/n*step;a.y+=dy/n*step;a.distance+=step;a.moving=true;a.transform.tick(a.x,a.y,dt)}}
}
class Atmosphere {
 constructor(){this.time=110;this.weather='clear';this.wetness=0;this.wind=.3;this.states={clear:{wet:0,wind:.3,fog:0},cloudy:{wet:0,wind:.55,fog:.03},rain:{wet:1,wind:.8,fog:.09},fog:{wet:.25,wind:.2,fog:.14}}}
 tick(dt){this.time+=dt;const phase=Math.floor(this.time/150)%4;this.weather=['clear','cloudy','rain','clear'][phase];const w=this.states[this.weather];this.wetness+=(w.wet-this.wetness)*Math.min(1,dt*.08);this.wind+=(w.wind-this.wind)*Math.min(1,dt*.08)}
 get night(){return Math.max(0,-Math.sin(this.time/130))*.24}
 draw(ctx,w,h,iso,objects,quality){ctx.save();if(this.night){ctx.fillStyle=`rgba(17,31,63,${this.night})`;ctx.fillRect(0,0,w,h)}const fog=this.states[this.weather].fog;if(fog){const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,`rgba(190,214,199,${fog})`);g.addColorStop(1,'rgba(190,214,199,0)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}for(const o of objects){if(!o.building&&o.art!=='stall')continue;const p=iso(o.x,o.y);const r=o.building?50:22;const g=ctx.createRadialGradient(p.x,p.y-35,0,p.x,p.y-35,r);g.addColorStop(0,`rgba(255,210,113,${.035+this.night*.5})`);g.addColorStop(1,'rgba(255,210,113,0)');ctx.fillStyle=g;ctx.fillRect(p.x-r,p.y-35-r,r*2,r*2)}if(this.wetness>.06){ctx.strokeStyle=`rgba(185,218,224,${this.wetness*.45})`;ctx.lineWidth=1;const count=quality.particles*2;for(let i=0;i<count;i++){const x=(i*137+this.time*70)%w,y=(i*83+this.time*310)%h;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-3,y+11);ctx.stroke()}}ctx.restore()}
}
class AudioScene {
 constructor(){this.ctx=null;this.master=null;this.enabled=localStorage.getItem('astraeon-sound')!=='off';this.nextWater=0;this.nextMusic=0;this.step=0;this.zone=0;this.nextAmbient=0;this.prepare()}
 prepare(){if(!this.enabled||this.ctx)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;this.ctx=new C({latencyHint:'interactive'});this.master=this.ctx.createGain();this.master.gain.value=.22;this.master.connect(this.ctx.destination)}catch{this.enabled=false}}
 unlock(){if(!this.enabled)return;this.prepare();if(this.ctx?.state==='suspended')this.ctx.resume().catch(()=>{})}
 tone(freq,duration=.15,gain=.08,type='sine',delay=0){if(!this.ctx||this.ctx.state!=='running'||!this.enabled)return;const t=this.ctx.currentTime+delay,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(Math.max(.002,gain),t+.012);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+duration+.02)}
 noise(duration=.09,gain=.09,cutoff=1800){if(!this.ctx||!this.enabled||this.ctx.state!=='running')return;const n=Math.ceil(this.ctx.sampleRate*duration),b=this.ctx.createBuffer(1,n,this.ctx.sampleRate),data=b.getChannelData(0);for(let i=0;i<n;i++)data[i]=(Math.random()*2-1)*(1-i/n);const s=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();f.type='lowpass';f.frequency.value=cutoff;g.gain.value=gain;s.buffer=b;s.connect(f);f.connect(g);g.connect(this.master);s.start()}
 play(kind){this.unlock();if(kind==='hit'){this.noise(.075,.32,2600);this.tone(105,.09,.25,'triangle')}else if(kind==='cast'){this.tone(440,.21,.11);this.tone(660,.22,.08,'sine',.05)}else if(kind==='arrow'){this.noise(.1,.13,5000)}else if(kind==='dodge')this.noise(.18,.1,1000);else if(kind==='hurt')this.tone(90,.18,.24,'triangle');else if(kind==='loot'){this.tone(660,.18,.1);this.tone(880,.23,.07,'sine',.08)}else if(kind==='step')this.noise(.025,.035,800);else this.tone(520,.08,.06)}
 tick(time,zone,dungeon,position,weather){if(!this.ctx||this.ctx.state!=='running'||!this.enabled)return;this.zone=zone;if(time>this.nextWater){this.nextWater=time+.8;const water=zone===0?Math.hypot(position.x-window.AstraeonContent.townObjects.find(o=>o.art==='fountain').x,position.y-window.AstraeonContent.townObjects.find(o=>o.art==='fountain').y):zone===2?Math.hypot(position.x-24,position.y-8):100;if(!dungeon&&water<8)this.noise(.8,.023*(1-water/8),1500)}if(time>this.nextMusic){this.nextMusic=time+(dungeon?.7:1.2);const melody=[0,7,12,9,7,4,2,7,0,4,9,12,7,2,4,0],root=dungeon?146.83:zone===0?220:174.61,n=melody[this.step++%melody.length];this.tone(root*Math.pow(2,n/12),dungeon?.6:1.7,.036,'sine');if(this.step%4===0)this.tone(root/2,2.8,.026,'triangle')}if(time>this.nextAmbient){this.nextAmbient=time+3.4;if(weather==='rain')this.noise(.9,.025,900);else if(!dungeon&&zone!==0){this.tone(1800,.09,.02);this.tone(2200,.12,.016,'sine',.14)}else if(zone===0&&Math.hypot(position.x-window.AstraeonContent.services.find(s=>s.kind==='craft').x,position.y-window.AstraeonContent.services.find(s=>s.kind==='craft').y)<6){this.tone(740,.045,.026,'triangle');this.noise(.045,.022,900)}}}
 setEnabled(value){this.enabled=value;try{localStorage.setItem('astraeon-sound',value?'on':'off')}catch{};if(this.master)this.master.gain.value=value?.22:0;if(value)this.unlock()}
}
window.AstraeonWorldSystems={qualityPresets,AmbientLife,Atmosphere,AudioScene};
})();
