const {test}=require('node:test'),assert=require('node:assert/strict');
global.window={};
for(const n of ['input','skill-nodes','combat','progression-config','progression','stats','skill-definitions','skill-tree','action-loadout','skill-runtime','action-runtime','character-state','item-definitions','equipment-slots','item-inventory','inventory-capacity','item-equipment','item-state','action-item-config','item-effects','action-item','action-item-runtime','drop-tables','monster-definitions','loot-resolution','monster-rewards','monster-loot-runtime','box-content-tables','monster-box','monster-box-runtime','combat-resolution-config','combat-resolution','combat-runtime','enemy-combat','monster-lifecycle-definitions','monster-lifecycle','monster-combat-runtime','quest-definitions','quest-state','quest-evidence','quest-runtime','town-service-definitions','storage-state','town-service-runtime','player-state','save-state'])require('../'+n+'.js');
require('../dev-tools.js');
const W=window,D=W.AstraeonDevTools,S=W.AstraeonSave,I=W.AstraeonItemInventory;
function fixture(cls=0,extra={}){
 const state=S.normalize({name:'Dev disposable',cls,gold:50,itemInventory:I.normalize(),equippedItems:{},actionLoadout:Array(8).fill(null),...extra});
 const p=W.AstraeonPlayer.attach(state);let loading=false,configure=true,wiped=false;
 const storage=new Map([['astraeon-iso-v1','character'],['astraeon-quality','high'],['other','keep']]);
 const actors=[],loot=W.AstraeonMonsterLootRuntime.create({commit:(r,id)=>p.commitMonsterRewards(r,id)});
 const life=W.AstraeonMonsterLifecycle.create({loot,getRewardContext:()=>p.getMonsterRewardContext(2),rng:W.AstraeonCombatRuntime.sequenceRng([0,0,0,0])});
 const owner={getPlayer:()=>wiped?null:p,isLoading:()=>loading,canConfigure:()=>configure,saveSnapshot:()=>S.snapshot(state),afterMutation:()=>({ok:true}),
  effects:()=>({scope:'limited',statuses:[]}),monsters:()=>actors.map(a=>life.inspect(a)),maps:()=>[{zone:0},{zone:2}],
  spawnMonster:(id,point)=>{const d=W.AstraeonMonsterLifecycleDefinitions.getDefinition(id);if(!d)return {ok:false,code:'UNKNOWN_MONSTER_DEFINITION'};const hp=W.AstraeonMonsterLifecycleDefinitions.maxHP(d).maxHP,a={hp,maxHp:hp,x:point.x,y:point.y};const r=life.register(a,id,{id:'dev-'+actors.length,home:point},0);if(r.ok)actors.push(a);return r.ok?{ok:true,monster:r}:r},
  killTarget:id=>{const a=actors.find(a=>life.inspect(a).instanceId===id);if(!a)return {ok:false,code:'UNKNOWN_MONSTER_INSTANCE'};if(a.hp<=0)return {ok:false,code:'ALREADY_DEAD'};const r=W.AstraeonCombatResolution.applyCombatResult(a.hp,{ok:true,finalDamage:a.hp},a.maxHp);a.hp=r.hpAfter;return life.notifyDeath(a,0)},
  teleport:async point=>{if(![0,2].includes(point?.zone)||!Number.isFinite(point?.x)||point.x<1||point.x>28)return {ok:false,code:'INVALID_POSITION'};p.invalidatePreparedActions();state.zone=point.zone;state.x=point.x;state.y=point.y;life.invalidateTargets(0,'DEV_TELEPORT');return {ok:true,invalidated:true}},
  wipe:c=>{if(c!=='WIPE '+state.name)return {ok:false,code:'WIPE_CONFIRMATION_REQUIRED'};storage.delete('astraeon-iso-v1');wiped=true;return {ok:true,removedKeys:['astraeon-iso-v1'],reloadRequired:true}}
 };
 return {p,state,owner,api:D.create(owner,'?dev=1'),actors,life,storage,loading:n=>loading=n,configure:n=>configure=n};
}
function unchanged(f,fn,code){const before=S.snapshot(f.state),r=fn();assert(!r.ok);if(code)assert.equal(r.code,code);assert.deepEqual(S.snapshot(f.state),before);return r}
for(const query of ['', '?qa=1','?dev=0','?dev=01','?xdev=1','?dev=true','?dev=1x'])test('no mutation API for '+query,()=>assert.equal(D.create({},query),null));
test('exact dev mode exposes one frozen coherent namespace',()=>{const f=fixture();assert(Object.isFrozen(f.api));assert.deepEqual(Object.keys(f.api),['progression','items','money','skills','stats','monsters','world','inspect','save'])});
for(const cls of [0,12]){
 test('canonical levels and points class '+cls,()=>{const f=fixture(cls),a=f.api;assert(a.progression.setBaseLevel(5).ok);assert.equal(f.state.baseLevel,5);assert.equal(f.state.statPoints,12);assert(a.progression.setJobLevel(6).ok);assert.equal(f.state.skillPoints,5);assert(f.state.hp<=f.state.maxHp);assert(f.state.energy<=f.state.maxEnergy)});
 test('EXP uses existing multi-level progression class '+cls,()=>{const f=fixture(cls),before=f.p.snapshot();const expected=W.AstraeonProgression.grant(before,'base',200).state;assert(f.api.progression.addBaseExp(200).ok);assert.equal(f.state.baseLevel,expected.baseLevel);assert.equal(f.state.baseExp,expected.baseExp);assert.equal(f.state.statPoints,expected.statPoints);assert(f.api.progression.addJobExp(180).ok);assert.equal(f.state.baseJobLevel,4)});
 test('level lowering preserves canonical spent point refusal class '+cls,()=>{const f=fixture(cls);f.api.progression.setBaseLevel(4);f.api.stats.allocate('STR',9);unchanged(f,()=>f.api.progression.setBaseLevel(1),'INVALID_VALUE')});
 test('stat refund and derived resources class '+cls,()=>{const f=fixture(cls);f.api.progression.setBaseLevel(5);const before=f.p.snapshot();assert(f.api.stats.allocate('VIT',2).ok);assert(f.api.stats.reset().ok);assert.equal(f.state.VIT,1);assert.equal(f.state.statPoints,before.statPoints);assert.equal(f.state.statPointSpending,0);assert(f.state.hp<=f.state.maxHp)});
 const skill=cls===0?'rising-edge':'ember-bloom';
 test('learn rank reset uses paid ledger and loadout class '+cls,()=>{const f=fixture(cls);f.api.progression.setJobLevel(20);const points=f.state.skillPoints;assert(f.api.skills.learn(skill).ok);assert(f.api.skills.rankUp(skill).ok);assert.equal(f.p.getSkillRank(skill),2);assert(f.p.assignSkill(0,skill).ok);assert(f.api.skills.reset().ok);assert.equal(f.state.skillPoints,points);assert.equal(f.p.getSkillRank(skill),0);assert.deepEqual(f.p.getActionLoadout(),Array(8).fill(null))});
 test('wrong class skill rejects class '+cls,()=>{const f=fixture(cls);f.api.progression.setJobLevel(20);unchanged(f,()=>f.api.skills.learn(cls===0?'ember-bloom':'rising-edge'),'WRONG_CLASS')});
 test('canonical read-only inspectors class '+cls,()=>{const f=fixture(cls);const before=S.snapshot(f.state),s=f.api.inspect.stats();assert.deepEqual(s.primary,f.p.getPrimaryStats());assert.deepEqual(s.derived,f.p.getDerivedStats());assert.deepEqual(s.modifiers,f.p.getModifierGroups());assert(Object.isFrozen(s));assert.deepEqual(f.api.save.snapshot(),S.snapshot(f.state));f.api.inspect.effects();assert.deepEqual(S.snapshot(f.state),before)});
}
for(const value of [0,-1,.5,NaN,Infinity,Number.MAX_SAFE_INTEGER+1,'2'])for(const track of ['Base','Job'])test('invalid '+track+' Level '+value,()=>{const f=fixture();unchanged(f,()=>f.api.progression['set'+track+'Level'](value),'INVALID_LEVEL')});
for(const n of [-1,.5,NaN,Infinity,Number.MAX_SAFE_INTEGER+1,'5'])for(const track of ['Base','Job'])test('invalid '+track+' EXP '+n,()=>{const f=fixture();unchanged(f,()=>f.api.progression['add'+track+'Exp'](n),'INVALID_EXP')});
test('caps and same-level setters preserve current canonical policy',()=>{const f=fixture();assert(f.api.progression.setBaseLevel(60).ok);assert(f.api.progression.setJobLevel(50).ok);assert(f.api.progression.addBaseExp(100000).ok);assert(f.api.progression.addJobExp(100000).ok);assert.equal(f.state.baseExp,0);assert.equal(f.state.baseJobExp,0);unchanged(f,()=>f.api.progression.setBaseLevel(61),'INVALID_LEVEL')});
for(const n of [-1,.5,NaN,Infinity,Number.MAX_SAFE_INTEGER+1])test('invalid Gold '+n,()=>{const f=fixture();unchanged(f,()=>f.api.money.give(n),'INVALID_CURRENCY_AMOUNT')});
test('safe Gold give/set share canonical Player wallet',()=>{const f=fixture();assert(f.api.money.give(25).ok);assert.equal(f.state.gold,75);assert(f.api.money.set(10).ok);assert.equal(f.state.gold,10)});
test('Gold overflow rejects unchanged',()=>{const f=fixture(0,{gold:Number.MAX_SAFE_INTEGER});unchanged(f,()=>f.api.money.give(1),'CURRENCY_OVERFLOW')});
test('malformed current wallet is not silently repaired',()=>{const f=fixture(0,{gold:.5});unchanged(f,()=>f.api.money.set(10),'INVALID_CURRENCY')});
test('canonical stack grant uses revision with no serial',()=>{const f=fixture(),serial=f.p.getInventory().nextItemSerial,rev=f.p.getInventoryRevision();assert(f.api.items.give('herb',3).ok);assert.equal(f.p.getQuantity('herb'),3);assert.equal(f.p.getInventoryRevision(),rev+1);assert.equal(f.p.getInventory().nextItemSerial,serial)});
test('bulk unique grant creates exact canonical instances without equip',()=>{const f=fixture(),serial=f.p.getInventory().nextItemSerial;const r=f.api.items.give('astral-blade',3);assert(r.ok);assert.equal(r.result.instanceRewards.length,3);assert.equal(new Set(r.result.instanceRewards.map(i=>i.instanceId)).size,3);assert.equal(f.p.getInventory().nextItemSerial,serial+3);assert(Object.values(f.p.getEquipmentSlots()).every(v=>v===null))});
test('stored IDs remain globally reserved by debug grant',()=>{const f=fixture(0,{storageState:{schema:1,instances:{'item-42':{instanceId:'item-42',definitionId:'astral-blade',metadata:{}}}}});const r=f.api.items.give('astral-blade');assert(r.ok);assert.equal(r.result.instanceRewards[0].instanceId,'item-43')});
test('capacity rejection allocates no serial or partial items',()=>{const f=fixture();const p=W.AstraeonPlayer.attach(S.snapshot(f.state),{getCapacityPolicy:()=>({...W.AstraeonInventoryCapacity.defaultPolicy,slotLimit:0,weightLimit:0})});f.owner.getPlayer=()=>p;const rev=p.getInventoryRevision(),serial=p.getInventory().nextItemSerial;const r=f.api.items.give('astral-blade',2);assert(!r.ok);assert.equal(p.getInventoryRevision(),rev);assert.equal(p.getInventory().nextItemSerial,serial)});
test('unknown item rejects',()=>{const f=fixture();unchanged(f,()=>f.api.items.give('missing'),'UNKNOWN_ITEM')});
for(const n of [0,-1,.5,NaN,Infinity,Number.MAX_SAFE_INTEGER+1])test('invalid grant count '+n,()=>{const f=fixture();unchanged(f,()=>f.api.items.give('herb',n),'INVALID_QUANTITY')});
test('unknown skill and prerequisite gates reject unchanged',()=>{const f=fixture();unchanged(f,()=>f.api.skills.learn('missing'),'UNKNOWN_SKILL');unchanged(f,()=>f.api.skills.learn('rising-edge'),'SKILL_POINTS')});
test('configuration unsafe retains skill/stat state',()=>{const f=fixture();f.configure(false);unchanged(f,()=>f.api.skills.reset(),'UNSAFE_CONFIGURATION');unchanged(f,()=>f.api.stats.reset(),'UNSAFE_CONFIGURATION')});
test('unknown primary rejects',()=>{const f=fixture();unchanged(f,()=>f.api.stats.allocate('UNKNOWN'),'UNKNOWN_STAT')});
test('loading blocks mutation but not read-only inspector',()=>{const f=fixture();f.loading(true);unchanged(f,()=>f.api.items.give('herb'),'CONTEXT_BLOCKED');assert(f.api.inspect.save())});
test('spawn owns real Lifecycle and exact-once death/reward',()=>{const f=fixture(),r=f.api.monsters.spawn('lifecycle-normal-a',{zone:2,x:10,y:10});assert(r.ok);const id=r.result.monster.instanceId;assert(f.life.inspect(f.actors[0]).alive);const serial=f.p.getInventory().nextItemSerial;assert(f.api.monsters.kill(id).ok);const after=S.snapshot(f.state);assert(f.life.inspect(f.actors[0]).deathId);assert.equal(f.p.getQuantity('herb'),2);assert(!f.api.monsters.kill(id).ok);assert.deepEqual(S.snapshot(f.state),after);assert.equal(f.p.getInventory().nextItemSerial,serial)});
test('unknown monster definition cannot create actor',()=>{const f=fixture();assert(!f.api.monsters.spawn('missing',{x:10,y:10}).ok);assert.equal(f.actors.length,0)});
test('unknown kill cannot create death',()=>{const f=fixture();unchanged(f,()=>f.api.monsters.kill('missing'),'UNKNOWN_MONSTER_INSTANCE')});
test('invalid teleport rejects unchanged; valid reconciles runtime callback',async()=>{const f=fixture();const before=S.snapshot(f.state);assert(!(await f.api.world.teleport({zone:99,x:10,y:10})).ok);assert.deepEqual(S.snapshot(f.state),before);const r=await f.api.world.teleport({zone:2,x:10,y:10});assert(r.ok);assert(r.result.invalidated);assert.equal(f.state.zone,2)});
test('async command blocks concurrent mutation and read-only remains available',async()=>{const f=fixture();let done;f.owner.teleport=()=>new Promise(r=>done=r);const pending=f.api.world.teleport({zone:2,x:10,y:10});unchanged(f,()=>f.api.money.give(1),'DEV_COMMAND_IN_PROGRESS');assert(f.api.inspect.stats());done({ok:true});assert((await pending).ok)});
test('wipe exact name confirmation and exact save key only',()=>{const f=fixture();unchanged(f,()=>f.api.save.wipeTestCharacter('WIPE wrong'),'WIPE_CONFIRMATION_REQUIRED');const r=f.api.save.wipeTestCharacter('WIPE Dev disposable');assert(r.ok);assert.deepEqual(r.result.removedKeys,['astraeon-iso-v1']);assert(r.result.reloadRequired);assert(!f.storage.has('astraeon-iso-v1'));assert.equal(f.storage.get('astraeon-quality'),'high');assert.equal(f.storage.get('other'),'keep');assert.equal(f.api.save.snapshot(),null);assert.equal(f.api.money.give(1).code,'NO_CHARACTER')});
test('real-game adapters use canonical paths; normal exposure gate and wipe scope',()=>{const fs=require('node:fs'),s=fs.readFileSync(require('node:path').join(__dirname,'../game.js'),'utf8'),boot=fs.readFileSync(require('node:path').join(__dirname,'../boot.js'),'utf8');assert(s.includes('hit(actor,actor.hp)'));assert(s.includes('mobs.push(actor)'));assert(s.includes("player.invalidatePreparedActions();invalidateMonsterTargets('DEV_TELEPORT')"));assert(s.includes("localStorage.removeItem('astraeon-iso-v1')"));assert(!s.includes('localStorage.clear()'));assert(boot.includes("if(new URLSearchParams(location.search).get('dev')==='1')await load(['dev-tools.js'])"));assert(s.indexOf('window.AstraeonDev=')>s.indexOf("if(new URLSearchParams(location.search).get('dev')==='1'){",s.indexOf('window.AstraeonQA')))});
