"""Roadmap developer commands against real two-class characters, not a sandbox."""
import argparse,json,os,tempfile
from pathlib import Path
from playwright.sync_api import sync_playwright
ap=argparse.ArgumentParser();ap.add_argument('--url',default='http://127.0.0.1:8011');ap.add_argument('--browser',default=os.environ.get('ASTRAEON_BROWSER',r'C:\Program Files\Google\Chrome\Application\chrome.exe'));ap.add_argument('--output',type=Path,default=Path(tempfile.gettempdir())/'astraeon-dev-tools-browser');args=ap.parse_args();args.output.mkdir(parents=True,exist_ok=True)
checks,errors,http_errors,rejections=[],[],[],[];page=None;game=None;report={}
def checkpoint():(args.output/'progress.json').write_text(json.dumps({'checks':checks,'errors':errors,'httpErrors':http_errors,'expectedRejections':rejections},indent=2),encoding='utf-8')
def passed(name,evidence=None):checks.append({'name':name,'evidence':evidence});print('PASS',name,flush=True);checkpoint()
def call(code):return game.evaluate('async()=>{const d=AstraeonDev;'+code+'}')
def snap():return call('return d.save.snapshot()')
def click(command):
 page.locator('#result').evaluate('e=>e.textContent="PENDING"');page.locator('[data-command="'+command+'"]').click();page.wait_for_function('document.querySelector("#result").textContent!=="PENDING"');return json.loads(page.locator('#result').inner_text())
def reject(code,expected):
 before=snap();r=call(code);assert not r['ok'] and r['code']==expected,(r,expected);assert snap()==before;rejections.append({'code':r['code'],'operation':r.get('operation')});return r
try:
 with sync_playwright() as pw:
  browser=pw.chromium.launch(executable_path=args.browser,headless=True,args=['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-background-timer-throttling','--disable-renderer-backgrounding','--disable-backgrounding-occluded-windows'])
  for cls,skill in [('0','rising-edge'),('12','ember-bloom')]:
   context=browser.new_context(viewport={'width':1600,'height':1000});page=context.new_page();page.set_default_timeout(180000)
   page.on('pageerror',lambda e:errors.append(str(e)));page.on('console',lambda m:errors.append(m.text) if m.type=='error' else None);page.on('response',lambda r:http_errors.append(f'{r.status} {r.url}') if r.status>=400 else None)
   page.goto(args.url.rstrip('/')+'/tools/dev-console.html',wait_until='load');page.locator('#game').wait_for();game=page.locator('#game').element_handle().content_frame();game.set_default_timeout(180000) if hasattr(game,'set_default_timeout') else None
   game.wait_for_selector('#create');name='Dev tools disposable '+cls;game.locator('#newname').fill(name);game.locator('#newclass').select_option(cls);game.locator('#create').click();game.wait_for_selector('#world');game.wait_for_function('AstraeonQA.snapshot().time>.3&&!!window.AstraeonDev');game.locator('[data-open="character"]').click()
   assert snap()['name']==name;passed('real game developer console loads disposable character',{'class':cls})
   page.locator('#value').fill('5');assert click('base-level')['ok'];assert snap()['baseLevel']==5;assert snap()['statPoints']==12;passed('Set Base Level uses canonical point/resource state',{'class':cls})
   page.locator('#value').fill('20');assert click('job-level')['ok'];assert snap()['baseJobLevel']==20;assert snap()['skillPoints']==19;passed('Set Job Level uses canonical Skill Point pool',{'class':cls})
   page.locator('#value').fill('500');assert click('base-exp')['ok'];assert click('job-exp')['ok'];assert snap()['baseLevel']>5 and snap()['baseJobLevel']>=20;passed('Base and Job EXP use existing multi-level progression',{'class':cls})
   before=snap();page.locator('#item').fill('herb');page.locator('#count').fill('2');assert click('give-item')['ok'];after=snap();assert after['itemInventory']['stacks']['herb']==before['itemInventory']['stacks']['herb']+2;assert after['itemInventory']['nextItemSerial']==before['itemInventory']['nextItemSerial'];passed('stack grant is canonical with exact count and unchanged serial',{'class':cls})
   page.locator('#item').fill('astral-blade');r=click('give-item');assert r['ok'];gear=r['result']['instanceRewards'];assert len(gear)==2 and len(set(i['instanceId'] for i in gear))==2;assert r['after']['itemInventory']['nextItemSerial']==r['before']['itemInventory']['nextItemSerial']+2;assert all(i['instanceId'] not in snap()['equippedItems'].values() for i in gear);passed('unique grant creates canonical IDs once and does not auto-equip',{'class':cls})
   page.locator('#value').fill('100');r=click('gold');assert r['ok'] and r['after']['gold']==r['before']['gold']+100;reject('return d.money.give(Number.MAX_SAFE_INTEGER)','CURRENCY_OVERFLOW');passed('Gold helper shares canonical wallet and rejects overflow unchanged',{'class':cls})
   page.locator('#skill').fill(skill);assert click('learn')['ok'];assert click('rank')['ok'];assert snap()['learnedSkills'][skill]==2;assert click('reset-skills')['ok'];assert not snap()['learnedSkills'];assert snap()['actionLoadout']==[None]*8;passed('learn rank and paid reset preserve valid skill/loadout state',{'class':cls})
   page.locator('#count').fill('2');page.locator('#stat').select_option('VIT');before=snap();assert click('allocate')['ok'];assert snap()['VIT']==before['VIT']+2;assert click('reset-stats')['ok'];after=snap();assert after['VIT']==1 and after['statPoints']==before['statPoints'] and after['currentHP']<=after['maxHP'];passed('allocate then reset uses canonical paid stat refund/resource clamp',{'class':cls})
   r=click('stats');canonical=game.evaluate('AstraeonProgressionDev.getDerivedStats()');assert r['derived']==canonical and r['primary']['VIT']==1 and 'temporaryEffectModifiers' in r['modifiers'];passed('derived inspector displays Character results and modifier groups',{'class':cls})
   before=snap();r=click('effects');assert 'runtime' in r and 'scope' in r['runtime'];assert snap()==before;passed('effects inspector exposes only supported current status representation',{'class':cls})
   assert game.evaluate('AstraeonQuestDev.accept("quest-proof-kill").ok');before=snap();reject('return await d.world.teleport({zone:99,x:10,y:10})','INVALID_MAP');reject('return await d.world.teleport({zone:2,x:4,y:4})','BLOCKED_POSITION');reject('return d.monsters.spawn("missing",{zone:0,x:10,y:10})','UNKNOWN_MONSTER_DEFINITION');passed('unknown map blocked point and definition reject without mutation',{'class':cls})
   assert game.evaluate('()=>{const p=AstraeonProgressionDev;p.setCurrentHP(Math.max(1,p.snapshot().maxHP-10));window.oldActionItemTicket=p.prepareActionItem("potion",{now:AstraeonQA.snapshot().time,intent:"inventory"});return oldActionItemTicket.ok}')
   page.locator('#zone').fill('2');page.locator('#x').fill('14.5');page.locator('#y').fill('14.5');r=click('teleport');assert r['ok'];s=snap();q=game.evaluate('AstraeonQA.snapshot()');assert s['zone']==2 and s['gold']==before['gold'];assert abs(q['player']['position']['x']-s['x'])<.01 and abs(q['player']['position']['y']-s['y'])<.01;assert q['action'] is None and q['navigation'] is None and q['townServices']['session'] is None;passed('map teleport reconciles transform targeting combat and services without travel fee',{'class':cls})
   game.locator('[data-open="character"]').click();unchanged=snap();stale=game.evaluate('AstraeonProgressionDev.commitActionItem(oldActionItemTicket,{now:AstraeonQA.snapshot().time,intent:"inventory"})');assert stale['code']=='STALE_PACKAGE' and snap()==unchanged;passed('teleport invalidates a valid prepared Action Item without consumption',{'class':cls});page.locator('#x').fill('15');page.locator('#y').fill('15');page.locator('#monster').fill('leafmane-fox');r=click('spawn');assert r['ok'],r;m=r['result']['monster'];id=m['instanceId'];assert m['definitionId']=='leafmane-fox' and m['lifeGeneration']==1 and m['state']=='SPAWN';assert any(e['lifecycle']['instanceId']==id for e in game.evaluate('AstraeonQA.snapshot().enemies'));passed('dev spawn creates real Lifecycle-owned field actor',{'class':cls,'monster':m})
   game.locator('#modal .close').click();game.wait_for_function('id=>AstraeonMonsterLifecycleDev.inspect(id)?.state!=="SPAWN"',arg=id,timeout=30000);game.locator('[data-open="character"]').click();before=snap();r=click('kill');assert r['ok'],r;s=snap();assert r['result']['after']['deathId'] and r['result']['reward']['ok'];assert s['kills']==before['kills']+1 and s['gold']>before['gold']
   quest=game.evaluate('AstraeonQuestDev.inspect("quest-proof-kill")');assert quest['objectives'][0]['progress']==1,quest
   assert 'questKill' in r['result']['policy'];passed('dev kill uses Combat HP and sole Lifecycle death with normal Loot EXP gold and Quest credit',{'class':cls,'deathId':r['result']['after']['deathId'],'reward':r['result']['reward']})
   reject('return d.monsters.kill('+json.dumps(id)+')','ALREADY_DEAD');passed('same-life repeated kill grants no second item EXP gold or Quest increment',{'class':cls})
   page.locator('#zone').fill('0');town=game.evaluate('AstraeonContent.nativeWorld.spatial.safePoint||null');point=game.evaluate('AstraeonQA.snapshot().town.spawn');page.locator('#x').fill(str(point[0]));page.locator('#y').fill(str(point[1]));assert click('teleport')['ok'];game.locator('[data-open="character"]').click();before=snap();r=click('snapshot');assert r==before and r['saveVersion']==5;assert all(k not in r for k in ['tickets','session','listeners']);passed('canonical save snapshot retains Quest Storage gear position but no transient capabilities',{'class':cls})
   game.evaluate('localStorage.setItem("unrelated-dev-evidence","keep");localStorage.setItem("astraeon-quality","medium")');page.locator('#confirmation').fill('WIPE wrong');r=click('wipe');assert not r['ok'] and r['code']=='WIPE_CONFIRMATION_REQUIRED';page.locator('#confirmation').fill('WIPE '+name);r=click('wipe');assert r['ok'] and r['result']['reloadRequired'];assert game.evaluate('localStorage.getItem("astraeon-iso-v1")') is None;assert game.evaluate('localStorage.getItem("unrelated-dev-evidence")')=='keep';assert game.evaluate('localStorage.getItem("astraeon-quality")')=='medium';game.locator('#dev-reload').click();game.wait_for_selector('#create');assert game.evaluate('localStorage.getItem("astraeon-iso-v1")') is None;passed('wipe removes exact test-character key only and pagehide cannot recreate it',{'class':cls});context.close()
  for query in ['', '?qa=1','?dev=0','?dev=01']:
   context=browser.new_context();page=context.new_page();page.set_default_timeout(180000);page.on('pageerror',lambda e:errors.append(str(e)));page.on('console',lambda m:errors.append(m.text) if m.type=='error' else None);page.on('response',lambda r:http_errors.append(f'{r.status} {r.url}') if r.status>=400 else None);page.goto(args.url.rstrip('/')+'/'+query,wait_until='load');page.wait_for_selector('#create');assert page.evaluate('typeof AstraeonDev==="undefined"&&typeof AstraeonDevTools==="undefined"&&typeof AstraeonProgressionDev==="undefined"&&typeof AstraeonMonsterLifecycleDev==="undefined"');passed('normal and non-exact dev URL have no mutation module/API',{'query':query});context.close()
  assert not errors and not http_errors,(errors,http_errors);browser.close();report={'result':'passed','checks':checks,'errors':errors,'httpErrors':http_errors,'expectedRejections':rejections};print('PASS',len(checks),'Dev Tools browser groups',flush=True)
except Exception as exc:
 try:last=game.evaluate('window.AstraeonQA?.snapshot()') if game else None
 except Exception:last=None
 report={'result':'failed','error':str(exc),'checks':checks,'errors':errors,'httpErrors':http_errors,'expectedRejections':rejections,'lastState':last};raise
finally:(args.output/'report.json').write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8')
