const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),child=require('node:child_process');
global.window={};
for(const n of ['input','skill-nodes','combat','progression-config','progression','stats','skill-definitions','skill-tree','action-loadout','skill-runtime','action-runtime','character-state','item-definitions','equipment-slots','item-inventory','inventory-capacity','item-equipment','item-state','action-item-config','item-effects','action-item','action-item-runtime','drop-tables','monster-definitions','loot-resolution','monster-rewards','monster-loot-runtime','box-content-tables','monster-box','monster-box-runtime','player-state','save-state','combat-resolution-config','combat-resolution','combat-runtime','enemy-combat','monster-lifecycle-definitions','monster-lifecycle','monster-combat-runtime'])require('../'+n+'.js');
const D=window.AstraeonItemDefinitions,E=window.AstraeonItemEquipment,R=window.AstraeonEquipmentSlots,S=window.AstraeonSave,I=window.AstraeonItemInventory;
const fixtures={weapon:'astral-blade',offHand:'offhand-proof',armor:'warden-plate',shoes:'shoes-proof',relic:'spirit-charm'};
function fixture(extra={},options={}){const state=S.normalize({name:'Slot disposable',cls:0,legacySkillControls:false,itemInventory:I.normalize(),equippedItems:{},...extra}),p=window.AstraeonPlayer.attach(state,options);return {state,p}}
function catalogWith(id,changes){return {getDefinition:key=>key===id?{...D.getDefinition(id),...changes}:D.getDefinition(key)}}
function capture(f){return {save:S.snapshot(f.state),stats:f.p.getDerivedStats(),capacity:f.p.getInventoryCapacityState(),revision:f.p.getInventoryRevision(),skills:f.p.getActionRuntime(),items:f.p.getActionItemRuntime()}}
function unchanged(f,fn,code){const before=capture(f),result=fn();assert.equal(result.ok,false);if(code)assert.equal(result.code,code);assert.deepEqual(capture(f),before);return result}
function give(f,slot){const result=f.p.createItemInstance(fixtures[slot]);assert(result.ok);return result.instance.instanceId}
function all(f){return Object.fromEntries(R.ids.map(slot=>{const id=give(f,slot);assert(f.p.equip(id,slot).ok);return [slot,id]}))}
for(const slot of R.ids){test('registry active '+slot,()=>{assert.equal(R.getDefinition(slot).id,slot);assert(Object.isFrozen(R.getDefinition(slot)));assert.equal(R.canonical(R.getDefinition(slot).semanticId),slot)});test('valid authored definition '+slot,()=>{const d=D.getDefinition(fixtures[slot]);assert(E.validateDefinition(d).ok);assert(Object.isFrozen(d));assert(Object.isFrozen(d.equipmentSlots))})}
test('active registry deterministic order and validated immutable data',()=>{assert.deepEqual(R.ids,['weapon','offHand','armor','shoes','relic']);assert.deepEqual(R.definitions.map(d=>d.name),['Main Hand','Off Hand','Body','Shoes','Accessory']);assert(R.validate(R.definitions).ok);assert(Object.isFrozen(R.definitions))});
for(const id of ['head','garment','accessory1','accessory2','cosmetic','futureHead','constructor','__proto__',null])test('future/unknown slot inactive '+String(id),()=>{assert.equal(R.canonical(id),null);assert.equal(R.getDefinition(id),null)});
for(const defs of [[],null,[R.definitions[0],R.definitions[0]],[{id:'head',semanticId:'head',name:'Head'}],[{...R.definitions[0],semanticId:'head'}]])test('malformed registry '+JSON.stringify(defs),()=>assert.equal(R.validate(defs).ok,false));
for(const allowed of [[],null,'weapon',['head'],['weapon','weapon'],['weapon','mainHand'],['accessory1'],[42]])test('invalid authored allowedSlots '+JSON.stringify(allowed),()=>{const cat=catalogWith('astral-blade',{equipmentSlots:allowed}),f=fixture({}, {itemCatalog:cat}),id=give(f,'weapon');unchanged(f,()=>f.p.equip(id,'weapon'),'INVALID_EQUIPMENT_DEFINITION')});
for(const modifiers of [null,{},[{add:{unknown:1}}],[{add:{DEF:'1'}}],[{multiply:{DEF:Infinity}}],[{bogus:1}],[{primary:{STR:NaN}}]])test('malformed authored modifiers '+JSON.stringify(modifiers),()=>{const cat=catalogWith('astral-blade',{modifiers}),f=fixture({}, {itemCatalog:cat}),id=give(f,'weapon');unchanged(f,()=>f.p.equip(id,'weapon'))});
test('cyclic authored metadata rejects without equipping',()=>{const metadata={};metadata.cycle=metadata;const f=fixture({}, {itemCatalog:catalogWith('astral-blade',{metadata})}),id=give(f,'weapon');unchanged(f,()=>f.p.equip(id,'weapon'))});
test('non-equipment owned nonstack cannot equip',()=>{const f=fixture({}, {itemCatalog:catalogWith('astral-blade',{kind:'future-object'})}),id=give(f,'weapon');unchanged(f,()=>f.p.equip(id,'weapon'),'NOT_EQUIPMENT')});
for(const slot of R.ids){
 test('empty slot authoritative equip '+slot,()=>{const f=fixture(),id=give(f,slot),inventory=f.p.getInventory(),before=f.p.getInventoryCapacityState(),r=f.p.equip(id,slot);assert(r.ok);assert.equal(r.slot,slot);assert.equal(r.equippedInstanceId,id);assert.equal(r.previousInstanceId,null);assert.equal(f.p.getInventory(),inventory);assert.equal(f.p.getEquipmentSlots()[slot],id);assert.equal(f.p.getEquipped(R.getDefinition(slot).semanticId),id);assert.deepEqual(f.p.getInventoryCapacityState(),before);assert.deepEqual(r.capacity.delta,{slots:0,weight:0});assert(Object.isFrozen(r.equipment))});
 test('atomic replacement preserves both IDs and serial '+slot,()=>{const f=fixture(),old=give(f,slot),next=give(f,slot);f.p.equip(old,slot);const inventory=f.p.getInventory(),stats=f.p.getDerivedStats(),revision=f.p.getInventoryRevision(),r=f.p.equip(next,slot);assert(r.ok);assert.equal(r.previousInstanceId,old);assert.equal(f.p.getEquipped(slot),next);assert(f.p.getInstance(old));assert(f.p.getInstance(next));assert.equal(f.p.getInventory(),inventory);assert.equal(f.p.getInventoryRevision(),revision+1);assert.deepEqual(f.p.getDerivedStats(),stats)});
 test('unequip retains ownership serial capacity '+slot,()=>{const f=fixture(),id=give(f,slot);f.p.equip(id,slot);const before=f.p.getInventory(),capacity=f.p.getInventoryCapacityState(),r=f.p.unequip(slot);assert(r.ok);assert.equal(r.previousInstanceId,id);assert.equal(f.p.getEquipped(slot),null);assert.equal(f.p.getInventory(),before);assert.equal(f.p.getInstance(id).instanceId,id);assert.deepEqual(f.p.getInventoryCapacityState(),capacity);assert(f.p.unequip(slot).ok);assert.equal(f.p.unequip(slot).changed,false)});
 test('unowned identity rejects '+slot,()=>{const f=fixture();unchanged(f,()=>f.p.equip('item-999',slot),'UNKNOWN_INSTANCE')});
 test('slot reference save/reload '+slot,()=>{const f=fixture(),id=give(f,slot);f.p.equip(id,slot);const saved=S.snapshot(f.state),p=window.AstraeonPlayer.attach(saved);assert.equal(p.getEquipped(slot),id);assert.deepEqual(p.getEquipmentSlots(),f.p.getEquipmentSlots());assert.deepEqual(p.getInventory(),f.p.getInventory());assert.deepEqual(p.getDerivedStats(),f.p.getDerivedStats())});
}
for(const slot of ['offHand','armor','shoes','relic'])test('wrong slot rejects and preserves resources '+slot,()=>{const f=fixture(),id=give(f,'weapon');unchanged(f,()=>f.p.equip(id,slot),'WRONG_EQUIPMENT_SLOT')});
for(const slot of ['mainHand','body','accessory'])test('semantic alias explicit compatibility '+slot,()=>{const f=fixture(),id=give(f,R.canonical(slot));assert(f.p.equip(id,slot).ok);assert.equal(f.p.getEquipped(slot),id);assert(f.p.unequip(slot).ok)});
test('flexible instance second-slot occupancy rejects; explicit unequip then equip allowed',()=>{const f=fixture({}, {itemCatalog:catalogWith('astral-blade',{equipmentSlots:['mainHand','offHand']})}),id=give(f,'weapon');assert(f.p.equip(id,'mainHand').ok);unchanged(f,()=>f.p.equip(id,'offHand'),'ALREADY_EQUIPPED');assert(f.p.unequip('mainHand').ok);assert(f.p.equip(id,'offHand').ok);assert.equal(Object.values(f.p.getEquipmentSlots()).filter(x=>x===id).length,1)});
test('repeated five-slot replacement/unequip never clones or accumulates modifiers',()=>{const f=fixture(),ids=all(f),inventory=f.p.getInventory(),derived=f.p.getDerivedStats(),capacity=f.p.getInventoryCapacityState();for(let n=0;n<20;n++){for(const slot of R.ids){assert(f.p.equip(ids[slot],slot).ok);assert(f.p.unequip(slot).ok);assert(f.p.equip(ids[slot],slot).ok)}assert.equal(f.p.getInventory(),inventory);assert.deepEqual(f.p.getDerivedStats(),derived);assert.deepEqual(f.p.getInventoryCapacityState(),capacity)}});
for(const [slot,key,value] of [['weapon','physicalATK',6],['weapon','magicATK',6],['offHand','DEF',1],['armor','DEF',2],['shoes','MDEF',1],['relic','physicalATK',3],['relic','magicATK',3]])test('individual modifier through Stats '+slot+' '+key,()=>{const f=fixture(),base=f.p.getDerivedStats(),id=give(f,slot);assert(f.p.equip(id,slot).ok);assert.equal(f.p.getDerivedStats()[key],base[key]+value);assert(f.p.unequip(slot).ok);assert.deepEqual(f.p.getDerivedStats(),base)});
test('all five modifiers aggregate exactly once; legacy read projection is not second authority',()=>{const f=fixture(),base=f.p.getDerivedStats();all(f);const derived=f.p.getDerivedStats();assert.equal(derived.physicalATK,base.physicalATK+9);assert.equal(derived.magicATK,base.magicATK+9);assert.equal(derived.DEF,base.DEF+3);assert.equal(derived.MDEF,base.MDEF+1);assert.equal(f.p.getEquipmentModifiers().length,5);assert.deepEqual(Object.keys(f.p.getEquipment()),['weapon','armor','relic']);assert.deepEqual(Object.keys(f.p.getEquipmentSlots()),R.ids);assert(Object.isFrozen(f.p.getEquipmentSlots()))});
test('outgoing physical and magical Combat sees Main Hand Stats',()=>{for(const cls of [0,12]){const f=fixture({cls}),category=cls===0?'physical':'magical',action=window.AstraeonCombat.compile(cls===0?'warrior':'mage','attack');function resolve(){const input=window.AstraeonCombatRuntime.buildInput({attackerLevel:1,attackerStats:f.p.getDerivedStats(),action,damageType:category});return window.AstraeonCombatResolution.resolveAttack(input,{rng:window.AstraeonCombatRuntime.sequenceRng([.5,.5,.5])})}const before=resolve(),id=give(f,'weapon');f.p.equip(id,'weapon');const after=resolve();assert(before.ok&&after.ok);assert(after.finalDamage>before.finalDamage)}});
test('incoming shared Combat sees Body plus Off Hand once',()=>{const f=fixture();function resolve(){return window.AstraeonMonsterCombatRuntime.resolve({damage:12,player:f.p,rng:window.AstraeonCombatRuntime.sequenceRng([])})}const before=resolve();for(const slot of ['armor','offHand'])f.p.equip(give(f,slot),slot);const after=resolve();assert(before.ok&&after.ok);assert.equal(before.result.finalDamage-after.result.finalDamage,3);assert.equal(after.hp.hpBefore,f.p.snapshot().currentHP)});
for(const [resource,max,key,slot] of [['currentHP','maxHP','maxHP','offHand'],['currentSP','maxSP','maxSP','shoes']])test('max-resource gear safe no heal and clamp '+resource,()=>{const f=fixture({}, {itemCatalog:catalogWith(fixtures[slot],{modifiers:[{add:{[key]:30}}]})}),id=give(f,slot);f.p[resource==='currentHP'?'setCurrentHP':'setCurrentSP'](10);const before=f.p.snapshot()[max];f.p.equip(id,slot);assert.equal(f.p.snapshot()[resource],10);assert.equal(f.p.snapshot()[max],before+30);f.p[resource==='currentHP'?'setCurrentHP':'setCurrentSP'](before+30);f.p.unequip(slot);assert.equal(f.p.snapshot()[resource],before)});
for(const slot of R.ids)test('weighted owned instance counted once equipped '+slot,()=>{const cat=catalogWith(fixtures[slot],{weight:.125}),f=fixture({}, {itemCatalog:cat}),id=give(f,slot),before=f.p.getInventoryCapacityState();assert.equal(before.occupiedSlots,1);assert.equal(before.totalWeight,.125);f.p.equip(id,slot);assert.deepEqual(f.p.getInventoryCapacityState(),before);f.p.unequip(slot);assert.deepEqual(f.p.getInventoryCapacityState(),before)});
test('over-limit equip unequip replacement remains no worse ownership',()=>{let policy=window.AstraeonInventoryCapacity.defaultPolicy;const f=fixture({}, {getCapacityPolicy:()=>policy}),a=give(f,'offHand'),b=give(f,'offHand');policy={mode:'bounded',slotLimit:0,weightLimit:0,overLimitPolicy:'no-worse'};assert(f.p.getInventoryCapacityState().isOverLimit);assert(f.p.equip(a,'offHand').ok);assert(f.p.equip(b,'offHand').ok);assert(f.p.unequip('offHand').ok);assert.equal(f.p.getInventoryCapacityState().occupiedSlots,2)});
for(const id of Object.values(fixtures))test('Monster Loot normal instance reward equips '+id,()=>{const f=fixture(),table={id:'slot-proof',entries:[{id:'gear',itemId:id,rollMode:'guaranteed',chance:1,minQuantity:1,maxQuantity:1}]},tables={getDefinition:()=>table},definitions={getDefinition:()=>({id:'slot-monster',dropTableId:table.id,rewardProfileId:'proof',metadata:{fixture:true}})},loot=window.AstraeonMonsterLootRuntime.create({commit:(r,p)=>f.p.commitMonsterRewards(r,p)},{tables,monsters:definitions}),actor={hp:1};assert(loot.register(actor,'slot-monster').ok);actor.hp=0;const claim=loot.prepareDeath(actor,f.p.getMonsterRewardContext(2),{next:()=>{throw Error('guaranteed should not roll')}}),result=loot.commit(claim);assert(result.ok);const gear=result.instanceRewards[0];assert(Object.values(f.p.getEquipmentSlots()).every(x=>x===null));assert.equal(loot.commit(claim).code,'ALREADY_COMMITTED');assert(f.p.equip(gear.instanceId,D.getDefinition(id).equipmentSlots[0]).ok)});
for(const id of Object.values(fixtures))test('Monster Box canonical gear reward and envelope '+id,()=>{let draws=0;const f=fixture({}, {boxTables:{getDefinition:()=>({id:'box-proof-basic',entries:[{id:'gear',itemId:id,rollMode:'guaranteed',minQuantity:1,maxQuantity:1}]})},getBoxRng:()=>({next:()=>{draws++;return .5}})});f.p.addStack('monster-box-proof',2);const ticket=f.p.prepareMonsterBoxOpen('monster-box-proof',2);assert(ticket.ok&&ticket.authorizationOnly);assert.equal(draws,0);const result=f.p.commitMonsterBoxOpen(ticket);assert(result.ok);assert.equal(result.instanceRewards.length,2);assert.equal(f.p.getQuantity('monster-box-proof'),0);assert.equal(result.serialAfter-result.serialBefore,2);assert.equal(new Set(result.instanceRewards.map(i=>i.instanceId)).size,2);assert(Object.values(f.p.getEquipmentSlots()).every(x=>x===null));assert.equal(f.p.commitMonsterBoxOpen(ticket).code,'ALREADY_COMMITTED');assert(f.p.equip(result.instanceRewards[0].instanceId,D.getDefinition(id).equipmentSlots[0]).ok)});
test('gear-only mutation invalidates Box authorization before entropy',()=>{let draws=0;const f=fixture({}, {getBoxRng:()=>({next:()=>{draws++;return .8}})});f.p.addStack('monster-box-proof',1);const id=give(f,'shoes'),ticket=f.p.prepareMonsterBoxOpen('monster-box-proof');f.p.equip(id,'shoes');unchanged(f,()=>f.p.commitMonsterBoxOpen(ticket),'STALE_PACKAGE');assert.equal(draws,0)});
for(const recipe of ['blade','plate','charm'])test('existing canonical crafted gear equips '+recipe,()=>{const f=fixture();f.p.reward({ore:20,shard:20,herb:20});const r=f.p.craft(recipe);assert(r.ok);const id=Object.keys(r.inventory.instances).at(-1);assert(f.p.equip(id,D.getDefinition(f.p.getInstance(id).definitionId).equipmentSlots[0]).ok)});
test('merchant unchanged stacks and no equipment economy invented',()=>{const f=fixture();assert(f.p.buy('potion').ok);assert(f.p.sell('herb').ok===false);unchanged(f,()=>f.p.buy('offhand-proof'),'INVALID_TRADE')});
for(const [legacy,id] of [['weapon','astral-blade'],['armor','warden-plate'],['relic','spirit-charm']])test('pre-v5 legacy equipped meaning preserved '+legacy,()=>{const raw={name:'Legacy slots',saveVersion:4,equipment:{weapon:'None',armor:'None',relic:'None',[legacy]:D.getDefinition(id).name},inventory:{blade:1,plate:1,charm:1}},state=S.normalize(raw),p=window.AstraeonPlayer.attach(state);assert.equal(p.getInstance(p.getEquipped(legacy)).definitionId,id);assert.equal(Object.values(p.getInventory().instances).filter(i=>i.definitionId===id).length,1);assert.equal(p.getInventory().nextItemSerial,4);assert.deepEqual(S.normalize(S.snapshot(state)),S.snapshot(state))});
for(const [key,slot] of [['mainHand','weapon'],['body','armor'],['accessory','relic']])test('canonical ownership semantic-key migration '+key,()=>{const f=fixture(),id=give(f,slot),raw=S.snapshot(f.state);raw.equippedItems={[key]:id};const normalized=S.normalize(raw);assert.equal(normalized.equippedItems[slot],id);assert.deepEqual(normalized.itemInventory,raw.itemInventory);assert.deepEqual(S.normalize(normalized),normalized)});
for(const canonical of ['item-1',null,'missing'])test('conflicting alias preserves both owned instances '+String(canonical),()=>{const f=fixture(),a=give(f,'weapon'),b=give(f,'weapon'),raw=S.snapshot(f.state);raw.equippedItems={weapon:canonical,mainHand:b};const normalized=S.normalize(raw);assert.equal(normalized.equippedItems.weapon,canonical===a?a:null);assert.deepEqual(normalized.itemInventory,raw.itemInventory);assert(normalized.itemHistory.equipmentSlotNormalization.some(i=>i.code==='SLOT_ALIAS_CONFLICT'));assert.deepEqual(S.normalize(normalized),normalized)});
for(const key of ['head','garment','futureHead','unknown'])test('unknown saved slot retained as evidence without effects '+key,()=>{const f=fixture(),id=give(f,'weapon'),raw=S.snapshot(f.state);raw.equippedItems={[key]:id};const restored=fixture(S.normalize(raw));assert.equal(restored.p.getEquipped('weapon'),null);assert(restored.p.getInstance(id));assert.equal(restored.p.getInventory().nextItemSerial,2);assert.equal(restored.state.itemHistory.equipmentSlotNormalization[0].code,'UNKNOWN_EQUIPMENT_SLOT');assert.equal(restored.p.getDerivedStats().physicalATK,fixture().p.getDerivedStats().physicalATK)});
test('malformed and duplicate references normalize with no instance loss',()=>{const f=fixture(),ids=all(f),raw=S.snapshot(f.state);raw.equippedItems={weapon:ids.weapon,offHand:ids.weapon,armor:'missing',shoes:ids.shoes,relic:ids.shoes};const next=S.normalize(raw);assert.deepEqual(next.itemInventory,raw.itemInventory);assert.equal(next.equippedItems.offHand,null);assert.equal(next.equippedItems.armor,null);assert.equal(next.equippedItems.relic,null);assert(next.itemHistory.equipmentSlotNormalization.length>=3);assert.deepEqual(S.normalize(next),next)});
for(const cls of [0,12])test('twenty five-slot normalize save attach cycles stable '+cls,()=>{let f=fixture({cls});all(f);const expected=capture(f);for(let n=0;n<20;n++){f=fixture(S.normalize(JSON.parse(JSON.stringify(S.snapshot(f.state)))));assert.deepEqual(S.snapshot(f.state),expected.save);assert.deepEqual(f.p.getInventoryCapacityState(),expected.capacity);assert.deepEqual(f.p.getDerivedStats(),expected.stats);assert.deepEqual(f.p.getInventory(),expected.save.itemInventory)}});
for(const cls of [0,12])test('death respawn travel class transition preserve five slots '+cls,()=>{const f=fixture({cls});all(f);const inventory=f.p.getInventory(),equipment=f.p.getEquipmentSlots(),capacity=f.p.getInventoryCapacityState();f.p.setCurrentHP(0);f.p.invalidatePreparedActions();f.p.setCurrentHP(80);for(const zone of [2,1,0]){f.state.zone=zone;f.p.invalidatePreparedActions();assert.equal(f.p.getInventory(),inventory);assert.equal(f.p.getEquipmentSlots(),equipment);assert.deepEqual(f.p.getInventoryCapacityState(),capacity)}f.state.cls=cls===0?12:0;f.p.recalculate();assert.deepEqual(f.p.getEquipmentSlots(),equipment)});
test('Action Item and learned actions independent of all equipment slots',()=>{const f=fixture({baseJobLevel:20,skillPoints:10});all(f);f.p.addStack('potion',1);f.p.setCurrentHP(1);f.p.setCurrentSP(60);f.p.learnSkill('rising-edge');f.p.assignSkill(7,'rising-edge');const slots=f.p.getEquipmentSlots(),serial=f.p.getInventory().nextItemSerial;assert(f.p.useConsumable('potion',{now:0}).ok);assert(f.p.requestAction(7,{now:0},()=>true).ok);assert.deepEqual(f.p.getEquipmentSlots(),slots);assert.equal(f.p.getInventory().nextItemSerial,serial);assert(!f.p.getLoadout().some(id=>Object.values(fixtures).includes(id)))});
test('save version remains v5 without unsupported-future downgrade',()=>{assert.equal(S.version,5);const f=fixture();all(f);assert.equal(S.snapshot(f.state).saveVersion,5);const future={saveVersion:6,unknownSlots:{head:'item-1'}},before=structuredClone(future);assert.throws(()=>S.normalize(future),S.UnsupportedSaveError);assert.deepEqual(future,before)});
test('registry loads before equipment in normal boot and every item harness',()=>{for(const file of ['boot.js','tools/inventory.html','tools/monster-loot.html','tools/monster-box.html','tools/monster-lifecycle.html','tools/progression.html','tools/inventory-capacity.html']){const s=fs.readFileSync(require.resolve('../'+file),'utf8');assert(s.indexOf('equipment-slots.js')>s.indexOf('item-definitions.js'));assert(s.indexOf('equipment-slots.js')<s.indexOf('item-equipment.js'))}assert(fs.readFileSync(require.resolve('../sw.js'),'utf8').includes('equipment-slots.js?v=94'))});
test('protected visual and stable systems unchanged from authoritative parent',()=>{const parent='621b1cd214218078beb70392f647a48a9bfdef25';for(const file of ['stats.js','progression.js','skill-tree.js','skill-runtime.js','combat-resolution.js','combat-runtime.js','action-item.js','action-item-runtime.js','action-loadout.js','monster-loot-runtime.js','monster-box.js','monster-box-runtime.js','box-content-tables.js','drop-tables.js','monster-lifecycle.js','monster-combat-runtime.js','inventory-capacity.js','item-inventory.js','save-state.js','style.css'])assert.equal(fs.readFileSync(require.resolve('../'+file),'utf8').replace(/\r\n/g,'\n'),child.execFileSync('git',['show',parent+':'+file]).toString().replace(/\r\n/g,'\n'));assert(!child.execFileSync('git',['diff','--name-only',parent]).toString().split('\n').some(p=>/^(assets|world|authoring|RO3 Ref)\//.test(p)))});

test('equipment requirement callback nested inventory mutation rejects under validation lock',()=>{let f,nested;f=fixture({}, {equipmentRequirements:()=>{nested=f.p.addStack('herb',1);return true}});const id=give(f,'offHand'),before=f.p.getInventory();assert(f.p.equip(id,'offHand').ok);assert.equal(nested.code,'TRANSACTION_IN_PROGRESS');assert.equal(f.p.getInventory(),before);assert.equal(f.p.getQuantity('herb'),0)});
test('failed replacement restriction keeps previous occupant and Stats atomically',()=>{let allowed=true;const f=fixture({}, {equipmentRequirements:()=>allowed}),a=give(f,'offHand'),b=give(f,'offHand');assert(f.p.equip(a,'offHand').ok);allowed=false;unchanged(f,()=>f.p.equip(b,'offHand'),'EQUIPMENT_REQUIREMENTS');assert.equal(f.p.getEquipped('offHand'),a)});
test('non-equipment stack cannot carry equip capability into active slots',()=>{assert.equal(E.validateDefinition({...D.getDefinition('herb'),equipmentSlots:['offHand']}).code,'NOT_EQUIPMENT');const f=fixture();f.p.addStack('herb',1);unchanged(f,()=>f.p.equip('herb','offHand'),'UNKNOWN_INSTANCE')});
test('five owned weighted instances count five slots once despite all references',()=>{const catalog={getDefinition:id=>{const d=D.getDefinition(id);return d?{...d,weight:d.kind==='equipment'?.125:d.weight}:null}},f=fixture({}, {itemCatalog:catalog});all(f);assert.equal(f.p.getInventoryCapacityState().occupiedSlots,5);assert.equal(f.p.getInventoryCapacityState().totalWeight,.625);for(const slot of R.ids)f.p.unequip(slot);assert.equal(f.p.getInventoryCapacityState().occupiedSlots,5);assert.equal(f.p.getInventoryCapacityState().totalWeight,.625)});
test('replacement removes prior authored modifiers instead of adding both occupants',()=>{const f=fixture(),a=give(f,'weapon'),b=f.p.createItemInstance('traveler-blade').instance.instanceId,base=f.p.getDerivedStats();f.p.equip(a,'weapon');assert.equal(f.p.getDerivedStats().physicalATK,base.physicalATK+6);f.p.equip(b,'weapon');assert.deepEqual(f.p.getDerivedStats(),base);assert.equal(f.p.getEquipmentModifiers().length,0)});

for(const changes of [{id:''},{id:null},{maxStack:2},{maxStack:NaN}])test('invalid canonical equipment definition identity/stack contract '+JSON.stringify(changes),()=>assert.equal(E.validateDefinition({...D.getDefinition('offhand-proof'),...changes}).ok,false));
for(const map of [null,[],false,1,'1'])test('malformed modifier map rejects '+JSON.stringify(map),()=>{const f=fixture({}, {itemCatalog:catalogWith('shoes-proof',{modifiers:[{add:map}]})}),id=give(f,'shoes');unchanged(f,()=>f.p.equip(id,'shoes'))});

for(const [label,make] of [['null',()=>null],['undefined',()=>undefined],['empty',()=>''],['number',()=>1],['object',()=>({})],['boxed string',id=>new String(id)],['array',id=>[id]],['symbol',id=>Symbol(id)],['coercion callback',id=>({toString(){throw Error('Identity must never coerce')}})]])test('non-string/empty instance identity rejects without mutation: '+label,()=>{const f=fixture(),id=give(f,'weapon');assert(f.p.equip(id,'weapon').ok);const bad=make(id);assert.equal(f.p.canEquip(bad,'weapon').code,'UNKNOWN_INSTANCE');unchanged(f,()=>f.p.equip(bad,'weapon'),'UNKNOWN_INSTANCE')});
