"""Equipment Slot Closure acceptance: five slots and retained real two-class integration smoke."""
import argparse,json,os,tempfile,time
from pathlib import Path
from playwright.sync_api import sync_playwright,TimeoutError as PlaywrightTimeout
parser=argparse.ArgumentParser();parser.add_argument('--url',default='http://127.0.0.1:8011');parser.add_argument('--browser',default=os.environ.get('ASTRAEON_BROWSER',r'C:\Program Files\Google\Chrome\Application\chrome.exe' if os.name=='nt' else '/usr/bin/chromium'));parser.add_argument('--output',type=Path,default=Path(tempfile.gettempdir())/'astraeon-equipment-slots-browser');args=parser.parse_args();args.output.mkdir(parents=True,exist_ok=True)
BOX='monster-box-proof';checks,errors,http_errors,timing=[],[],[],[];report={}
def passed(name,evidence=None):checks.append({'name':name,'evidence':evidence});print('PASS',name,flush=True)
def qa(page):return page.evaluate('AstraeonQA.snapshot()')
def dev(page,code):return page.evaluate('()=>{const d=AstraeonProgressionDev,b=AstraeonMonsterBoxDev,l=AstraeonMonsterLifecycleDev;'+code+'}')
def snap(page):return dev(page,'return d.snapshot()')
def close(page):
    if qa(page)['windowName']:page.locator('#modal .close').click()
def pause(page):
    close(page);page.locator('[data-open="character"]').click()
def place(page,x,y):assert dev(page,f'return l.placePlayer({x},{y})')['ok']
def inspect(page,id):return dev(page,'return l.inspect('+json.dumps(id)+')')
def point(page,x,y):
    s=qa(page);v,c=s['view'],s['camera'];rect=page.locator('#world').bounding_box()
    return (rect['x']+rect['width']/2+(x*v['basis']['xx']+y*v['basis']['yx']-c['x'])*v['zoom'],rect['y']+rect['height']*v['anchorY']+(x*v['basis']['xy']+y*v['basis']['yy']-c['y'])*v['zoom'])
def learned_contact(page,id,slot,skill):
    for attempt in range(3):
        actor=inspect(page,id);close(page);place(page,actor['position']['x'],actor['position']['y']-.7)
        x,y=point(page,actor['position']['x'],actor['position']['y']);page.mouse.click(x,y-16)
        page.wait_for_function('!AstraeonQA.snapshot().action')
        page.wait_for_function('slot=>AstraeonProgressionDev.getActionSlotState(slot).cooldownRemaining===0',arg=slot,timeout=30000)
        assert dev(page,'return d.executeActionSlot('+str(slot)+')')['ok']
        try:
            page.wait_for_function('skill=>AstraeonCombatDev.results().some(r=>r.result.ok&&r.result.input.context.sourceSkillId===skill)',arg=skill,timeout=10000)
            return
        except PlaywrightTimeout:
            timing.append({'event':'bounded learned skill retarget','attempt':attempt+1,'skill':skill,'state':inspect(page,id),'qa':qa(page)})
    raise AssertionError(('learned skill did not contact actual monster',skill,inspect(page,id)))
def fight(page,id):
    deadline=time.monotonic()+90
    while inspect(page,id)['hp']>0:
        assert time.monotonic()<deadline,('bounded real encounter',inspect(page,id),qa(page)['navigation'])
        close(page);dev(page,'d.setCurrentHP(d.snapshot().maxHP);d.setCurrentSP(d.snapshot().maxSP)');actor=inspect(page,id);place(page,actor['position']['x'],actor['position']['y']-.7)
        x,y=point(page,actor['position']['x'],actor['position']['y']);page.mouse.click(x,y-16);button=page.locator('[data-action="attack"]').bounding_box();page.mouse.move(button['x']+button['width']/2,button['y']+button['height']/2);page.mouse.down()
        try:page.wait_for_function('id=>AstraeonMonsterLifecycleDev.inspect(id)?.hp===0',arg=id,timeout=8000)
        except PlaywrightTimeout:timing.append({'event':'bounded Basic Attack retry','id':id,'state':inspect(page,id)})
        finally:page.mouse.up()
try:
    with sync_playwright() as p:
        browser=p.chromium.launch(executable_path=args.browser,headless=True,args=['--no-sandbox','--enable-gpu']+(['--use-angle=d3d11'] if os.name=='nt' else ['--use-angle=swiftshader','--enable-unsafe-swiftshader']))
        def open_page(path='/?qa=1&dev=1'):
            context=browser.new_context(viewport={'width':1280,'height':800});page=context.new_page();page.set_default_timeout(180000)
            page.on('pageerror',lambda e:errors.append(str(e)));page.on('console',lambda m:errors.append(m.text) if m.type=='error' else None);page.on('response',lambda r:http_errors.append(f'{r.status} {r.url}') if r.status>=400 else None)
            page.goto(args.url.rstrip('/')+path,wait_until='load');return context,page
        for cls,skill in [('0','rising-edge'),('12','ember-bloom')]:
            context,page=open_page();page.wait_for_selector('#create');page.locator('#newname').fill('Box '+cls);page.locator('#newclass').select_option(cls);page.locator('#create').click();page.wait_for_selector('#world');pause(page);assert [x['name'] for x in dev(page,'return d.getEquipmentSlotRegistry()')]==['Main Hand','Off Hand','Body','Shoes','Accessory'];assert list(dev(page,'return d.getEquipmentSlots()'))==['weapon','offHand','armor','shoes','relic'];passed('normal character boot with canonical v5 inventory',{'class':cls})
            before=snap(page);award=dev(page,"const prepared=AstraeonMonsterLootDev.prepareFixture('proof-monster-box');return {prepared,result:AstraeonMonsterLootDev.commitFixture(),box:d.getQuantity('monster-box-proof'),runtime:b.state()} ")
            assert award['result']['ok'] and award['box']==1;assert award['runtime']['pending'] is None;assert qa(page)['monsterBoxes']['events']==[]
            for key in ['baseExp','baseJobExp','kills','quest','gold']:assert snap(page)[key]==before[key],key
            assert dev(page,"return AstraeonMonsterLootDev.duplicateFixture().code")=='ALREADY_COMMITTED';passed('controlled Monster Loot awards unopened canonical Box without opening or progression',{'class':cls,'award':award})
            separation=dev(page,"return {skill:AstraeonSkillDefinitions.getDefinition('monster-box-proof'),action:AstraeonActionItem.compile('monster-box-proof'),slots:d.getLoadout(),item:b.definitions().item}")
            assert separation['skill'] is None and not separation['action']['ok'] and BOX not in separation['slots'];assert separation['item']['stackable'];passed('Box remains outside learned slots and Action Item capabilities',{'class':cls})
            before=snap(page);clocks=dev(page,'return d.getActionItemRuntime()');prepared=dev(page,"b.setRolls([.4]);window.boxTicket=b.prepare('monster-box-proof');return window.boxTicket")
            assert prepared['authorizationOnly'] and 'boxes' not in prepared and 'resolution' not in prepared;assert snap(page)==before;close(page);page.locator('[data-open="inventory"]').click();page.locator('[data-item="monster-box-proof"]').click();after=snap(page)
            assert after['itemInventory']['stacks'].get(BOX,0)==0 and after['inventory']['potion']==before['inventory']['potion']+1;assert len(qa(page)['monsterBoxes']['events'])==1
            for key in ['currentHP','currentSP','gold','baseExp','baseJobExp','kills','quest','skillPoints','learnedSkills','actionLoadout']:assert after[key]==before[key],key
            assert dev(page,'return d.getActionItemRuntime()')==clocks;assert dev(page,'return b.commit(window.boxTicket).code')=='STALE_PACKAGE';assert snap(page)==after;passed('existing Bag single-open consumes once and grants exact content; no HP/SP/EXP/cooldown effects',{'class':cls})
            setup=dev(page,"d.addStack('monster-box-proof',3);b.setRolls([.8]);window.boxTicket=b.prepare('monster-box-proof');const copied=b.commit(structuredClone(window.boxTicket)),opened=b.commit(window.boxTicket),duplicate=b.commit(window.boxTicket);return {copied,opened,duplicate,stats:d.getDerivedStats(),equipped:d.getEquipped('weapon')} ")
            assert setup['copied']['code']=='INVALID_PACKAGE' and setup['duplicate']['code']=='ALREADY_COMMITTED';opened=setup['opened'];assert opened['ok'] and len(opened['instanceRewards'])==1 and opened['serialAfter']==opened['serialBefore']+1;gear=opened['instanceRewards'][0];assert gear['instanceId']!=setup['equipped'];assert dev(page,'return d.getInstance('+json.dumps(gear['instanceId'])+')')==gear
            equipped=dev(page,'const result=d.equip('+json.dumps(gear['instanceId'])+',"weapon");return {result,stats:d.getDerivedStats()}');assert equipped['result']['ok'];assert equipped['stats']['physicalATK']==setup['stats']['physicalATK']+6 and equipped['stats']['magicATK']==setup['stats']['magicATK']+6;passed('copied/duplicate guards and canonical equipment outcome reaches Equipment/Stats',{'class':cls,'gear':gear})
            before=snap(page);bulk=dev(page,"d.addStack('monster-box-proof',3);b.setRolls([0,0,.4,.8]);return b.open('monster-box-proof',3)");after=snap(page)
            assert bulk['ok'] and bulk['openedCount']==3 and len(bulk['boxes'])==3 and bulk['quantityBefore']==5 and bulk['quantityAfter']==2;assert [x['itemRewards'][0]['itemId'] for x in bulk['boxes']]==['herb','potion','astral-blade'];assert after['inventory']['herb']==before['inventory']['herb']+2 and after['inventory']['potion']==before['inventory']['potion']+1;assert bulk['serialAfter']==bulk['serialBefore']+1;assert dev(page,'return d.getEquipped("weapon")')==gear['instanceId'];passed('deterministic bulk three consumes exact N and commits aggregated stacks plus distinct gear',{'class':cls,'bulk':bulk})
            stale=dev(page,"window.boxTicket=b.prepare('monster-box-proof');d.addStack('ore',1);const before=d.snapshot(),result=b.commit(window.boxTicket);return {before,result,after:d.snapshot()}");assert stale['result']['code']=='STALE_PACKAGE' and stale['after']==stale['before'];passed('inventory mutation makes opening authorization stale without grants',{'class':cls})
            used=dev(page,"d.setCurrentHP(1);d.resetActionItemCooldowns();const before=d.getQuantity('potion'),result=d.useConsumable('potion');return {before,result,after:d.getQuantity('potion'),hp:d.snapshot().currentHP,clock:d.getActionItemRuntime()} ");assert used['result']['ok'] and used['after']==used['before']-1 and used['hp']>1
            before=snap(page);independent=dev(page,"b.setRolls([.4]);return b.open('monster-box-proof',1)");assert independent['ok'];assert snap(page)['currentHP']==before['currentHP'] and snap(page)['currentSP']==before['currentSP'];assert dev(page,'return d.getActionItemRuntime()')==used['clock'];passed('Box Potion works through Action Item; healing cooldown does not block or change Box open',{'class':cls})
            close(page);page.locator('[data-open="systems"]').click();page.locator('[data-nav="market"]').click();page.locator('[data-buy="herb:5"]').click();page.locator('[data-sell="herb:2"]').click();close(page);page.locator('[data-open="systems"]').click();page.locator('[data-nav="craft"]').click();prior=snap(page);page.locator('[data-craft="0"]').click();assert snap(page)['inventory']['potion']==prior['inventory']['potion']+1;assert snap(page)['itemInventory']['stacks'][BOX]==1;passed('existing merchant/crafting remain canonical alongside unopened Box',{'class':cls})
            pause(page);setup=dev(page,f"d.setBaseLevel(8);d.setBaseJobLevel(20);d.addSkillPoints(50);return {{learned:d.learnSkill('{skill}'),assigned:d.assignSkill(7,'{skill}')}}");assert setup['learned']['ok'] and setup['assigned']['ok'];dev(page,"window.boxTicket=b.prepare('monster-box-proof');d.setCurrentHP(d.snapshot().maxHP);d.setCurrentSP(d.snapshot().maxSP)");close(page);page.locator('[data-open="journal"]').click();page.locator('[data-quest="2"]').click();page.locator('[data-open="map"]').click();page.locator('[data-travel="2"]').click();page.wait_for_function('AstraeonQA.snapshot().save.zone===2');pause(page);assert dev(page,'return b.commit(window.boxTicket).code')=='STALE_PACKAGE';assert snap(page)['itemInventory']['stacks'][BOX]==1;passed('travel invalidates outstanding Box authorization and preserves quantity',{'class':cls})
            actor=next(e['lifecycle'] for e in qa(page)['enemies'] if e['hp']>0);id=actor['instanceId'];home=actor['home'];before=snap(page);learned_contact(page,id,7,skill);fight(page,id);pause(page);dead=inspect(page,id);events=[e for e in qa(page)['loot']['events'] if e['deathId']==dead['deathId']]
            assert len(events)==1 and dead['state'] in ['DEAD','RESPAWN_WAIT'];after=snap(page);assert after['kills']==before['kills']+1 and after['gold']==before['gold']+events[0]['currencyGranted'];assert after['baseExp']==before['baseExp']+events[0]['baseExp'] and after['baseJobExp']==before['baseJobExp']+events[0]['jobExp'];assert events[0]['questCredit']==1;assert after['itemInventory']['stacks'][BOX]==1
            combat=dev(page,'return AstraeonCombatDev.results().filter(r=>r.result.ok)')
            assert any(r['result']['input']['context'].get('sourceSkillId')==skill and r['result']['input']['attacker']['stats']['physicalATK' if cls=='0' else 'magicATK']==dev(page,'return d.getDerivedStats()')['physicalATK' if cls=='0' else 'magicATK'] for r in combat)
            duplicate=dev(page,'return AstraeonMonsterLootDev.repeatDeath('+json.dumps(id)+')');assert duplicate['code']=='ALREADY_COMMITTED' and snap(page)==after;passed('real learned Skill/Basic Attack consume box-derived gear Stats and retain exactly-once death rewards',{'class':cls,'death':dead,'event':events[0]})
            place(page,14.5,14.5);close(page);page.wait_for_function('({id,life})=>AstraeonMonsterLifecycleDev.inspect(id)?.lifeGeneration===life+1',arg={'id':id,'life':actor['lifeGeneration']},timeout=60000);assert inspect(page,id)['deathId'] is None;fight(page,id);pause(page);second=inspect(page,id);assert second['deathId']!=dead['deathId'];events=[e for e in qa(page)['loot']['events'] if e['deathId'].startswith(id+':')];assert len(events)==2;assert snap(page)['itemInventory']['stacks'][BOX]==1;passed('Monster Lifecycle respawns new life and second legitimate death rewards without Box replay',{'class':cls})
            dev(page,"for(const [slot,id] of Object.entries({weapon:'astral-blade',offHand:'offhand-proof',armor:'warden-plate',shoes:'shoes-proof',relic:'spirit-charm'})){const item=d.createItemInstance(id);d.equip(item.instance.instanceId,slot)}");five_before_death=dev(page,'return d.getEquipmentSlots()');living=next(e['lifecycle'] for e in qa(page)['enemies'] if e['hp']>0);ownership=snap(page)['itemInventory'];place(page,living['position']['x'],living['position']['y']-.7);dev(page,"window.boxTicket=b.prepare('monster-box-proof');d.setCurrentHP(1)");close(page);page.wait_for_function('AstraeonQA.snapshot().save.currentHP===0',timeout=60000);assert all(e['lifecycle']['targetId'] is None for e in qa(page)['enemies']);page.wait_for_function('AstraeonQA.snapshot().save.zone===0&&AstraeonQA.snapshot().save.currentHP>0',timeout=30000);pause(page);assert dev(page,'return d.getEquipmentSlots()')==five_before_death;assert snap(page)['itemInventory']==ownership and dev(page,'return b.commit(window.boxTicket).code')=='STALE_PACKAGE';passed('actual player death/respawn preserves remaining Boxes/contents and invalidates ticket',{'class':cls})
            dev(page,'d.save()');saved=snap(page);page.reload(wait_until='load');page.wait_for_selector('#world');pause(page);loaded=snap(page)
            for key in ['itemInventory','equippedItems','gold','kills','baseExp','baseJobExp','quest']:assert loaded[key]==saved[key],key
            assert loaded['saveVersion']==5 and qa(page)['monsterBoxes']['events']==[] and qa(page)['monsterBoxes']['runtime']['pending'] is None;assert qa(page)['loot']['events']==[];passed('save/reload preserves unopened Box and committed contents/serial without opening/death replay',{'class':cls})
            close(page);page.locator('[data-open="map"]').click();page.locator('[data-travel="2"]').click();page.wait_for_function('AstraeonQA.snapshot().save.zone===2');page.locator('[data-open="map"]').click();page.locator('[data-travel="0"]').click();page.wait_for_function('AstraeonQA.snapshot().save.zone===0');pause(page);assert snap(page)['itemInventory']==loaded['itemInventory'] and snap(page)['kills']==loaded['kills'];assert qa(page)['monsterBoxes']['events']==[];passed('town/field round trip does not refund or duplicate Boxes/contents',{'class':cls})
            proof=dev(page,"const defs={weapon:'astral-blade',offHand:'offhand-proof',armor:'warden-plate',shoes:'shoes-proof',relic:'spirit-charm'};for(const slot of d.getEquipmentSlotRegistry())d.unequip(slot.id);const base=d.getDerivedStats(),ids=Object.fromEntries(Object.entries(defs).map(([slot,id])=>[slot,d.createItemInstance(id).instance.instanceId]));return {base,ids,capacity:d.getInventoryCapacityState(),inventory:d.getInventory()}")
            close(page);page.locator('[data-open="inventory"]').click()
            for slot,id in proof['ids'].items():
                assert page.locator('[data-equipment-slot="'+slot+'"]').count()==1
                page.locator('[data-equip-instance="'+id+'"][data-equip-slot="'+slot+'"]').click()
                assert dev(page,'return d.getEquipped('+json.dumps(slot)+')')==id
                assert dev(page,'return d.getInventory()')==proof['inventory'] and dev(page,'return d.getInventoryCapacityState()')==proof['capacity']
                passed('ordinary Bag equips canonical '+slot+' without ownership/serial/capacity drift',{'class':cls,'instance':id})
            stats=dev(page,'return d.getDerivedStats()');assert stats['physicalATK']==proof['base']['physicalATK']+9 and stats['magicATK']==proof['base']['magicATK']+9 and stats['DEF']==proof['base']['DEF']+3 and stats['MDEF']==proof['base']['MDEF']+1
            combat=dev(page,"const action=AstraeonCombat.compile('warrior','attack');const input=AstraeonCombatRuntime.buildInput({attackerLevel:1,attackerStats:d.getDerivedStats(),action,damageType:'physical'});const outgoing=AstraeonCombatResolution.resolveAttack(input,{rng:AstraeonCombatRuntime.sequenceRng([.5,.5,.5])}),incoming=AstraeonMonsterCombatRuntime.resolve({damage:12,player:{snapshot:d.snapshot,getDerivedStats:d.getDerivedStats},rng:AstraeonCombatRuntime.sequenceRng([])});return {outgoing,incoming}")
            assert combat['outgoing']['ok'] and combat['incoming']['ok'] and combat['outgoing']['input']['attacker']['stats']['physicalATK']==stats['physicalATK'];assert combat['incoming']['result']['input']['defender']['stats']['DEF']==stats['DEF'];passed('all five modifiers aggregate once through existing Stats and outgoing/incoming Combat',{'class':cls,'stats':stats})
            before=snap(page);rejected=dev(page,'return d.equip('+json.dumps(proof['ids']['weapon'])+',"shoes")');assert rejected['code']=='WRONG_EQUIPMENT_SLOT' and snap(page)==before;passed('wrong-slot request has no ownership resource serial or Stats mutation',{'class':cls})
            replacement=dev(page,"const created=d.createItemInstance('astral-blade'),before=d.getInventory(),capacity=d.getInventoryCapacityState(),result=d.equip(created.instance.instanceId,'mainHand');return {created,before,after:d.getInventory(),result,capacity,afterCapacity:d.getInventoryCapacityState(),old:d.getInstance("+json.dumps(proof['ids']['weapon'])+")}")
            assert replacement['result']['ok'] and replacement['old']['instanceId']==proof['ids']['weapon'] and replacement['before']==replacement['after'] and replacement['capacity']==replacement['afterCapacity'];assert replacement['result']['previousInstanceId']==proof['ids']['weapon'];passed('atomic occupied Main Hand replacement retains old instance and serial',{'class':cls})
            close(page);page.locator('[data-open="inventory"]').click();before=snap(page);cap=dev(page,'return d.getInventoryCapacityState()');page.locator('[data-unequip-slot="offHand"]').click();assert dev(page,'return d.getEquipped("offHand")') is None;assert snap(page)['itemInventory']==before['itemInventory'] and dev(page,'return d.getInventoryCapacityState()')==cap;page.locator('[data-equip-instance="'+proof['ids']['offHand']+'"][data-equip-slot="offHand"]').click();passed('ordinary Bag unequip and re-equip preserves canonical ownership and capacity',{'class':cls})
            death=dev(page,"const before=d.snapshot(),slots=d.getEquipmentSlots(),capacity=d.getInventoryCapacityState();d.setCurrentHP(0);d.setCurrentHP(before.maxHP);return {slots,afterSlots:d.getEquipmentSlots(),capacity,afterCapacity:d.getInventoryCapacityState(),beforeInventory:before.itemInventory,inventory:d.getInventory()}");assert death['slots']==death['afterSlots'] and death['capacity']==death['afterCapacity'] and death['beforeInventory']==death['inventory'];passed('five-slot resource death/recovery preserves equipment and ownership',{'class':cls})
            dev(page,'d.save()');saved=snap(page);equipped=dev(page,'return d.getEquipmentSlots()');page.reload(wait_until='load');page.wait_for_selector('#world');pause(page);assert dev(page,'return d.getEquipmentSlots()')==equipped and snap(page)['itemInventory']==saved['itemInventory'];assert dev(page,'return d.getDerivedStats()')==stats;passed('all five slot references serial capacity and combined Stats survive actual save/reload',{'class':cls})
            close(page);page.locator('[data-open="map"]').click();page.locator('[data-travel="2"]').click();page.wait_for_function('AstraeonQA.snapshot().save.zone===2');page.locator('[data-open="map"]').click();page.locator('[data-travel="0"]').click();page.wait_for_function('AstraeonQA.snapshot().save.zone===0');pause(page);assert dev(page,'return d.getEquipmentSlots()')==equipped and snap(page)['itemInventory']==saved['itemInventory'];passed('all five slots survive town/field travel without duplicated gear',{'class':cls})
            context.close()
        context,page=open_page('/tools/monster-box.html');page.wait_for_function('AstraeonMonsterBoxHarness.snapshot().inventory');page.locator('#add-many').click();page.locator('#prepare').click();prepared=json.loads(page.locator('#ticket').inner_text());assert prepared['authorizationOnly'] and 'boxes' not in prepared;page.locator('#commit').click();r=json.loads(page.locator('#result').inner_text());assert r['ok'] and r['openedCount']==3 and r['quantityAfter']==2 and len(r['instanceRewards'])==1;page.locator('#duplicate').click();assert json.loads(page.locator('#result').inner_text())['code']=='ALREADY_COMMITTED';passed('isolated harness deterministic bulk/roll evidence/serial/duplicate inspect correctly')
        page.locator('#count').fill('1');page.locator('#prepare').click();page.locator('#mutate').click();page.locator('#commit').click();assert json.loads(page.locator('#result').inner_text())['code']=='STALE_PACKAGE';page.locator('#rolls').fill('.8');page.locator('#single').click();assert json.loads(page.locator('#result').inner_text())['ok'];page.locator('#prepare').click();page.locator('#save').click();before=page.evaluate('AstraeonMonsterBoxHarness.snapshot().inventory');page.locator('#reload').click();page.locator('#commit').click();assert json.loads(page.locator('#result').inner_text())['code']=='INVALID_PACKAGE';assert page.evaluate('AstraeonMonsterBoxHarness.snapshot().inventory')==before;assert page.evaluate('localStorage.getItem("astraeon-iso-v1")') is None;passed('isolated harness single/stale/reload keeps canonical ownership without playable storage');context.close()
        context,page=open_page('/tools/inventory.html');page.wait_for_function('AstraeonInventoryHarness.inspect().equipment');
        evidence=page.evaluate("()=>{const h=AstraeonInventoryHarness,ids={};for(const [slot,id] of Object.entries({weapon:'astral-blade',offHand:'offhand-proof',armor:'warden-plate',shoes:'shoes-proof',relic:'spirit-charm'})){ids[slot]=h.give(id).instance.instanceId;h.equip(ids[slot],slot)}const full=h.inspect(),saved=h.snapshot();const legacy={...saved,equippedItems:{weapon:ids.weapon,armor:ids.armor,relic:ids.relic}},migrated=h.normalize(legacy);let repeat=migrated;for(let n=0;n<20;n++)repeat=h.normalize(repeat);const conflict=h.normalize({...saved,equippedItems:{weapon:ids.weapon,mainHand:ids.relic,futureHead:ids.shoes}});return {ids,full,saved,migrated,repeat,conflict}}")
        assert evidence['full']['equipment']==evidence['ids'] and evidence['migrated']==evidence['repeat'];assert evidence['migrated']['itemInventory']==evidence['saved']['itemInventory'] and evidence['conflict']['itemInventory']==evidence['saved']['itemInventory'];assert evidence['conflict']['equippedItems']['weapon']==evidence['ids']['weapon'] and len(evidence['conflict']['itemHistory']['equipmentSlotNormalization'])==2;assert page.evaluate('localStorage.getItem("astraeon-iso-v1")') is None;passed('isolated five-slot developer tooling and twenty legacy/conflict normalization cycles retain ownership');context.close()
        context,page=open_page('/tools/inventory-capacity.html');page.wait_for_function('AstraeonCapacityHarness.snapshot().capacity');
        evidence=page.evaluate("()=>{const raw=AstraeonSave.normalize({name:'Reward slot browser',cls:0,itemInventory:AstraeonItemInventory.normalize(),equippedItems:{}}),table={id:'box-proof-basic',entries:[{id:'shoes',itemId:'shoes-proof',rollMode:'guaranteed',minQuantity:1,maxQuantity:1}]},p=AstraeonPlayer.attach(raw,{boxTables:{getDefinition:()=>table}});p.addStack('monster-box-proof',1);const box=p.openMonsterBoxes('monster-box-proof');const drop={id:'slot-browser',entries:[{id:'offhand',itemId:'offhand-proof',rollMode:'guaranteed',chance:1,minQuantity:1,maxQuantity:1}]},loot=AstraeonMonsterLootRuntime.create({commit:(r,id)=>p.commitMonsterRewards(r,id)},{tables:{getDefinition:()=>drop},monsters:{getDefinition:()=>({id:'slot-fixture',dropTableId:drop.id,rewardProfileId:'proof',metadata:{fixture:true}})}}),actor={hp:1};loot.register(actor,'slot-fixture');actor.hp=0;const claim=loot.prepareDeath(actor,p.getMonsterRewardContext(2),{next:()=>.5}),result=loot.commit(claim),before=p.getEquipmentSlots(),equipBox=p.equip(box.instanceRewards[0].instanceId,'shoes'),equipLoot=p.equip(result.instanceRewards[0].instanceId,'offHand'),duplicate=loot.commit(claim);const flexible={getDefinition:id=>id==='astral-blade'?{...AstraeonItemDefinitions.getDefinition(id),equipmentSlots:['weapon','offHand']}:AstraeonItemDefinitions.getDefinition(id)},q=AstraeonPlayer.attach(AstraeonSave.normalize({name:'Flexible browser',itemInventory:AstraeonItemInventory.normalize(),equippedItems:{}}),{itemCatalog:flexible}),id=q.createItemInstance('astral-blade').instance.instanceId;q.equip(id,'weapon');const rejected=q.equip(id,'offHand');return {box,result,before,equipBox,equipLoot,duplicate,slots:p.getEquipmentSlots(),rejected,flexibleSlots:q.getEquipmentSlots()}}")
        assert evidence['box']['ok'] and evidence['result']['ok'] and all(x is None for x in evidence['before'].values());assert evidence['equipBox']['ok'] and evidence['equipLoot']['ok'] and evidence['duplicate']['code']=='ALREADY_COMMITTED';assert evidence['rejected']['code']=='ALREADY_EQUIPPED' and list(evidence['flexibleSlots'].values()).count(evidence['flexibleSlots']['weapon'])==1;passed('controlled Shoes Box and Off Hand Loot use canonical instances; multi-slot reference rejects');context.close()
        context,page=open_page('/');page.wait_for_selector('#create');page.locator('#newname').fill('Normal Box boot');page.locator('#create').click();page.wait_for_selector('#world');assert page.evaluate('typeof AstraeonMonsterBoxDev')=='undefined';assert page.evaluate('typeof AstraeonMonsterBoxHarness')=='undefined';assert page.evaluate('typeof AstraeonProgressionDev')=='undefined';page.locator('[data-open="inventory"]').click();assert page.locator('[data-equipment-slot]').count()==5;assert page.locator('[data-equip-slot="offHand"]').count()==0 and page.locator('[data-equip-slot="shoes"]').count()==0;assert page.evaluate('typeof AstraeonInventoryHarness')=='undefined';assert page.locator('[data-item="monster-box-proof"]').count()==0;passed('normal URL boots without Box mutation globals or unowned Box controls');context.close();browser.close()
    assert not errors and not http_errors,(errors,http_errors);report['result']='passed'
except Exception as error:report.update(result='failed',failure=str(error));raise
finally:
    report.update(checks=checks,runtimeErrors=errors,httpErrors=http_errors,liveTargetingObservations=timing);(args.output/'report.json').write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8')
print('PASS',len(checks),'Equipment Slot Closure browser groups',flush=True)
