const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),child=require('node:child_process');
global.window={};
for(const n of ['input','skill-nodes','combat','progression-config','progression','stats','skill-definitions','skill-tree','action-loadout','skill-runtime','action-runtime','character-state','item-definitions','item-inventory','inventory-capacity','item-equipment','item-state','action-item-config','item-effects','action-item','action-item-runtime','drop-tables','monster-definitions','loot-resolution','monster-rewards','monster-loot-runtime','box-content-tables','monster-box','monster-box-runtime','player-state','save-state','combat-resolution-config','combat-resolution','combat-runtime','enemy-combat','monster-lifecycle-definitions','monster-lifecycle','monster-combat-runtime','exploration'])require('../'+n+'.js');
const D=window.AstraeonItemDefinitions,I=window.AstraeonItemInventory,C=window.AstraeonInventoryCapacity,S=window.AstraeonSave,B=window.AstraeonMonsterBox,BOX='monster-box-proof';
const policy=(slotLimit=10,weightLimit=10)=>({mode:'bounded',slotLimit,weightLimit,overLimitPolicy:'no-worse',metadata:{fixture:true}});
const reward=(itemId,quantity=1)=>({itemId,quantity});
const catalog=(weights={},changes={})=>({getDefinition:id=>{const d=D.getDefinition(id);return d?D.freeze({...d,weight:weights[id]??d.weight,...changes[id]}):null}});
function fixture({stacks={},instances=[],weights={},changes={},capacity=policy(),table,rolls=[.4],extra={}}={}){
 const cat=catalog(weights,changes);let inventory=I.normalize({stacks},cat);for(const id of instances){const r=I.createInstance(inventory,id,{},cat);assert(r.ok);inventory=r.inventory}
 const state=S.normalize({name:'Capacity disposable',cls:0,legacySkillControls:false,itemInventory:inventory,equippedItems:{},equipment:{weapon:'None',armor:'None',relic:'None'},...extra});
 let active=capacity,draws=0,index=0;
 const player=window.AstraeonPlayer.attach(state,{itemCatalog:cat,getCapacityPolicy:()=>active,getBoxRng:()=>({next:()=>{draws++;return rolls[index++]}}),boxTables:table?{getDefinition:()=>table}:undefined});
 return {state,player,cat,setPolicy:p=>active=p,draws:()=>draws,snapshot:()=>S.snapshot(state),capacity:()=>player.getInventoryCapacityState(),open:n=>player.openMonsterBoxes(BOX,n)};
}
function unchanged(f,operation,code){const before=f.snapshot(),inventory=f.player.getInventory(),revision=f.player.getInventoryRevision(),r=operation();assert.equal(r.ok,false);if(code)assert.equal(r.code,code);assert.deepEqual(f.snapshot(),before);assert.equal(f.player.getInventory(),inventory);assert.equal(f.player.getInventoryRevision(),revision);return r}
const guaranteed=(itemId,quantity=1)=>({id:'box-proof-basic',entries:[{id:'reward',itemId,rollMode:'guaranteed',minQuantity:quantity,maxQuantity:quantity}]});
const exact=(f,rewards=[],stackDebits=[])=>f.player.canAcceptItemPackage({itemRewards:rewards,stackDebits});
test('valid immutable provisional policy and isolated technical unlimited mode',()=>{assert(C.validatePolicy(C.defaultPolicy).ok);assert(Object.isFrozen(C.defaultPolicy.metadata));const unlimited={mode:'unlimited',slotLimit:null,weightLimit:null,overLimitPolicy:'no-worse'};assert(C.validatePolicy(unlimited).ok);assert.equal(C.snapshot(I.normalize(),{policy:unlimited}).freeSlots,null)});
for(const key of ['slotLimit','weightLimit'])for(const value of [-1,NaN,Infinity,-Infinity,'1',null,Number.MAX_VALUE,Number.MAX_SAFE_INTEGER+1])test(`invalid ${key} ${String(value)} rejects`,()=>assert.equal(C.validatePolicy({...policy(),[key]:value}).code,'INVALID_CAPACITY_POLICY'));
for(const value of [.1,1.5])test('fractional slots reject '+value,()=>assert.equal(C.validatePolicy(policy(value)).ok,false));
test('positive subprecision weight cannot silently become authored zero',()=>{for(const value of [1e-12,Number.MIN_VALUE]){assert.equal(C.validatePolicy(policy(10,value)).code,'INVALID_CAPACITY_POLICY');const cat={getDefinition:id=>({...D.getDefinition(id),weight:value})};assert.equal(C.snapshot(I.normalize({stacks:{herb:1}}),{catalog:cat}).code,'INVALID_WEIGHT')}});
for(const value of [{fn:()=>1},{date:new Date()},{number:Infinity}])test('malformed authored policy metadata '+String(value),()=>assert.equal(C.validatePolicy({...policy(),metadata:value}).ok,false));
test('cyclic policy metadata rejects without throwing',()=>{const p=policy();p.metadata.self=p;assert.equal(C.validatePolicy(p).ok,false)});
test('throwing non-JSON policy metadata rejects with structured failure',()=>{const metadata={};Object.defineProperty(metadata,'invalid',{enumerable:true,get(){throw Error('invalid authored data')}});assert.equal(C.validatePolicy({...policy(),metadata}).code,'INVALID_CAPACITY_POLICY')});
for(const p of [null,{},[],{...policy(),mode:'unknown'},{...policy(),overLimitPolicy:'truncate'},{...policy(),slotLimit:undefined},{...policy(),weightLimit:undefined},{...policy(),inventory:[]}])test('unsupported incomplete policy rejects '+JSON.stringify(p),()=>assert.equal(C.validatePolicy(p).ok,false));
test('policy and snapshot deep immutable copies never freeze caller data',()=>{const p=policy(),inv=I.normalize({stacks:{herb:2}}),before=JSON.stringify(inv),r=C.snapshot(inv,{policy:p});assert(Object.isFrozen(r)&&Object.isFrozen(r.policy.metadata));assert(!Object.isFrozen(p));p.slotLimit=0;assert.equal(r.slotLimit,10);assert.equal(JSON.stringify(inv),before)});
test('empty canonical ownership uses zero slots and weight',()=>{const f=fixture();assert.equal(f.capacity().occupiedSlots,0);assert.equal(f.capacity().totalWeight,0)});
test('positive canonical stack uses one slot regardless of quantity',()=>{const f=fixture({stacks:{herb:1}});assert.equal(f.capacity().stackSlots,1);assert(f.player.addStack('herb',200).ok);assert.equal(f.capacity().occupiedSlots,1)});
test('second definition adds one logical stack slot',()=>{const f=fixture({stacks:{herb:2}});assert(f.player.addStack('ore',1).ok);assert.equal(f.capacity().stackSlots,2)});
test('zero and unknown quarantined stacks have no phantom occupancy',()=>{const inv=I.normalize({stacks:{herb:0,missing:10}}),r=C.snapshot(inv);assert.equal(r.occupiedSlots,0);assert(inv.history.stacks.missing)});
test('invalid noncanonical ownership rejects rather than drops items',()=>assert.equal(C.snapshot({stacks:{missing:1},instances:{},nextItemSerial:1,history:{}}).code,'INVALID_INVENTORY'));
for(const count of [1,2,3])test('each independent instance occupies one slot '+count,()=>{const f=fixture({instances:Array(count).fill('astral-blade')});assert.equal(f.capacity().instanceSlots,count);assert.equal(f.capacity().occupiedSlots,count)});
test('equipped instance counts exactly once; equip and unequip zero delta',()=>{const f=fixture({instances:['astral-blade'],weights:{'astral-blade':2}}),before=f.capacity();assert(f.player.equip('item-1','weapon').ok);assert.deepEqual(f.capacity(),before);assert(f.player.unequip('weapon').ok);assert.deepEqual(f.capacity(),before)});
test('stack weights sum quantity times authored units with stable fractional boundary',()=>{const f=fixture({stacks:{herb:3,ore:2},weights:{herb:.1,ore:.125}});assert.equal(f.capacity().weightUnits,550);assert.equal(f.capacity().totalWeight,.55);assert.deepEqual(f.player.getCarriedWeight(),{ok:true,weight:.55});assert.equal(I.carriedWeight(f.player.getInventory(),f.cat).weight,.55)});
test('mixed equipment stacks and zero weight Box counted independently',()=>{const f=fixture({stacks:{herb:3,[BOX]:50},instances:['astral-blade','astral-blade'],weights:{herb:.1,'astral-blade':2}});assert.equal(f.capacity().occupiedSlots,4);assert.equal(f.capacity().totalWeight,4.3)});
for(const value of [-1,NaN,Infinity,-Infinity,'1',undefined,.0001,Number.MAX_VALUE,1n,Symbol('weight')])test('invalid authored weight '+String(value)+' rejects safely',()=>{const cat={getDefinition:id=>({...D.getDefinition(id),weight:value})};assert.equal(C.snapshot(I.normalize({stacks:{herb:1}}),{catalog:cat}).code,'INVALID_WEIGHT');const f=fixture({changes:{herb:{weight:value}}});unchanged(f,()=>f.player.addStack('herb',1),'INVALID_WEIGHT')});
test('quantity multiplication overflow is finite structured failure',()=>{const inv=I.normalize({stacks:{herb:Number.MAX_SAFE_INTEGER}});assert.equal(C.snapshot(inv,{catalog:catalog({herb:1})}).code,'WEIGHT_OVERFLOW')});
test('weight accumulation overflow rejects before publication',()=>{const inv=I.normalize({stacks:{herb:5000000000000,ore:5000000000000}});assert.equal(C.snapshot(inv,{catalog:catalog({herb:1,ore:1})}).code,'WEIGHT_OVERFLOW')});
test('candidate is immutable nonmutating with inspectable net delta',()=>{const f=fixture({stacks:{herb:2},weights:{herb:.1,ore:.2}}),before=f.snapshot(),r=exact(f,[reward('ore',2)]);assert(r.ok);assert.deepEqual(r.delta,{slots:1,weight:.4});assert(Object.isFrozen(r.after));assert.deepEqual(f.snapshot(),before)});
for(const [name,capacity,weights,id,count,code] of [
 ['exact slot',policy(1),{},'herb',1,null],['one over slot',policy(0),{},'herb',1,'SLOT_LIMIT_EXCEEDED'],
 ['exact fractional weight',policy(3,.3),{herb:.1},'herb',3,null],['one milliweight over',policy(3,.299),{herb:.1},'herb',3,'WEIGHT_LIMIT_EXCEEDED']
])test(name+' candidate and canonical grant agree',()=>{const f=fixture({capacity,weights}),r=exact(f,[reward(id,count)]);if(code){assert.equal(r.code,code);unchanged(f,()=>f.player.addStack(id,count),code)}else{assert(r.ok);assert(f.player.addStack(id,count).ok);assert.deepEqual(f.capacity(),r.after)}});
test('existing zero-weight stack can merge with no free slots',()=>{const f=fixture({stacks:{herb:1},capacity:policy(1)});assert(f.player.addStack('herb',1).ok);unchanged(f,()=>f.player.addStack('ore',1),'SLOT_LIMIT_EXCEEDED')});
test('maxStack failure distinct from capacity with free slots',()=>{const f=fixture({stacks:{herb:2},changes:{herb:{maxStack:2}}});assert.equal(exact(f,[reward('herb')]).code,'STACK_OVERFLOW');unchanged(f,()=>f.player.addStack('herb',1),'STACK_OVERFLOW')});
test('canAddStack includes authoritative capacity without mutation',()=>{const f=fixture({capacity:policy(0)});assert.equal(f.player.canAddStack('herb',1).code,'SLOT_LIMIT_EXCEEDED');assert.equal(f.capacity().occupiedSlots,0)});
test('last source debit frees slot for new output',()=>{const f=fixture({stacks:{[BOX]:1},capacity:policy(1)}),r=exact(f,[reward('potion')],[reward(BOX)]);assert(r.ok);assert.equal(r.after.occupiedSlots,1);assert.equal(r.delta.slots,0)});
test('partial source debit retains slot and can reject output',()=>{const f=fixture({stacks:{[BOX]:2},capacity:policy(1)});assert.equal(exact(f,[reward('potion')],[reward(BOX)]).code,'SLOT_LIMIT_EXCEEDED')});
test('multiple debits aggregate and impossible debit rejects',()=>{const f=fixture({stacks:{herb:2}});assert(exact(f,[reward('herb',2)],[reward('herb'),reward('herb')]).ok);assert.equal(exact(f,[],[reward('herb',3)]).code,'INSUFFICIENT_ITEMS')});
test('instance removal simulation respects equipped and duplicate IDs',()=>{const f=fixture({instances:['astral-blade'],weights:{'astral-blade':2}});assert.equal(f.player.canAcceptItemPackage({instanceDebits:['item-1']}).after.totalWeight,0);assert.equal(f.player.canAcceptItemPackage({instanceDebits:['item-1','item-1']}).code,'UNKNOWN_INSTANCE');f.player.equip('item-1','weapon');assert.equal(f.player.canAcceptItemPackage({instanceDebits:['item-1']}).code,'ITEM_EQUIPPED')});
for(const packageData of [null,[],{itemRewards:null},{itemRewards:[reward('missing')]},{itemRewards:[reward('herb',0)]},{maximumInstanceUnits:0},{itemRewards:[reward('herb',1.5)]},{stackDebits:[reward('herb',-1)]}])test('invalid package rejects '+JSON.stringify(packageData),()=>assert.equal(fixture().player.canAcceptItemPackage(packageData).ok,false));
for(const rewards of [[reward('herb',2)],[reward('astral-blade',2)],[reward('herb'),reward('astral-blade')]])test('exact package simulation matches committed stack instance mixed ownership '+JSON.stringify(rewards),()=>{const f=fixture(),r=exact(f,rewards),serial=f.player.getInventory().nextItemSerial;assert(r.ok);assert(f.player.grantItemPackage(rewards).ok);assert.deepEqual(f.capacity(),r.after);assert.equal(f.player.getInventory().nextItemSerial-serial,rewards.filter(x=>!D.getDefinition(x.itemId).stackable).reduce((s,x)=>s+x.quantity,0))});
test('mixed package capacity failure publishes no early material/gear/serial',()=>{const f=fixture({capacity:policy(1)});unchanged(f,()=>f.player.grantItemPackage([reward('herb'),reward('astral-blade')]),'SLOT_LIMIT_EXCEEDED')});
test('rejected instance package does not call canonical instance allocator',()=>{const f=fixture({capacity:policy(0)});unchanged(f,()=>f.player.createItemInstance('astral-blade'),'SLOT_LIMIT_EXCEEDED');assert.equal(f.player.getInventory().nextItemSerial,1)});
for(const [name,stacks,weights,capacity,flags] of [
 ['over slots',{herb:1,ore:1},{},policy(1),[true,false]],['overweight',{herb:2},{herb:1},policy(10,1),[false,true]],['both',{herb:2,ore:1},{herb:1},policy(1,1),[true,true]]
])test(name+' returning ownership loads intact and reports over-limit',()=>{const f=fixture({stacks,weights,capacity}),r=f.capacity();assert(r.isOverLimit);assert.deepEqual([r.isSlotOverLimit,r.isWeightOverLimit],flags);assert.deepEqual(f.player.getInventory().stacks,stacks);assert.deepEqual(S.snapshot(f.state).itemInventory.stacks,stacks)});
test('over-limit equipment retained and zero-delta equip allowed',()=>{const f=fixture({instances:['astral-blade','warden-plate'],capacity:policy(0,0),weights:{'astral-blade':1}});assert(f.capacity().isOverLimit);assert(f.player.equip('item-1','weapon').ok);assert(f.player.unequip('weapon').ok);assert.equal(Object.keys(f.player.getInventory().instances).length,2)});
for(const id of ['herb','astral-blade'])test('over-limit worsening '+id+' rejects',()=>{const f=fixture({stacks:{herb:2},capacity:policy(0,1),weights:{herb:1,'astral-blade':1}});unchanged(f,()=>f.player.grantItemPackage([reward(id)]),'OVER_LIMIT_WORSENED')});
test('slot-over-limit zero-weight existing stack merge is no worse',()=>{const f=fixture({stacks:{herb:1},capacity:policy(0)});assert(f.player.addStack('herb',1).ok);unchanged(f,()=>f.player.addStack('ore',1),'OVER_LIMIT_WORSENED')});
test('two exceeded dimensions must independently be no worse',()=>{const f=fixture({stacks:{herb:2,ore:1},weights:{herb:1,ore:2},capacity:policy(1,1)});const r=exact(f,[reward('ore',2)],[reward('herb',2)]);assert.equal(r.code,'OVER_LIMIT_WORSENED');assert.equal(r.dimension,'weight')});
test('overweight Action Item consumption remains authoritative and frees last slot',()=>{const f=fixture({stacks:{potion:1},weights:{potion:2},capacity:policy(0,1)});f.player.setCurrentHP(1);assert(f.player.useConsumable('potion',{now:0,intent:'inventory'}).ok);assert.equal(f.capacity().occupiedSlots,0);assert.equal(f.capacity().totalWeight,0);assert(f.state.currentHP>1)});
test('over-limit state attaches no movement combat Stats or SP penalty',()=>{const f=fixture({stacks:{herb:100},weights:{herb:1}}),before=f.player.getDerivedStats(),resources=f.player.snapshot();f.setPolicy(policy(0,0));assert(f.capacity().isOverLimit);assert.deepEqual(f.player.getDerivedStats(),before);assert.deepEqual(f.player.snapshot(),resources)});
for(const [name,capacity,weights] of [['slots',policy(1),{}],['weight',policy(10,.5),{herb:1,'astral-blade':1}]])test('Box '+name+' envelope blocks before RNG source grant and allocation',()=>{const f=fixture({stacks:{[BOX]:2},capacity,weights}),before=f.snapshot();for(let i=0;i<3;i++){assert.equal(f.player.prepareMonsterBoxOpen(BOX).ok,false);unchanged(f,()=>f.open(1));assert.equal(f.draws(),0);assert.deepEqual(f.snapshot(),before)}assert.equal(f.player.getMonsterBoxRuntime().pending,null)});
test('guaranteed final Box frees source slot and exact outcome matches envelope',()=>{const f=fixture({stacks:{[BOX]:1},capacity:policy(1),table:guaranteed('potion')});assert(f.player.prepareMonsterBoxOpen(BOX).ok);assert(f.open(1).ok);assert.equal(f.player.getQuantity(BOX),0);assert.equal(f.capacity().occupiedSlots,1);assert.equal(f.player.getQuantity('potion'),1)});
test('partial Box stack needs both source and new reward slot',()=>{const f=fixture({stacks:{[BOX]:2},capacity:policy(1),table:guaranteed('potion')});unchanged(f,()=>f.open(1),'SLOT_LIMIT_EXCEEDED');assert.equal(f.draws(),0)});
test('full bulk envelope rejected atomically before entropy',()=>{const f=fixture({stacks:{[BOX]:3},capacity:policy(2),table:guaranteed('astral-blade')});unchanged(f,()=>f.open(3),'SLOT_LIMIT_EXCEEDED');assert.equal(f.draws(),0)});
test('capacity policy change after prepare rechecks envelope before entropy',()=>{const f=fixture({stacks:{[BOX]:2}}),t=f.player.prepareMonsterBoxOpen(BOX);assert(t.ok);f.setPolicy(policy(1));unchanged(f,()=>f.player.commitMonsterBoxOpen(t),'SLOT_LIMIT_EXCEEDED');assert.equal(f.draws(),0)});
for(const [name,rolls,itemId,quantity,weight] of [['material',[0,0],'herb',2,.2],['consumable',[.4],'potion',1,.3],['equipment',[.8],'astral-blade',1,.4]])test('accepted Box '+name+' exact ownership fits envelope and serial',()=>{const f=fixture({stacks:{[BOX]:1},weights:{herb:.1,potion:.3,'astral-blade':.4},capacity:policy(3,1),rolls}),r=f.open(1);assert(r.ok);assert.equal(f.capacity().totalWeight,weight);assert.equal(f.capacity().occupiedSlots,1);if(itemId==='astral-blade'){assert.equal(r.instanceRewards.length,1);assert.equal(r.serialAfter-r.serialBefore,1);assert.equal(f.player.getEquipped('weapon'),null)}else{assert.equal(f.player.getQuantity(itemId),quantity);assert.equal(r.serialAfter,r.serialBefore)}});
test('Box reward existing stack merges and source removal shrinks slots',()=>{const f=fixture({stacks:{potion:1,[BOX]:1},table:guaranteed('potion'),capacity:policy(2)});assert(f.open(1).ok);assert.equal(f.capacity().occupiedSlots,1);assert.equal(f.player.getQuantity('potion'),2)});
test('bulk mixed Box capacity envelope and exact publication deterministic',()=>{const f=fixture({stacks:{[BOX]:3},weights:{herb:.1,potion:.3,'astral-blade':.4},capacity:policy(5,3),rolls:[0,0,.4,.8]}),r=f.open(3);assert(r.ok);assert.equal(r.openedCount,3);assert.equal(f.capacity().occupiedSlots,3);assert.equal(f.capacity().totalWeight,.9);assert.equal(r.serialAfter-r.serialBefore,1)});
test('mutually exclusive equipment envelope uses max instance count, conservative weight',()=>{const table={id:'box-proof-basic',entries:['astral-blade','warden-plate'].map((itemId,i)=>({id:String(i),itemId,rollMode:'weighted',weight:1,minQuantity:1,maxQuantity:1}))},f=fixture({stacks:{[BOX]:1},table,capacity:policy(1),rolls:[.8]});assert(f.open(1).ok);assert.equal(f.capacity().instanceSlots,1)});
function lootFixture(f,definition='proof-multi',rolls=[0,0,0,0],contracts=[]){let draws=0,index=0;const actor={hp:1},loot=window.AstraeonMonsterLootRuntime.create({commit:(r,p)=>f.player.commitMonsterRewards(r,p,contracts)});assert(loot.register(actor,definition).ok);actor.hp=0;const claim=loot.prepareDeath(actor,f.player.getMonsterRewardContext(2),{next:()=>{draws++;return rolls[index++]}});assert(claim.ok);return {actor,loot,claim,draws:()=>draws}}
for(const [name,capacity,weights] of [['slot',policy(1),{}],['weight',policy(10,.1),{herb:1}]])test('Monster Loot '+name+' failure retains exact claim no partial currency gear or reroll',()=>{const f=fixture({capacity,weights}),l=lootFixture(f),before=f.snapshot(),draws=l.draws();assert.equal(l.loot.commit(l.claim).ok,false);assert.equal(l.loot.commit(l.claim).ok,false);assert.deepEqual(f.snapshot(),before);assert.equal(l.draws(),draws);assert.equal(l.loot.prepareDeath(l.actor,{},{}),l.claim);f.setPolicy(policy());assert(l.loot.commit(l.claim).ok);assert.equal(l.loot.commit(l.claim).code,'ALREADY_COMMITTED');assert.equal(l.draws(),draws)});
test('blocked production kill progression and quest remain exactly once after same claim retry',()=>{const f=fixture({capacity:policy(0),extra:{quest:{id:0,progress:0}}}),l=lootFixture(f,'leafmane-fox',[],[{zone:2,target:1,reward:10,xp:20,title:'fixture'}]);unchanged(f,()=>l.loot.commit(l.claim));assert.equal(f.state.kills,0);assert.equal(f.state.quest.progress,0);f.setPolicy(policy());const r=l.loot.commit(l.claim);assert(r.ok);assert.equal(f.state.kills,1);assert.equal(r.questCredit,1);assert(r.baseExp>0&&r.jobExp>0&&r.currencyGranted>0);const before=f.snapshot();assert.equal(l.loot.commit(l.claim).code,'ALREADY_COMMITTED');assert.deepEqual(f.snapshot(),before)});
test('Monster Loot Box is unopened and no Box RNG consumed',()=>{const f=fixture(),l=lootFixture(f,'proof-monster-box',[]);assert(l.loot.commit(l.claim).ok);assert.equal(f.player.getQuantity(BOX),1);assert.equal(f.draws(),0);assert.equal(f.capacity().stackSlots,1)});
test('Lifecycle blocked reward never repeats handoff; new life unchanged',()=>{const f=fixture({capacity:policy(0)}),loot=window.AstraeonMonsterLootRuntime.create({commit:(r,p)=>f.player.commitMonsterRewards(r,p)}),life=window.AstraeonMonsterLifecycle.create({loot,rng:{next:()=>.5}}),actor={x:0,y:0,hp:20,maxHp:20};assert(life.register(actor,'lifecycle-normal-a',{id:'capacity-spawn',home:{x:0,y:0}}).ok);actor.hp=0;assert.equal(life.notifyDeath(actor,0).reward.ok,false);assert(life.notifyDeath(actor,0).duplicate);assert.equal(loot.snapshot().events.length,0);life.update(actor,{now:1,active:true,target:null});f.setPolicy(policy());assert(life.update(actor,{now:4,active:true,target:null,canRespawn:true}).respawnEvent);actor.hp=0;assert(life.notifyDeath(actor,5).reward.ok);assert.equal(loot.snapshot().events.length,1)});
test('fitting merchant charges exact price and accepted ownership',()=>{const f=fixture({capacity:policy(1),weights:{herb:.5}});assert(f.player.buy('herb',2).ok);assert.equal(f.state.gold,40);assert.equal(f.capacity().totalWeight,1)});
for(const [name,capacity,weights] of [['slot',policy(0),{}],['weight',policy(1,.5),{herb:1}]])test('merchant '+name+' rejection charges zero and grants nothing',()=>{const f=fixture({capacity,weights});unchanged(f,()=>f.player.buy('herb',1));assert.equal(f.state.gold,50)});
test('selling over-limit ownership reduces weight and grants original currency',()=>{const f=fixture({stacks:{herb:2},weights:{herb:1},capacity:policy(0,0)});assert(f.player.sell('herb',1).ok);assert.equal(f.state.gold,52);assert.equal(f.capacity().totalWeight,1);assert(f.player.sell('herb',1).ok);assert.equal(f.capacity().occupiedSlots,0)});
test('craft net input slots can free enough room for output',()=>{const f=fixture({stacks:{herb:2,shard:1},capacity:policy(2),weights:{herb:.1,shard:.1,potion:.3}});assert(f.player.craft('potion').ok);assert.equal(f.capacity().occupiedSlots,1);assert.equal(f.capacity().totalWeight,.3);assert.equal(f.state.profXP,0)});
for(const [name,capacity,weights] of [['slot',policy(2),{}],['weight',policy(10,.3),{herb:.1,shard:.1,potion:1}]])test('craft '+name+' output failure preserves inputs gold and serial',()=>{const f=fixture({stacks:{herb:3,shard:2},capacity,weights});unchanged(f,()=>f.player.craft('potion'))});
test('craft equipment input debit and serial agrees with capacity',()=>{const f=fixture({stacks:{ore:4,shard:2},capacity:policy(2),weights:{ore:.1,shard:.1,'astral-blade':.6}});assert(f.player.craft('blade').ok);assert.equal(f.capacity().occupiedSlots,1);assert.equal(f.capacity().totalWeight,.6);assert.equal(f.player.getInventory().nextItemSerial,2)});
test('capacity blocked exploration preserves pickup claim and gold',()=>{const f=fixture({capacity:policy(0)}),entry={id:'capacity-chest',kind:'chest',name:'fixture'},before=f.snapshot();assert.equal(window.AstraeonExploration.claim(entry,f.state,{addItems:f.player.reward}).ok,false);assert.deepEqual(f.snapshot(),before);assert.equal(f.state.worldClaims[entry.id],undefined)});
test('instance delete improves capacity without serial rewind',()=>{const f=fixture({instances:['astral-blade'],weights:{'astral-blade':2},capacity:policy(0,0)});assert(f.player.deleteItemInstance('item-1').ok);assert.equal(f.capacity().totalWeight,0);assert.equal(f.player.getInventory().nextItemSerial,2)});
test('canonical mirror synchronized after exact reward and last-stack removal',()=>{const f=fixture();f.player.grantItemPackage([reward('potion',2)]);assert.equal(f.state.inventory.potion,2);f.player.removeStack('potion',2);assert.equal(f.state.inventory.potion,0);assert.equal(f.capacity().occupiedSlots,0)});
test('box-derived consumable and equipment reach existing Action Item Stats Combat',()=>{const f=fixture({stacks:{[BOX]:2},rolls:[.4,.8]}),base=f.player.getDerivedStats();assert(f.open(1).ok);f.player.setCurrentHP(1);assert(f.player.useConsumable('potion',{now:0,intent:'inventory'}).ok);const r=f.open(1);assert(r.ok);assert(f.player.equip(r.instanceRewards[0].instanceId,'weapon').ok);assert.equal(f.player.getDerivedStats().physicalATK,base.physicalATK+6);const input=window.AstraeonCombatRuntime.buildInput({attackerLevel:1,attackerStats:f.player.getDerivedStats(),action:window.AstraeonCombat.compile('warrior','attack'),damageType:'physical'});assert(window.AstraeonCombatResolution.resolveAttack(input,{rng:{next:()=>.5}}).ok)});
test('twenty save load normalize cycles preserve ownership capacity serial and overweight',()=>{const f=fixture({stacks:{herb:3,[BOX]:2},instances:['astral-blade'],weights:{herb:.1,'astral-blade':2},capacity:policy(1,1)});f.player.equip('item-1','weapon');const before=f.snapshot(),capacity=f.capacity();let saved=before;for(let i=0;i<20;i++){saved=S.snapshot(S.normalize(JSON.parse(JSON.stringify(saved))));assert.deepEqual(saved,before);const p=window.AstraeonPlayer.attach(S.normalize(saved),{itemCatalog:f.cat,getCapacityPolicy:()=>policy(1,1)});assert.deepEqual(p.getInventoryCapacityState(),capacity)}assert.equal(saved.saveVersion,5);for(const key of ['currentWeight','occupiedSlots','isOverweight','slotLimit','weightLimit'])assert.equal(saved[key],undefined)});
test('save reload after Box preserves contents and derived capacity, invalidates old ticket',()=>{const f=fixture({stacks:{[BOX]:3},rolls:[.8]}),ticket=f.player.prepareMonsterBoxOpen(BOX);assert(f.open(1).ok);const saved=f.snapshot(),p=window.AstraeonPlayer.attach(S.normalize(saved));assert.deepEqual(p.getInventoryCapacityState(),C.snapshot(saved.itemInventory));assert.equal(p.commitMonsterBoxOpen(ticket).code,'INVALID_PACKAGE');assert.equal(p.getQuantity(BOX),2)});
for(const version of [1,2,3,4,5])test('version '+version+' migration retains over-limit ownership',()=>{const state=S.normalize({name:'returning',saveVersion:version,inventory:{herb:2,blade:2},equipment:{weapon:'Astral Blade',armor:'None',relic:'None'}}),p=window.AstraeonPlayer.attach(state,{getCapacityPolicy:()=>policy(0,0)});assert.equal(state.saveVersion,5);assert.equal(p.getQuantity('herb'),2);assert.equal(Object.keys(p.getInventory().instances).length,2);assert(p.getInventoryCapacityState().isOverLimit);assert.equal(p.getEquipped('weapon'),'item-1')});
test('future guard rejects before capacity or migration and preserves supplied data',()=>{const raw={name:'future',saveVersion:6,itemInventory:{stacks:{herb:1}}},before=structuredClone(raw);assert.throws(()=>S.normalize(raw),S.UnsupportedSaveError);assert.deepEqual(raw,before)});
test('death respawn travel invalidation preserves canonical capacity without refund',()=>{const f=fixture({stacks:{[BOX]:2},rolls:[.4]});assert(f.open(1).ok);for(const boundary of ['death','respawn','town','field']){const before=f.snapshot(),capacity=f.capacity(),t=f.player.prepareMonsterBoxOpen(BOX);f.player.invalidatePreparedActions();assert.equal(f.player.commitMonsterBoxOpen(t).code,'STALE_PACKAGE');assert.deepEqual(f.snapshot(),before);assert.deepEqual(f.capacity(),capacity)}});
test('boot and all item harnesses load required authority before Item State',()=>{for(const file of ['boot.js','tools/inventory.html','tools/monster-box.html','tools/monster-loot.html','tools/monster-lifecycle.html','tools/progression.html']){const s=fs.readFileSync(require.resolve('../'+file),'utf8');assert(s.indexOf('inventory-capacity.js')>s.indexOf('item-inventory.js'));assert(s.indexOf('inventory-capacity.js')<s.indexOf('item-state.js'))}const game=fs.readFileSync(require.resolve('../game.js'),'utf8');assert(game.indexOf('window.AstraeonInventoryCapacityDev=')>game.indexOf("if(new URLSearchParams(location.search).get('dev')==='1'){"));assert(!game.includes('bypassCapacity'));assert(fs.readFileSync(require.resolve('../sw.js'),'utf8').includes('inventory-capacity.js?v=93'))});
test('no protected visual AI Action Combat save or authored balance files changed',()=>{const parent='1e32ce4e17ae516b504a65e7a0a03db634ac62d4';for(const file of ['item-definitions.js','monster-box.js','monster-box-runtime.js','box-content-tables.js','monster-loot-runtime.js','monster-lifecycle.js','monster-lifecycle-definitions.js','monster-combat-runtime.js','combat-resolution.js','action-item.js','action-item-runtime.js','save-state.js','style.css'])assert.equal(fs.readFileSync(require.resolve('../'+file),'utf8').replace(/\r\n/g,'\n'),child.execFileSync('git',['show',parent+':'+file]).toString().replace(/\r\n/g,'\n'));assert(!child.execFileSync('git',['diff','--name-only',parent]).toString().split('\n').some(p=>/^(assets|world|authoring|RO3 Ref)\//.test(p)))});
test('all authored current weights stay explicitly zero and validate',()=>{for(const d of Object.values(D.definitions)){assert.equal(d.weight,0);assert.equal(d.metadata.weight,'unconfigured');const inventory=d.stackable?I.addStack(I.normalize(),d.id,1).inventory:I.createInstance(I.normalize(),d.id).inventory;assert(C.snapshot(inventory).ok)}});
test('conservative Box weight envelope rejects even if selected small outcome would fit',()=>{const f=fixture({stacks:{[BOX]:1},weights:{herb:.1,potion:.3,'astral-blade':.4},capacity:policy(3,.999),rolls:[.4]});unchanged(f,()=>f.open(1),'WEIGHT_LIMIT_EXCEEDED');assert.equal(f.draws(),0);assert.equal(f.player.getMonsterBoxRuntime().pending,null)});
test('positive test-only Box source weight debit permits overweight recovery before RNG',()=>{const f=fixture({stacks:{[BOX]:1},weights:{[BOX]:2,herb:.1,potion:.3,'astral-blade':.4},capacity:policy(3,1),rolls:[.8]});assert(f.capacity().isWeightOverLimit);assert(f.open(1).ok);assert.equal(f.capacity().totalWeight,.4);assert(!f.capacity().isOverLimit)});
test('null debit arrays and cyclic packages reject deterministically',()=>{const f=fixture();for(const key of ['stackDebits','instanceDebits'])assert.equal(f.player.canAcceptItemPackage({[key]:null}).code,'INVALID_PACKAGE');const cyclic={itemRewards:[]};cyclic.itemRewards.push(cyclic);assert.equal(f.player.canAcceptItemPackage(cyclic).code,'INVALID_PACKAGE')});
for(const id of ['constructor','__proto__',null,{}])test('unknown non-string or inherited instance identity rejects '+String(id),()=>assert.equal(fixture().player.canAcceptItemPackage({instanceDebits:[id]}).code,'UNKNOWN_INSTANCE'));
test('capacity policy provider exception rejects without publishing canonical mutation',()=>{const raw=S.normalize({name:'policy fault',itemInventory:I.normalize(),equippedItems:{}}),p=window.AstraeonPlayer.attach(raw,{getCapacityPolicy:()=>{throw Error('fixture')}}),before=S.snapshot(raw);assert.equal(p.addStack('herb',1).code,'INVALID_CAPACITY_POLICY');assert.deepEqual(S.snapshot(raw),before)});
test('stack-only package rejection keeps existing serial and independent progression unchanged',()=>{const f=fixture({capacity:policy(1)});unchanged(f,()=>f.player.reward({herb:1,ore:1}),'SLOT_LIMIT_EXCEEDED');assert.equal(f.player.getInventory().nextItemSerial,1)});
test('old per-life capacity rejected claim expires at new life without replay',()=>{const f=fixture({capacity:policy(0)}),l=lootFixture(f,'proof-equipment',[]);assert.equal(l.loot.commit(l.claim).ok,false);l.actor.hp=1;assert(l.loot.newLife(l.actor).ok);l.actor.hp=0;f.setPolicy(policy());unchanged(f,()=>l.loot.commit(l.claim),'STALE_CLAIM');const next=l.loot.prepareDeath(l.actor,f.player.getMonsterRewardContext(2),{next:()=>.5});assert.notEqual(next.deathId,l.claim.deathId);assert(l.loot.commit(next).ok);assert.equal(Object.keys(f.player.getInventory().instances).length,1)});
test('carried-weight helper fails closed when required capacity module unavailable',()=>{const saved=window.AstraeonInventoryCapacity;try{window.AstraeonInventoryCapacity=null;assert.equal(I.carriedWeight(I.normalize()).code,'CAPACITY_AUTHORITY_REQUIRED')}finally{window.AstraeonInventoryCapacity=saved}});
test('canAddStack retains its existing quantity field alongside capacity evidence',()=>{const f=fixture({stacks:{herb:2}}),r=f.player.canAddStack('herb',3);assert.equal(r.quantity,5);assert(r.capacity.ok);assert.equal(r.capacity.after.occupiedSlots,1)});
