"""Disposable capacity/weight proof, Box/Loot atomicity and real two-class smoke."""
import argparse,json,os,tempfile,time
from pathlib import Path
from playwright.sync_api import sync_playwright,TimeoutError as PlaywrightTimeout
parser=argparse.ArgumentParser();parser.add_argument('--url',default='http://127.0.0.1:8011');parser.add_argument('--browser',default=os.environ.get('ASTRAEON_BROWSER',r'C:\Program Files\Google\Chrome\Application\chrome.exe' if os.name=='nt' else '/usr/bin/chromium'));parser.add_argument('--output',type=Path,default=Path(tempfile.gettempdir())/'astraeon-inventory-capacity-browser');args=parser.parse_args();args.output.mkdir(parents=True,exist_ok=True)
BOX='monster-box-proof';checks,errors,http_errors,timing=[],[],[],[];report={}
def passed(name,evidence=None):checks.append({'name':name,'evidence':evidence});print('PASS',name,flush=True)
def qa(page):return page.evaluate('AstraeonQA.snapshot()')
def dev(page,code):return page.evaluate('()=>{const d=AstraeonProgressionDev,b=AstraeonMonsterBoxDev,l=AstraeonMonsterLifecycleDev;'+code+'}')
def snap(page):return dev(page,'return d.snapshot()')
def close(page):
    if qa(page)['windowName']:page.locator('#modal .close').click()
def pause(page):
    close(page);page.locator('[data-open="character"]').click()
def place(page,x,y):assert dev(page,f'return l.placePlayer({x},{y})')['ok']
def inspect(page,id):return dev(page,'return l.inspect('+json.dumps(id)+')')
def wait_attack_window(page,id):
    # A real incoming hit cancels anticipation. Observe recovery/cadence before
    # the original single cast; do not disable AI or alter Combat expectations.
    page.wait_for_function('''id=>{const q=AstraeonQA.snapshot(),e=q.enemies.find(e=>e.lifecycle.instanceId===id)?.lifecycle;return e&&q.incomingCombat.some(r=>r.attackId.startsWith(id+':'))&&!e.attackIntent&&e.attackReadyAt-q.time>1&&!q.action&&q.animation.state!=='hit'}''',arg=id,timeout=30000)
    timing.append({'event':'incoming-hit recovery window before learned cast','id':id,'state':inspect(page,id),'time':qa(page)['time']})
def point(page,x,y):
    s=qa(page);v,c=s['view'],s['camera'];rect=page.locator('#world').bounding_box()
    return (rect['x']+rect['width']/2+(x*v['basis']['xx']+y*v['basis']['yx']-c['x'])*v['zoom'],rect['y']+rect['height']*v['anchorY']+(x*v['basis']['xy']+y*v['basis']['yy']-c['y'])*v['zoom'])
def fight(page,id):
    deadline=time.monotonic()+90
    while inspect(page,id)['hp']>0:
        assert time.monotonic()<deadline,('bounded real encounter',inspect(page,id),qa(page)['navigation'])
        close(page);dev(page,'d.setCurrentHP(d.snapshot().maxHP);d.setCurrentSP(d.snapshot().maxSP)');actor=inspect(page,id);place(page,actor['position']['x'],actor['position']['y']-.7)
        x,y=point(page,actor['position']['x'],actor['position']['y']);page.mouse.click(x,y-16);button=page.locator('[data-action="attack"]').bounding_box();page.mouse.move(button['x']+button['width']/2,button['y']+button['height']/2);page.mouse.down()
        try:page.wait_for_function('id=>AstraeonMonsterLifecycleDev.inspect(id)?.hp===0',arg=id,timeout=8000)
        except PlaywrightTimeout:timing.append({'event':'bounded Basic Attack retry','id':id,'state':inspect(page,id)})
        finally:page.mouse.up()
try:
    with sync_playwright() as p:
        browser=p.chromium.launch(executable_path=args.browser,headless=True,args=['--no-sandbox','--enable-gpu']+(['--use-angle=d3d11'] if os.name=='nt' else ['--use-angle=swiftshader','--enable-unsafe-swiftshader']))
        def open_page(path='/?qa=1&dev=1'):
            context=browser.new_context(viewport={'width':1280,'height':800});page=context.new_page();page.set_default_timeout(180000)
            page.on('pageerror',lambda e:errors.append(str(e)));page.on('console',lambda m:errors.append(m.text) if m.type=='error' else None);page.on('response',lambda r:http_errors.append(f'{r.status} {r.url}') if r.status>=400 else None)
            page.goto(args.url.rstrip('/')+path,wait_until='load');return context,page
        for cls,skill in [('0','rising-edge'),('12','ember-bloom')]:
            context,page=open_page();page.wait_for_selector('#create');page.locator('#newname').fill('Box '+cls);page.locator('#newclass').select_option(cls);page.locator('#create').click();page.wait_for_selector('#world');pause(page);passed('normal character boot with canonical v5 inventory',{'class':cls})
            counted=dev(page,"const c=d.getInventoryCapacityState(),i=d.getInventory();return {c,expected:Object.keys(i.stacks).length+Object.keys(i.instances).length}")
            assert counted['c']['ok'] and counted['c']['occupiedSlots']==counted['expected'] and counted['c']['totalWeight']==0;passed('live canonical slots, zero/unconfigured weights and equipped ownership counted once',{'class':cls,'capacity':counted})
            evidence=dev(page,"const c=AstraeonInventoryCapacityDev,n=c.snapshot().occupiedSlots;const policy={mode:'bounded',slotLimit:n+1,weightLimit:1000,overLimitPolicy:'no-worse'};c.setTestPolicy(policy);const fit=d.createItemInstance('warden-plate'),before=d.snapshot(),fail=d.createItemInstance('warden-plate');return {fit,fail,before,after:d.snapshot(),capacity:c.snapshot()}")
            assert evidence['fit']['ok'] and evidence['fail']['code']=='SLOT_LIMIT_EXCEEDED' and evidence['before']==evidence['after'];passed('live exact slot fits; one over rejects ownership/serial unchanged',{'class':cls})
            evidence=dev(page,"const c=AstraeonInventoryCapacityDev,before=d.getInventoryCapacityState();d.unequip('weapon');const unequipped=c.snapshot();d.equip(Object.values(d.getInventory().instances).find(i=>i.definitionId==='traveler-blade').instanceId,'weapon');return {before,unequipped,after:c.snapshot()}");assert evidence['before']==evidence['unequipped']==evidence['after'];passed('live equip/unequip has no capacity drift',{'class':cls})
            evidence=dev(page,"const c=AstraeonInventoryCapacityDev,qty=d.getQuantity('herb');d.removeStack('herb',qty);c.setTestPolicy({mode:'bounded',slotLimit:c.snapshot().occupiedSlots,weightLimit:1000,overLimitPolicy:'no-worse'});const before=d.snapshot(),blocked=d.buy('herb');c.restorePolicy();const fit=d.buy('herb');d.addStack('herb',qty-1);return {before,blocked,blockedGold:before.gold,fit,after:d.snapshot()}")
            assert evidence['blocked']['code']=='SLOT_LIMIT_EXCEEDED' and evidence['fit']['ok'] and evidence['after']['gold']==evidence['before']['gold']-5;passed('live merchant blocked before charge; fitting purchase uses unchanged price',{'class':cls})
            evidence=dev(page,"const c=AstraeonInventoryCapacityDev,n=c.snapshot().occupiedSlots;c.setTestPolicy({mode:'bounded',slotLimit:n,weightLimit:1000,overLimitPolicy:'no-worse'});AstraeonMonsterLootDev.prepareFixture('proof-multi',[0,0,0,0]);const before=d.snapshot(),blocked=AstraeonMonsterLootDev.commitFixture(),after=d.snapshot();c.restorePolicy();const committed=AstraeonMonsterLootDev.commitFixture(),duplicate=AstraeonMonsterLootDev.duplicateFixture();return {before,blocked,after,committed,duplicate}")
            assert not evidence['blocked']['ok'] and evidence['before']==evidence['after'] and evidence['committed']['ok'] and evidence['duplicate']['code']=='ALREADY_COMMITTED';passed('live mixed Loot rejection atomic; retained exact claim retry commits once',{'class':cls})
            evidence=dev(page,"const c=AstraeonInventoryCapacityDev,owned=d.snapshot().itemInventory;c.setTestPolicy({mode:'bounded',slotLimit:c.snapshot().occupiedSlots-1,weightLimit:1000,overLimitPolicy:'no-worse'});const over=c.snapshot(),retained=d.snapshot().itemInventory;d.setCurrentHP(1);d.resetActionItemCooldowns();const consumed=d.useConsumable('potion'),sold=d.sell('ore');c.restorePolicy();d.addStack('potion',1);d.addStack('ore',1);return {owned,retained,over,consumed,sold}")
            assert evidence['owned']==evidence['retained'] and evidence['over']['isSlotOverLimit'] and evidence['consumed']['ok'] and evidence['sold']['ok'];passed('live over-limit retained; Action Item and sale remain available',{'class':cls})
            before=snap(page);award=dev(page,"const prepared=AstraeonMonsterLootDev.prepareFixture('proof-monster-box');return {prepared,result:AstraeonMonsterLootDev.commitFixture(),box:d.getQuantity('monster-box-proof'),runtime:b.state()} ")
            assert award['result']['ok'] and award['box']==1;assert award['runtime']['pending'] is None;assert qa(page)['monsterBoxes']['events']==[]
            for key in ['baseExp','baseJobExp','kills','quest','gold']:assert snap(page)[key]==before[key],key
            assert dev(page,"return AstraeonMonsterLootDev.duplicateFixture().code")=='ALREADY_COMMITTED';passed('controlled Monster Loot awards unopened canonical Box without opening or progression',{'class':cls,'award':award})
            envelope=dev(page,"const c=AstraeonInventoryCapacityDev;d.addStack('monster-box-proof',1);c.setTestPolicy({mode:'bounded',slotLimit:c.snapshot().occupiedSlots,weightLimit:1000,overLimitPolicy:'no-worse'});b.setRolls([.8]);const before=d.snapshot(),blocked=b.open('monster-box-proof'),after=d.snapshot(),runtime=b.state();c.restorePolicy();d.removeStack('monster-box-proof',1);return {before,blocked,after,runtime}")
            assert envelope['blocked']['code']=='SLOT_LIMIT_EXCEEDED' and envelope['before']==envelope['after'] and envelope['runtime']['pending'] is None;passed('live Box envelope blocks before source/RNG pending outcome; safe retry cannot shop contents',{'class':cls})
            separation=dev(page,"return {skill:AstraeonSkillDefinitions.getDefinition('monster-box-proof'),action:AstraeonActionItem.compile('monster-box-proof'),slots:d.getLoadout(),item:b.definitions().item}")
            assert separation['skill'] is None and not separation['action']['ok'] and BOX not in separation['slots'];assert separation['item']['stackable'];passed('Box remains outside learned slots and Action Item capabilities',{'class':cls})
            before=snap(page);clocks=dev(page,'return d.getActionItemRuntime()');prepared=dev(page,"b.setRolls([.4]);window.boxTicket=b.prepare('monster-box-proof');return window.boxTicket")
            assert prepared['authorizationOnly'] and 'boxes' not in prepared and 'resolution' not in prepared;assert snap(page)==before;close(page);page.locator('[data-open="inventory"]').click();page.locator('[data-item="monster-box-proof"]').click();after=snap(page)
            assert after['itemInventory']['stacks'].get(BOX,0)==0 and after['inventory']['potion']==before['inventory']['potion']+1;assert len(qa(page)['monsterBoxes']['events'])==1
            for key in ['currentHP','currentSP','gold','baseExp','baseJobExp','kills','quest','skillPoints','learnedSkills','actionLoadout']:assert after[key]==before[key],key
            assert dev(page,'return d.getActionItemRuntime()')==clocks;assert dev(page,'return b.commit(window.boxTicket).code')=='STALE_PACKAGE';assert snap(page)==after;passed('existing Bag single-open consumes once and grants exact content; no HP/SP/EXP/cooldown effects',{'class':cls})
            setup=dev(page,"d.addStack('monster-box-proof',3);b.setRolls([.8]);window.boxTicket=b.prepare('monster-box-proof');const copied=b.commit(structuredClone(window.boxTicket)),opened=b.commit(window.boxTicket),duplicate=b.commit(window.boxTicket);return {copied,opened,duplicate,stats:d.getDerivedStats(),equipped:d.getEquipped('weapon')} ")
            assert setup['copied']['code']=='INVALID_PACKAGE' and setup['duplicate']['code']=='ALREADY_COMMITTED';opened=setup['opened'];assert opened['ok'] and len(opened['instanceRewards'])==1 and opened['serialAfter']==opened['serialBefore']+1;gear=opened['instanceRewards'][0];assert gear['instanceId']!=setup['equipped'];assert dev(page,'return d.getInstance('+json.dumps(gear['instanceId'])+')')==gear
            equipped=dev(page,'const result=d.equip('+json.dumps(gear['instanceId'])+',"weapon");return {result,stats:d.getDerivedStats()}');assert equipped['result']['ok'];assert equipped['stats']['physicalATK']==setup['stats']['physicalATK']+6 and equipped['stats']['magicATK']==setup['stats']['magicATK']+6;passed('copied/duplicate guards and canonical equipment outcome reaches Equipment/Stats',{'class':cls,'gear':gear})
            before=snap(page);bulk=dev(page,"d.addStack('monster-box-proof',3);b.setRolls([0,0,.4,.8]);return b.open('monster-box-proof',3)");after=snap(page)
            assert bulk['ok'] and bulk['openedCount']==3 and len(bulk['boxes'])==3 and bulk['quantityBefore']==5 and bulk['quantityAfter']==2;assert [x['itemRewards'][0]['itemId'] for x in bulk['boxes']]==['herb','potion','astral-blade'];assert after['inventory']['herb']==before['inventory']['herb']+2 and after['inventory']['potion']==before['inventory']['potion']+1;assert bulk['serialAfter']==bulk['serialBefore']+1;assert dev(page,'return d.getEquipped("weapon")')==gear['instanceId'];passed('deterministic bulk three consumes exact N and commits aggregated stacks plus distinct gear',{'class':cls,'bulk':bulk})
            stale=dev(page,"window.boxTicket=b.prepare('monster-box-proof');d.addStack('ore',1);const before=d.snapshot(),result=b.commit(window.boxTicket);return {before,result,after:d.snapshot()}");assert stale['result']['code']=='STALE_PACKAGE' and stale['after']==stale['before'];passed('inventory mutation makes opening authorization stale without grants',{'class':cls})
            used=dev(page,"d.setCurrentHP(1);d.resetActionItemCooldowns();const before=d.getQuantity('potion'),result=d.useConsumable('potion');return {before,result,after:d.getQuantity('potion'),hp:d.snapshot().currentHP,clock:d.getActionItemRuntime()} ");assert used['result']['ok'] and used['after']==used['before']-1 and used['hp']>1
            before=snap(page);independent=dev(page,"b.setRolls([.4]);return b.open('monster-box-proof',1)");assert independent['ok'];assert snap(page)['currentHP']==before['currentHP'] and snap(page)['currentSP']==before['currentSP'];assert dev(page,'return d.getActionItemRuntime()')==used['clock'];passed('Box Potion works through Action Item; healing cooldown does not block or change Box open',{'class':cls})
            close(page);page.locator('[data-open="systems"]').click();page.locator('[data-nav="market"]').click();page.locator('[data-buy="herb:5"]').click();page.locator('[data-sell="herb:2"]').click();close(page);page.locator('[data-open="systems"]').click();page.locator('[data-nav="craft"]').click();prior=snap(page);page.locator('[data-craft="0"]').click();assert snap(page)['inventory']['potion']==prior['inventory']['potion']+1;assert snap(page)['itemInventory']['stacks'][BOX]==1;passed('existing merchant/crafting remain canonical alongside unopened Box',{'class':cls})
            pause(page);setup=dev(page,f"d.setBaseLevel(8);d.setBaseJobLevel(20);d.addSkillPoints(50);return {{learned:d.learnSkill('{skill}'),assigned:d.assignSkill(7,'{skill}')}}");assert setup['learned']['ok'] and setup['assigned']['ok'];dev(page,"window.boxTicket=b.prepare('monster-box-proof');d.setCurrentHP(d.snapshot().maxHP);d.setCurrentSP(d.snapshot().maxSP)");close(page);page.locator('[data-open="journal"]').click();page.locator('[data-quest="2"]').click();page.locator('[data-open="map"]').click();page.locator('[data-travel="2"]').click();page.wait_for_function('AstraeonQA.snapshot().save.zone===2');pause(page);assert dev(page,'return b.commit(window.boxTicket).code')=='STALE_PACKAGE';assert snap(page)['itemInventory']['stacks'][BOX]==1;passed('travel invalidates outstanding Box authorization and preserves quantity',{'class':cls})
            actor=next(e['lifecycle'] for e in qa(page)['enemies'] if e['hp']>0);id=actor['instanceId'];home=actor['home'];before=snap(page);close(page);place(page,home['x'],home['y']-.7);page.wait_for_function('!AstraeonQA.snapshot().action');wait_attack_window(page,id);assert dev(page,'return d.executeActionSlot(7)')['ok'];page.wait_for_function('skill=>AstraeonCombatDev.results().some(r=>r.result.ok&&r.result.input.context.sourceSkillId===skill)',arg=skill,timeout=30000);fight(page,id);pause(page);dead=inspect(page,id);events=[e for e in qa(page)['loot']['events'] if e['deathId']==dead['deathId']]
            assert len(events)==1 and dead['state'] in ['DEAD','RESPAWN_WAIT'];after=snap(page);assert after['kills']==before['kills']+1 and after['gold']==before['gold']+events[0]['currencyGranted'];assert after['baseExp']==before['baseExp']+events[0]['baseExp'] and after['baseJobExp']==before['baseJobExp']+events[0]['jobExp'];assert events[0]['questCredit']==1;assert after['itemInventory']['stacks'][BOX]==1
            combat=dev(page,'return AstraeonCombatDev.results().filter(r=>r.result.ok)')
            assert any(r['result']['input']['context'].get('sourceSkillId')==skill and r['result']['input']['attacker']['stats']['physicalATK' if cls=='0' else 'magicATK']==dev(page,'return d.getDerivedStats()')['physicalATK' if cls=='0' else 'magicATK'] for r in combat)
            duplicate=dev(page,'return AstraeonMonsterLootDev.repeatDeath('+json.dumps(id)+')');assert duplicate['code']=='ALREADY_COMMITTED' and snap(page)==after;passed('real learned Skill/Basic Attack consume box-derived gear Stats and retain exactly-once death rewards',{'class':cls,'death':dead,'event':events[0]})
            place(page,14.5,14.5);close(page);page.wait_for_function('({id,life})=>AstraeonMonsterLifecycleDev.inspect(id)?.lifeGeneration===life+1',arg={'id':id,'life':actor['lifeGeneration']},timeout=60000);assert inspect(page,id)['deathId'] is None;fight(page,id);pause(page);second=inspect(page,id);assert second['deathId']!=dead['deathId'];events=[e for e in qa(page)['loot']['events'] if e['deathId'].startswith(id+':')];assert len(events)==2;assert snap(page)['itemInventory']['stacks'][BOX]==1;passed('Monster Lifecycle respawns new life and second legitimate death rewards without Box replay',{'class':cls})
            living=next(e['lifecycle'] for e in qa(page)['enemies'] if e['hp']>0);ownership=snap(page)['itemInventory'];place(page,living['position']['x'],living['position']['y']-.7);dev(page,"window.boxTicket=b.prepare('monster-box-proof');d.setCurrentHP(1)");close(page);page.wait_for_function('AstraeonQA.snapshot().save.currentHP===0',timeout=60000);assert all(e['lifecycle']['targetId'] is None for e in qa(page)['enemies']);page.wait_for_function('AstraeonQA.snapshot().save.zone===0&&AstraeonQA.snapshot().save.currentHP>0',timeout=30000);pause(page);assert snap(page)['itemInventory']==ownership and dev(page,'return b.commit(window.boxTicket).code')=='STALE_PACKAGE';passed('actual player death/respawn preserves remaining Boxes/contents and invalidates ticket',{'class':cls})
            dev(page,'d.save()');saved=snap(page);page.reload(wait_until='load');page.wait_for_selector('#world');pause(page);loaded=snap(page)
            for key in ['itemInventory','equippedItems','gold','kills','baseExp','baseJobExp','quest']:assert loaded[key]==saved[key],key
            assert loaded['saveVersion']==5 and qa(page)['monsterBoxes']['events']==[] and qa(page)['monsterBoxes']['runtime']['pending'] is None;assert qa(page)['loot']['events']==[];passed('save/reload preserves unopened Box and committed contents/serial without opening/death replay',{'class':cls})
            close(page);page.locator('[data-open="map"]').click();page.locator('[data-travel="2"]').click();page.wait_for_function('AstraeonQA.snapshot().save.zone===2');page.locator('[data-open="map"]').click();page.locator('[data-travel="0"]').click();page.wait_for_function('AstraeonQA.snapshot().save.zone===0');pause(page);assert snap(page)['itemInventory']==loaded['itemInventory'] and snap(page)['kills']==loaded['kills'];assert qa(page)['monsterBoxes']['events']==[];passed('town/field round trip does not refund or duplicate Boxes/contents',{'class':cls});context.close()
        context,page=open_page('/tools/monster-box.html');page.wait_for_function('AstraeonMonsterBoxHarness.snapshot().inventory');page.locator('#add-many').click();page.locator('#prepare').click();prepared=json.loads(page.locator('#ticket').inner_text());assert prepared['authorizationOnly'] and 'boxes' not in prepared;page.locator('#commit').click();r=json.loads(page.locator('#result').inner_text());assert r['ok'] and r['openedCount']==3 and r['quantityAfter']==2 and len(r['instanceRewards'])==1;page.locator('#duplicate').click();assert json.loads(page.locator('#result').inner_text())['code']=='ALREADY_COMMITTED';passed('isolated harness deterministic bulk/roll evidence/serial/duplicate inspect correctly')
        page.locator('#count').fill('1');page.locator('#prepare').click();page.locator('#mutate').click();page.locator('#commit').click();assert json.loads(page.locator('#result').inner_text())['code']=='STALE_PACKAGE';page.locator('#rolls').fill('.8');page.locator('#single').click();assert json.loads(page.locator('#result').inner_text())['ok'];page.locator('#prepare').click();page.locator('#save').click();before=page.evaluate('AstraeonMonsterBoxHarness.snapshot().inventory');page.locator('#reload').click();page.locator('#commit').click();assert json.loads(page.locator('#result').inner_text())['code']=='INVALID_PACKAGE';assert page.evaluate('AstraeonMonsterBoxHarness.snapshot().inventory')==before;assert page.evaluate('localStorage.getItem("astraeon-iso-v1")') is None;passed('isolated harness single/stale/reload keeps canonical ownership without playable storage');context.close()
        context,page=open_page('/tools/inventory-capacity.html');page.wait_for_function('AstraeonCapacityHarness.snapshot().capacity');
        def harness(code):return page.evaluate('()=>{const h=AstraeonCapacityHarness;'+code+'}')
        for cls in [0,12]:
            evidence=harness(f"h.reset({{cls:{cls},slotLimit:1,weightLimit:.3}});const fit=h.add('herb',3),before=h.snapshot(),slots=h.add('ore'),weight=h.add('herb');return {{fit,before,slots,weight,after:h.snapshot()}}")
            assert evidence['fit']['ok'] and evidence['slots']['code']=='SLOT_LIMIT_EXCEEDED' and evidence['weight']['code']=='WEIGHT_LIMIT_EXCEEDED';assert evidence['before']['inventory']==evidence['after']['inventory'];assert evidence['after']['capacity']['totalWeight']==.3;passed('weighted isolated exact boundary and one-over slot/weight reject immutably',{'class':cls})
            evidence=harness("h.reset({stacks:{'monster-box-proof':2},slotLimit:1});const before=h.snapshot(),failed=h.open(1),after=h.snapshot();return {before,failed,after}");assert not evidence['failed']['ok'] and evidence['after']['draws']==0 and evidence['before']['inventory']==evidence['after']['inventory'];passed('weighted harness Box envelope rejects before RNG with no consumption/allocation',{'class':cls})
            evidence=harness("h.reset({stacks:{'monster-box-proof':1},slotLimit:3,weightLimit:1});h.setRolls([.8]);const opened=h.open(),before=h.snapshot();h.equip(opened.instanceRewards[0].instanceId);const equipped=h.snapshot();h.unequip();return {opened,before,equipped,after:h.snapshot()}");assert evidence['opened']['ok'];assert evidence['before']['capacity']['occupiedSlots']==1 and evidence['before']['capacity']['totalWeight']==.4;assert evidence['before']['capacity']==evidence['equipped']['capacity']==evidence['after']['capacity'];assert evidence['equipped']['stats']['physicalATK']==evidence['before']['stats']['physicalATK']+6;passed('weighted Box equipment creates one instance slot and weight; equip reaches Stats without drift',{'class':cls})
            evidence=harness("h.reset({stacks:{'monster-box-proof':1,potion:1},slotLimit:2,table:{id:'box-proof-basic',entries:[{id:'p',itemId:'potion',rollMode:'guaranteed',minQuantity:1,maxQuantity:1}]}});const opened=h.open(),before=h.snapshot(),consumed=h.consume();return {opened,before,consumed,after:h.snapshot()}");assert evidence['opened']['ok'] and evidence['before']['capacity']['occupiedSlots']==1 and evidence['before']['capacity']['totalWeight']==.6;assert evidence['consumed']['ok'] and evidence['after']['capacity']['totalWeight']==.3;passed('net final Box removes source slot; stack merge and Action Item weight decrease',{'class':cls})
            evidence=harness("h.reset({stacks:{herb:2,shard:1},slotLimit:2});const net=h.craft('potion'),after=h.snapshot();h.reset({stacks:{herb:3,shard:2},slotLimit:2});const before=h.snapshot(),blocked=h.craft('potion');return {net,after,before,blocked,failed:h.snapshot()}");assert evidence['net']['ok'] and evidence['after']['capacity']['occupiedSlots']==1;assert not evidence['blocked']['ok'] and evidence['before']['inventory']==evidence['failed']['inventory'];passed('weighted crafting net inputs free slots; blocked output preserves ingredients',{'class':cls})
            evidence=harness("h.reset({slotLimit:0});const before=h.snapshot(),blocked=h.buy('herb');h.setPolicy(1,.2);const fit=h.buy('herb',2);h.setPolicy(0,0);const over=h.snapshot(),sell=h.sell('herb',2);return {before,blocked,fit,over,sell,after:h.snapshot()}");assert not evidence['blocked']['ok'] and evidence['fit']['ok'];assert evidence['over']['save']['gold']==evidence['before']['save']['gold']-10 and evidence['over']['capacity']['isOverLimit'];assert evidence['sell']['ok'] and evidence['after']['capacity']['occupiedSlots']==0;passed('weighted merchant rejects charge; over-limit save keeps ownership and sale recovers',{'class':cls})
            evidence=harness("h.reset({slotLimit:1});h.prepareLoot('proof-multi',[0,.5,0,0]);const before=h.snapshot(),blocked=h.commitLoot();h.setPolicy(10,10);const committed=h.commitLoot(),duplicate=h.commitLoot();return {before,blocked,committed,duplicate,after:h.snapshot()}");assert not evidence['blocked']['ok'] and evidence['committed']['ok'] and evidence['duplicate']['code']=='ALREADY_COMMITTED';assert evidence['after']['capacity']['totalWeight']==.9;passed('weighted mixed Loot no partial grant; same entitlement commits once after capacity recovery',{'class':cls})
            evidence=harness("h.reset({stacks:{herb:3,'monster-box-proof':2},instances:['astral-blade']});h.prepare();h.save();const before=h.snapshot();h.reload();const rejected=h.commit();return {before,rejected,after:h.snapshot()}");assert evidence['rejected']['code']=='INVALID_PACKAGE';assert evidence['before']['inventory']==evidence['after']['inventory'] and evidence['before']['capacity']==evidence['after']['capacity'];assert page.evaluate('localStorage.getItem("astraeon-iso-v1")') is None;passed('weighted isolated save/reload reproduces capacity/ownership and retires tickets',{'class':cls})
        context.close()
        context,page=open_page('/');page.wait_for_selector('#create');page.locator('#newname').fill('Normal Box boot');page.locator('#create').click();page.wait_for_selector('#world');assert page.evaluate('typeof AstraeonInventoryCapacityDev')=='undefined';assert page.evaluate('typeof AstraeonCapacityHarness')=='undefined';assert page.evaluate('typeof AstraeonMonsterBoxDev')=='undefined';assert page.evaluate('typeof AstraeonMonsterBoxHarness')=='undefined';assert page.evaluate('typeof AstraeonProgressionDev')=='undefined';page.locator('[data-open="inventory"]').click();assert page.locator('[data-item="monster-box-proof"]').count()==0;passed('normal URL boots without Box mutation globals or unowned Box controls');context.close();browser.close()
    assert not errors and not http_errors,(errors,http_errors);report['result']='passed'
except Exception as error:report.update(result='failed',failure=str(error));raise
finally:
    report.update(checks=checks,runtimeErrors=errors,httpErrors=http_errors,liveTargetingObservations=timing);(args.output/'report.json').write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8')
print('PASS',len(checks),'Inventory Capacity browser groups',flush=True)
