const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),child=require('node:child_process');
global.window={};
for(const n of ['input','skill-nodes','combat','progression-config','progression','stats','skill-definitions','skill-tree','action-loadout','skill-runtime','action-runtime','character-state','item-definitions','equipment-slots','item-inventory','inventory-capacity','item-equipment','item-state','action-item-config','item-effects','action-item','action-item-runtime','drop-tables','monster-definitions','loot-resolution','monster-rewards','monster-loot-runtime','box-content-tables','monster-box','monster-box-runtime','combat-resolution-config','combat-resolution','combat-runtime','enemy-combat','monster-lifecycle-definitions','monster-lifecycle','monster-combat-runtime','quest-definitions','quest-state','quest-evidence','quest-runtime','player-state','save-state'])require('../'+n+'.js');
const D=window.AstraeonQuestDefinitions,Q=window.AstraeonQuestState,E=window.AstraeonQuestEvidence,Save=window.AstraeonSave,I=window.AstraeonItemInventory,Items=window.AstraeonItemDefinitions;
const q=key=>'quest-proof-'+key,clone=v=>structuredClone(v),definition=key=>clone(D.definitions.find(d=>d.id===q(key))),registry=D.createRegistry(D.definitions);
function fixture(extra={},options={}){
 const interactions=E.interactions([{id:'guild-registrar',x:0,y:0},{id:'merchant',x:1,y:0}]);let bridge;
 const state=Save.normalize({name:'Quest disposable',cls:0,legacySkillControls:false,itemInventory:I.normalize(),equippedItems:{},...extra});
 const context=()=>({interaction:interactions.current({zone:0,hp:p.snapshot().currentHP,x:0,y:0})});
 const p=window.AstraeonPlayer.attach(state,{...options,getQuestContext:context,isQuestTalkEvidence:interactions.owns,isQuestKillEvidence:e=>bridge?.owns(e)===true});
 const loot=window.AstraeonMonsterLootRuntime.create({commit:(r,id)=>p.commitMonsterRewards(r,id,[])},{initialKillOrdinal:state.kills});
 const lifecycle=window.AstraeonMonsterLifecycle.create({loot,getRewardContext:()=>p.getMonsterRewardContext(2),rng:window.AstraeonCombatRuntime.sequenceRng([])});
 bridge=E.deaths(lifecycle,p.observeQuestKill);
 function talk(id='guild-registrar'){const e=interactions.interact(id,{zone:0,hp:p.snapshot().currentHP,x:0,y:0});return {e,result:p.observeQuestTalk(e)}}
 function actor(id='leafmane-fox',spawn='spawn-1'){const a={x:5,y:5,hp:10,maxHp:10};assert(lifecycle.register(a,id,{id:spawn,home:{x:5,y:5}},0).ok);return a}
 function kill(a,now=1){a.hp=0;const output=lifecycle.notifyDeath(a,now);assert(output.ok);return {output,result:bridge.deliver(a,output)}}
 return {p,state,interactions,bridge,lifecycle,loot,talk,actor,kill,context};
}
function capture(f){return {save:Save.snapshot(f.state),stats:f.p.getDerivedStats(),capacity:f.p.getInventoryCapacityState(),revision:f.p.getInventoryRevision(),action:f.p.getActionRuntime(),item:f.p.getActionItemRuntime()}}
function rejected(f,fn,code){const before=capture(f),result=fn();assert.equal(result.ok,false);if(code)assert.equal(result.code,code);assert.deepEqual(capture(f),before);return result}
function accepted(f,key){assert(f.p.acceptQuest(q(key)).ok)}
function readyTalk(f,key='talk'){accepted(f,key);f.talk();assert.equal(f.p.getQuest(q(key)).status,'READY_TO_TURN_IN')}
function mutableDefinitions(d){return D.definitions.map(original=>original.id===d.id?d:clone(original))}
function custom(d,extra={},options={}){return fixture(extra,{...options,questDefinitions:mutableDefinitions(d)})}

for(const key of ['talk','kill','collect','mixed','chain'])test('authored immutable quest '+key,()=>{const d=D.definitions.find(d=>d.id===q(key));assert(D.validate(d).ok);assert(Object.isFrozen(d));assert(Object.isFrozen(d.objectives));assert(Object.isFrozen(d.rewards))});
test('complete immutable registry stable IDs and objective identities',()=>{assert(registry.ok);assert.deepEqual(registry.ids,D.definitions.map(d=>d.id));assert(Object.isFrozen(registry.definitions));assert(registry.getDefinition(q('talk')));assert.equal(registry.getDefinition({toString(){throw Error('coercion')}}),null)});
for(const value of ['',null,1,{},[],new String('x'),'__proto__'])test('invalid primitive quest ID '+String(value),()=>{const d=definition('talk');d.id=value;assert.equal(D.validate(d).ok,false)});
test('duplicate authored quest rejects whole registry',()=>assert.equal(D.createRegistry([...D.definitions,D.definitions[0]]).code,'DUPLICATE_QUEST'));
test('duplicate objective ID rejects',()=>{const d=definition('talk');d.objectives.push(clone(d.objectives[0]));assert.equal(D.validate(d).code,'INVALID_OBJECTIVE')});
for(const value of ['',null,1,{},'constructor'])test('invalid objective ID '+String(value),()=>{const d=definition('talk');d.objectives[0].id=value;assert(!D.validate(d).ok)});
for(const value of [0,-1,.5,NaN,Infinity,Number.MAX_SAFE_INTEGER,100001,'1',null])test('invalid required count '+String(value),()=>{const d=definition('talk');d.objectives[0].required=value;assert(!D.validate(d).ok)});
for(const type of ['ESCORT','talk','',null])test('unsupported objective '+String(type),()=>{const d=definition('talk');d.objectives[0].type=type;assert(!D.validate(d).ok)});
test('unknown NPC reference rejects',()=>{const d=definition('talk');d.objectives[0].targetId='not-npc';assert(!D.validate(d).ok)});
test('unknown monster reference rejects',()=>{const d=definition('kill');d.objectives[0].monsterDefinitionId='not-monster';assert.equal(D.validate(d).code,'UNKNOWN_MONSTER')});
test('unknown collect ItemDefinition rejects',()=>{const d=definition('collect');d.objectives[0].itemId='not-item';assert(!D.validate(d).ok)});
for(const value of [null,'true',1])test('explicit Collect consume policy required '+String(value),()=>{const d=definition('collect');d.objectives[0].consumeOnTurnIn=value;assert(!D.validate(d).ok)});
for(const value of [NaN,Infinity,()=>true,undefined])test('unsafe metadata rejects '+String(value),()=>{const d=definition('talk');d.metadata={value};assert(!D.validate(d).ok)});
test('cyclic metadata safely rejects without caller freezing',()=>{const d=definition('talk');d.metadata.loop=d;assert(!D.validate(d).ok);assert(!Object.isFrozen(d))});
for(const key of ['baseExp','jobExp','gold'])for(const value of [-1,.5,NaN,Infinity,Number.MAX_SAFE_INTEGER+1])test('invalid reward '+key+' '+String(value),()=>{const d=definition('talk');d.rewards[key]=value;assert(!D.validate(d).ok)});
for(const item of [{itemId:'unknown',quantity:1},{itemId:'potion',quantity:0},{itemId:'potion',quantity:1.5},{itemId:'astral-blade',quantity:10001}])test('invalid item reward '+JSON.stringify(item),()=>{const d=definition('talk');d.rewards.items=[item];assert(!D.validate(d).ok)});
test('unsupported reward field rejects',()=>{const d=definition('talk');d.rewards.random=true;assert(!D.validate(d).ok)});
test('invalid prerequisite reference rejects registry',()=>{const d=definition('talk');d.prerequisites=['unknown'];assert.equal(D.createRegistry(mutableDefinitions(d)).code,'UNKNOWN_PREREQUISITE')});
test('self prerequisite rejects',()=>{const d=definition('talk');d.prerequisites=[d.id];assert(!D.validate(d).ok)});
test('duplicate prerequisite rejects',()=>{const d=definition('chain');d.prerequisites.push(q('talk'));assert(!D.validate(d).ok)});
test('prerequisite cycle rejects before publication',()=>{const d=definition('talk');d.prerequisites=[q('chain')];assert.equal(D.createRegistry(mutableDefinitions(d)).code,'PREREQUISITE_CYCLE')});
test('repeatability stays disabled',()=>{const d=definition('talk');d.repeatable=true;assert(!D.validate(d).ok)});
test('malformed definitions cannot alter live state',()=>{const f=fixture(),before=capture(f),d=definition('talk');d.objectives[0].required=NaN;assert.throws(()=>custom(d),/INVALID/);assert.deepEqual(capture(f),before)});

test('old character starts empty without accepted/completed/migration rewards',()=>{const f=fixture();assert.deepEqual(f.p.getQuestState(),{schema:1,entries:{},history:{}});assert.equal(f.state.gold,50);assert.equal(f.p.getQuest(q('talk')).status,'AVAILABLE');assert.equal(f.p.getQuest(q('chain')).status,'LOCKED')});
test('accept once does not reset progress on duplicate',()=>{const f=fixture();readyTalk(f);rejected(f,()=>f.p.acceptQuest(q('talk')),'QUEST_ALREADY_ACCEPTED')});
test('unknown quest rejects accept',()=>{const f=fixture();rejected(f,()=>f.p.acceptQuest('unknown'),'UNKNOWN_QUEST')});
test('locked quest rejects accept',()=>{const f=fixture();rejected(f,()=>f.p.acceptQuest(q('chain')),'QUEST_LOCKED')});
for(const context of [{loading:true},{transitionPending:true},{retired:true},{restricted:true}])test('context blocked accept '+JSON.stringify(context),()=>{const f=fixture();rejected(f,()=>f.p.acceptQuest(q('talk'),context),'FORBIDDEN_QUEST_CONTEXT')});
test('dead actor cannot accept',()=>{const f=fixture();f.p.setCurrentHP(0);rejected(f,()=>f.p.acceptQuest(q('talk')),'FORBIDDEN_QUEST_CONTEXT')});
test('explicit controlled transitions; Collect may invalidate READY',()=>{assert(Q.canTransition('AVAILABLE','ACTIVE'));assert(Q.canTransition('READY_TO_TURN_IN','ACTIVE'));assert(!Q.canTransition('AVAILABLE','COMPLETED'));assert(!Q.canTransition('COMPLETED','ACTIVE'));assert(!Q.canTransition('unknown','ACTIVE'))});
test('multiple active quests independent',()=>{const f=fixture();for(const k of ['talk','kill','collect','mixed'])accepted(f,k);assert.equal(Object.keys(f.p.getQuestState().entries).length,4)});

test('proximity/querying/opening has no Talk progress',()=>{const f=fixture();accepted(f,'talk');for(let i=0;i<5;i++)f.context();assert.equal(f.p.getQuest(q('talk')).objectives[0].progress,0)});
test('correct semantic interaction counts after acceptance',()=>{const f=fixture();readyTalk(f);assert.equal(f.p.getQuest(q('talk')).objectives[0].progress,1)});
test('preaccept interaction cannot be replayed for progress',()=>{const f=fixture(),t=f.talk();accepted(f,'talk');assert.equal(f.p.observeQuestTalk(t.e).code,'DUPLICATE_QUEST_EVIDENCE');assert.equal(f.p.getQuest(q('talk')).objectives[0].progress,0)});
test('wrong NPC counts no Talk',()=>{const f=fixture();accepted(f,'talk');f.talk('merchant');assert.equal(f.p.getQuest(q('talk')).objectives[0].progress,0)});
test('repeated Talk caps one-time progress',()=>{const f=fixture();readyTalk(f);f.talk();f.talk();assert.equal(f.p.getQuest(q('talk')).objectives[0].progress,1)});
test('same Talk event replay rejects',()=>{const f=fixture();accepted(f,'talk');const t=f.talk();assert.equal(f.p.observeQuestTalk(t.e).code,'DUPLICATE_QUEST_EVIDENCE')});
test('copied/forged/foreign interaction cannot count',()=>{const f=fixture();accepted(f,'talk');const other=fixture().talk().e;for(const e of [other,clone(other),{type:'NPC_INTERACTED',targetId:'guild-registrar'}])assert.equal(f.p.observeQuestTalk(e).code,'INVALID_QUEST_EVIDENCE');assert.equal(f.p.getQuest(q('talk')).objectives[0].progress,0)});
test('one interaction progresses independent matching quests',()=>{const f=fixture();accepted(f,'talk');accepted(f,'mixed');f.talk();for(const k of ['talk','mixed'])assert.equal(f.p.getQuest(q(k)).objectives[0].progress,1)});
for(const context of [{zone:1,hp:10,x:0,y:0},{zone:0,hp:0,x:0,y:0},{zone:0,hp:10,x:3,y:0},{zone:0,hp:10,x:NaN,y:0},{zone:0,hp:10,x:0,y:0,loading:true}])test('invalid interaction context '+JSON.stringify(context),()=>{const f=fixture();assert(!f.interactions.interact('guild-registrar',context).ok)});
test('current interaction invalidates when actor leaves range',()=>{const f=fixture();f.talk();assert.equal(f.interactions.current({zone:0,hp:10,x:4,y:0}),null)});

test('correct authoritative Lifecycle death increments Kill once',()=>{const f=fixture();accepted(f,'kill');const a=f.actor(),k=f.kill(a);assert(k.result.ok);assert.equal(f.p.getQuest(q('kill')).objectives[0].progress,1);assert.equal(f.p.observeQuestKill(k.result.evidence).code,'DUPLICATE_QUEST_EVIDENCE')});
test('same death Lifecycle replay and copied output cannot count again',()=>{const f=fixture();accepted(f,'kill');const a=f.actor(),k=f.kill(a);assert(!f.bridge.deliver(a,k.output).ok);assert(!f.bridge.deliver(a,clone(k.output)).ok);assert(f.lifecycle.notifyDeath(a,1).duplicate);assert.equal(f.p.getQuest(q('kill')).objectives[0].progress,1)});
test('HP zero alone grants no Kill evidence',()=>{const f=fixture();accepted(f,'kill');const a=f.actor();a.hp=0;assert(!f.bridge.deliver(a,{deathEvent:{type:'death',deathId:'monster-1:life-1:death-1',instanceId:'monster-1',lifeGeneration:1}}).ok);assert.equal(f.p.getQuest(q('kill')).objectives[0].progress,0)});
test('wrong MonsterDefinition gives no Kill progress',()=>{const f=fixture();accepted(f,'kill');f.kill(f.actor('mossback-boar'));assert.equal(f.p.getQuest(q('kill')).objectives[0].progress,0)});
test('foreign death owner cannot mint Kill evidence',()=>{const f=fixture(),other=fixture();accepted(f,'kill');const a=other.actor(),k=other.kill(a);assert(!f.bridge.deliver(a,k.output).ok);assert.equal(f.p.observeQuestKill(k.result.evidence).code,'INVALID_QUEST_EVIDENCE')});
test('same runtime new life is a new legitimate kill',()=>{const f=fixture();accepted(f,'kill');const a=f.actor(),first=f.kill(a);assert(f.lifecycle.update(a,{now:2,active:true}).ok);assert(f.lifecycle.respawn(a,13).ok);const second=f.kill(a,14);assert.notEqual(first.output.deathEvent.deathId,second.output.deathEvent.deathId);assert.equal(f.p.getQuest(q('kill')).objectives[0].progress,2);assert(!f.bridge.deliver(a,first.output).ok)});
test('one death progresses multiple active matching quests once each',()=>{const f=fixture();accepted(f,'kill');accepted(f,'mixed');f.kill(f.actor());assert.equal(f.p.getQuest(q('kill')).objectives[0].progress,1);assert.equal(f.p.getQuest(q('mixed')).objectives[1].progress,1)});
test('events before acceptance never accrue retrospective kill credit',()=>{const f=fixture(),k=f.kill(f.actor());accepted(f,'kill');assert.equal(f.p.observeQuestKill(k.result.evidence).code,'DUPLICATE_QUEST_EVIDENCE');assert.equal(f.p.getQuest(q('kill')).objectives[0].progress,0)});
test('Loot resolution/commit alone cannot fabricate kill evidence',()=>{const f=fixture();accepted(f,'kill');const a={hp:1};assert(f.loot.register(a,'proof-material').ok);a.hp=0;const claim=f.loot.prepareDeath(a,f.p.getMonsterRewardContext(2),{next(){throw Error('no draw')}});assert(f.loot.commit(claim).ok);assert.equal(f.p.observeQuestKill(claim.resolution).code,'INVALID_QUEST_EVIDENCE');assert.equal(f.p.getQuest(q('kill')).objectives[0].progress,0)});
test('capacity-blocked Loot still has valid independent death evidence',()=>{let policy={mode:'bounded',slotLimit:0,weightLimit:0,overLimitPolicy:'no-worse'};const f=fixture({kills:1},{getCapacityPolicy:()=>policy});accepted(f,'kill');const k=f.kill(f.actor());assert.equal(k.output.reward.ok,false);assert(k.result.ok);assert.equal(f.p.getQuest(q('kill')).objectives[0].progress,1);assert.equal(f.state.kills,1)});

test('Collect derives already-owned stack and persists no count',()=>{const f=fixture();assert(f.p.addStack('herb',3).ok);accepted(f,'collect');assert.equal(f.p.getQuest(q('collect')).status,'READY_TO_TURN_IN');assert.deepEqual(f.p.getQuestState().entries[q('collect')].progress,{})});
test('wrong item does not satisfy Collect',()=>{const f=fixture();accepted(f,'collect');f.p.addStack('ore',3);assert.equal(f.p.getQuest(q('collect')).objectives[0].progress,0)});
test('2/3 -> 3/3 ready -> spend one -> 2/3 incomplete',()=>{const f=fixture();accepted(f,'collect');f.p.addStack('herb',2);assert.equal(f.p.getQuest(q('collect')).status,'ACTIVE');f.p.addStack('herb',1);assert.equal(f.p.getQuest(q('collect')).status,'READY_TO_TURN_IN');f.p.removeStack('herb',1);assert.equal(f.p.getQuest(q('collect')).status,'ACTIVE');assert.equal(f.p.getQuest(q('collect')).objectives[0].progress,2)});
test('readiness never consumes/reserves owned items',()=>{const f=fixture();f.p.addStack('herb',3);accepted(f,'collect');const before=capture(f);for(let i=0;i<10;i++)f.p.getQuest(q('collect'));assert.deepEqual(capture(f),before)});
test('same consuming ItemDefinition requirements share ownership pool',()=>{const d=definition('collect');d.objectives.push({...d.objectives[0],id:'collect-herb-2',required:2});const f=custom(d);accepted(f,'collect');f.p.addStack('herb',3);assert.deepEqual(f.p.getQuest(q('collect')).objectives.map(o=>o.progress),[3,0]);f.p.addStack('herb',2);assert.equal(f.p.getQuest(q('collect')).status,'READY_TO_TURN_IN');f.talk();assert(f.p.turnInQuest(q('collect')).ok);assert.equal(f.p.getQuantity('herb'),0)});
test('multiple Collect items commit one complete plan',()=>{const d=definition('collect');d.objectives.push({id:'ore-proof',type:'COLLECT',itemId:'ore',required:2,consumeOnTurnIn:true});const f=custom(d);accepted(f,'collect');f.p.addStack('herb',3);f.p.addStack('ore',2);f.talk();const r=f.p.turnInQuest(q('collect'));assert(r.ok);assert.equal(f.p.getQuantity('herb'),0);assert.equal(f.p.getQuantity('ore'),0);assert.equal(f.p.getQuantity('potion'),1)});
test('later incomplete Collect prevents any earlier consumption',()=>{const d=definition('collect');d.objectives.push({id:'ore-proof',type:'COLLECT',itemId:'ore',required:2,consumeOnTurnIn:true});const f=custom(d);accepted(f,'collect');f.p.addStack('herb',3);f.p.addStack('ore',1);f.talk();rejected(f,()=>f.p.turnInQuest(q('collect')),'QUEST_NOT_READY')});
test('non-consuming Collect retains quantity',()=>{const d=definition('collect');d.objectives[0].consumeOnTurnIn=false;const f=custom(d);accepted(f,'collect');f.p.addStack('herb',3);f.talk();assert(f.p.turnInQuest(q('collect')).ok);assert.equal(f.p.getQuantity('herb'),3)});
test('non-stack Collect counts canonical owned instances',()=>{const d=definition('collect');d.objectives[0].itemId='astral-blade';d.objectives[0].required=1;const f=custom(d);accepted(f,'collect');const i=f.p.createItemInstance('astral-blade');assert.equal(f.p.getQuest(q('collect')).status,'READY_TO_TURN_IN');f.talk();assert(f.p.turnInQuest(q('collect')).ok);assert.equal(f.p.getInstance(i.instance.instanceId),null);assert.equal(f.p.getInventory().nextItemSerial,2)});
test('equipped Collect item cannot be consumed; ownership/modifiers retained',()=>{const d=definition('collect');d.objectives[0].itemId='astral-blade';d.objectives[0].required=1;const f=custom(d);accepted(f,'collect');const i=f.p.createItemInstance('astral-blade');assert(f.p.equip(i.instance.instanceId,'mainHand').ok);f.talk();rejected(f,()=>f.p.turnInQuest(q('collect')),'ITEM_EQUIPPED')});

test('incomplete/not-accepted turn-in rejects with no mutation',()=>{const f=fixture();f.talk();rejected(f,()=>f.p.turnInQuest(q('talk')),'QUEST_NOT_READY');accepted(f,'talk');rejected(f,()=>f.p.turnInQuest(q('talk')),'QUEST_NOT_READY')});
test('wrong turn-in target rejects even when objectives complete',()=>{const f=fixture();readyTalk(f);f.talk('merchant');rejected(f,()=>f.p.turnInQuest(q('talk')),'WRONG_TURN_IN_TARGET')});
test('prepare immutable and non-mutating with complete plan',()=>{const f=fixture();readyTalk(f);const before=capture(f),t=f.p.prepareQuestTurnIn(q('talk'));assert(t.ok);assert(Object.isFrozen(t));assert(Object.isFrozen(t.transaction));assert.deepEqual(capture(f),before)});
test('successful turn-in grants exact authored Base/Job/gold/stack once',()=>{const f=fixture();readyTalk(f);const before=f.p.snapshot(),gold=f.state.gold,t=f.p.prepareQuestTurnIn(q('talk')),r=f.p.commitQuestTurnIn(t);assert(r.ok&&r.committed);assert.equal(f.p.snapshot().baseExp,before.baseExp+3);assert.equal(f.p.snapshot().baseJobExp,before.baseJobExp+2);assert.equal(f.state.gold,gold+4);assert.equal(f.p.getQuantity('potion'),1);assert.equal(f.p.getQuest(q('talk')).status,'COMPLETED');rejected(f,()=>f.p.commitQuestTurnIn(t),'ALREADY_COMMITTED');rejected(f,()=>f.p.turnInQuest(q('talk')),'QUEST_COMPLETED');rejected(f,()=>f.p.acceptQuest(q('talk')),'QUEST_COMPLETED')});
test('copied/forged/foreign authorization cannot mint reward',()=>{const f=fixture();readyTalk(f);const t=f.p.prepareQuestTurnIn(q('talk')),other=fixture();readyTalk(other);for(const ticket of [clone(t),{...t},other.p.prepareQuestTurnIn(q('talk')),{},null])rejected(f,()=>f.p.commitQuestTurnIn(ticket),'INVALID_QUEST_TICKET')});
test('sibling preparations cannot double complete',()=>{const f=fixture();readyTalk(f);const a=f.p.prepareQuestTurnIn(q('talk')),b=f.p.prepareQuestTurnIn(q('talk'));assert(f.p.commitQuestTurnIn(a).ok);rejected(f,()=>f.p.commitQuestTurnIn(b),'STALE_QUEST_TICKET')});
test('inventory mutation between prepare/commit rejects stale',()=>{const f=fixture();readyTalk(f);const t=f.p.prepareQuestTurnIn(q('talk'));f.p.addStack('ore',1);rejected(f,()=>f.p.commitQuestTurnIn(t),'STALE_QUEST_TICKET')});
test('Collect debit between prepare/commit prevents all rewards',()=>{const f=fixture();accepted(f,'collect');f.p.addStack('herb',3);f.talk();const t=f.p.prepareQuestTurnIn(q('collect'));f.p.removeStack('herb',1);rejected(f,()=>f.p.commitQuestTurnIn(t),'STALE_QUEST_TICKET');assert.equal(f.p.getQuantity('herb'),2);assert.equal(f.p.getQuantity('potion'),0)});
test('progression mutation invalidates prepared reward plan',()=>{const f=fixture();readyTalk(f);const t=f.p.prepareQuestTurnIn(q('talk'));f.p.grantBaseExp(1);rejected(f,()=>f.p.commitQuestTurnIn(t),'STALE_QUEST_TICKET')});
test('gold mutation invalidates prepared turn-in',()=>{const f=fixture();readyTalk(f);const t=f.p.prepareQuestTurnIn(q('talk'));f.state.gold++;rejected(f,()=>f.p.commitQuestTurnIn(t),'STALE_QUEST_TICKET')});
test('context invalidation invalidates old transient tickets only',()=>{const f=fixture();readyTalk(f);const t=f.p.prepareQuestTurnIn(q('talk'));const durable=f.p.getQuestState();assert(f.p.invalidatePreparedActions().ok);assert.deepEqual(f.p.getQuestState(),durable);rejected(f,()=>f.p.commitQuestTurnIn(t),'STALE_QUEST_TICKET')});
test('dead/loading actor cannot commit turn-in',()=>{const f=fixture();readyTalk(f);const t=f.p.prepareQuestTurnIn(q('talk'));rejected(f,()=>f.p.commitQuestTurnIn(t,{loading:true}),'FORBIDDEN_QUEST_CONTEXT');f.p.setCurrentHP(0);rejected(f,()=>f.p.commitQuestTurnIn(t),'FORBIDDEN_QUEST_CONTEXT')});
test('currency overflow rejects before item debit/reward',()=>{const f=fixture({gold:Number.MAX_SAFE_INTEGER});readyTalk(f);rejected(f,()=>f.p.turnInQuest(q('talk')),'CURRENCY_OVERFLOW')});
test('failed Character planning grants nothing',()=>{let fail=false;const f=fixture({}, {conversionHooks:[()=>{if(fail)throw Error('conversion failure');return {}}]});readyTalk(f);fail=true;rejected(f,()=>f.p.turnInQuest(q('talk')),'INVALID_PROGRESSION_REWARD')});

test('capacity rejection leaves ready quest and Collect items intact',()=>{const d=definition('collect');d.rewards.items=[{itemId:'potion',quantity:1},{itemId:'shard',quantity:1}];const f=custom(d,{}, {getCapacityPolicy:()=>({mode:'bounded',slotLimit:1,weightLimit:0,overLimitPolicy:'no-worse'})});accepted(f,'collect');f.p.addStack('herb',3);f.talk();rejected(f,()=>f.p.turnInQuest(q('collect')),'SLOT_LIMIT_EXCEEDED');assert.equal(f.p.getQuest(q('collect')).status,'READY_TO_TURN_IN');assert.equal(f.p.getQuantity('herb'),3)});
test('net Collect source debit frees final slot for reward',()=>{const f=fixture({}, {getCapacityPolicy:()=>({mode:'bounded',slotLimit:1,weightLimit:0,overLimitPolicy:'no-worse'})});accepted(f,'collect');f.p.addStack('herb',3);f.talk();const t=f.p.prepareQuestTurnIn(q('collect'));assert(t.ok);assert.equal(t.preflight.capacity.delta.slots,0);assert(f.p.commitQuestTurnIn(t).ok);assert.equal(f.p.getQuantity('herb'),0);assert.equal(f.p.getQuantity('potion'),1)});
test('partial Collect source stack retains slot and blocks new reward atomically',()=>{const f=fixture({}, {getCapacityPolicy:()=>({mode:'bounded',slotLimit:1,weightLimit:0,overLimitPolicy:'no-worse'})});accepted(f,'collect');f.p.addStack('herb',4);f.talk();rejected(f,()=>f.p.turnInQuest(q('collect')),'SLOT_LIMIT_EXCEEDED');assert.equal(f.p.getQuantity('herb'),4)});
test('policy change between prepare/commit rejects without rewards',()=>{let slots=3;const f=fixture({}, {getCapacityPolicy:()=>({mode:'bounded',slotLimit:slots,weightLimit:0,overLimitPolicy:'no-worse'})});readyTalk(f);const t=f.p.prepareQuestTurnIn(q('talk'));slots=0;rejected(f,()=>f.p.commitQuestTurnIn(t),'SLOT_LIMIT_EXCEEDED')});
test('over-limit reducing net transaction remains allowed',()=>{const inv=I.addStack(I.addStack(I.normalize(),'herb',3).inventory,'ore',1).inventory;const d=definition('collect');d.rewards.items=[];const f=custom(d,{itemInventory:inv},{getCapacityPolicy:()=>({mode:'bounded',slotLimit:1,weightLimit:0,overLimitPolicy:'no-worse'})});accepted(f,'collect');f.talk();assert(f.p.getInventoryCapacityState().isOverLimit);assert(f.p.turnInQuest(q('collect')).ok);assert(!f.p.getInventoryCapacityState().isOverLimit)});
test('mixed reward gear canonical instance/no auto-equip/exact serial',()=>{const f=fixture();accepted(f,'mixed');f.talk();f.p.addStack('ore',2);f.kill(f.actor());const serial=f.p.getInventory().nextItemSerial,r=f.p.turnInQuest(q('mixed'));assert(r.ok);assert.equal(r.instanceRewards.length,1);const i=r.instanceRewards[0];assert.equal(i.definitionId,'offhand-proof');assert.equal(f.p.getInstance(i.instanceId),i);assert.equal(f.p.getEquipped('offHand'),null);assert.equal(f.p.getInventory().nextItemSerial,serial+1);assert(f.p.equip(i.instanceId,'offHand').ok);assert(f.p.getDerivedStats().DEF>0)});
test('stack-only Quest rewards never advance instance serial',()=>{const f=fixture();readyTalk(f);const serial=f.p.getInventory().nextItemSerial;assert(f.p.turnInQuest(q('talk')).ok);assert.equal(f.p.getInventory().nextItemSerial,serial)});
test('instance serial exhaustion leaves ready quest and source untouched',()=>{const f=fixture({itemInventory:I.normalize({nextItemSerial:Number.MAX_SAFE_INTEGER})});accepted(f,'mixed');f.talk();f.p.addStack('ore',2);f.kill(f.actor());rejected(f,()=>f.p.turnInQuest(q('mixed')),'SERIAL_EXHAUSTED')});
test('Quest completion grants no monster kill/legacy contract credit',()=>{const f=fixture();readyTalk(f);const before={kills:f.state.kills,quest:f.state.quest,clears:f.state.clears,reputation:f.state.reputation};assert(f.p.turnInQuest(q('talk')).ok);assert.deepEqual({kills:f.state.kills,quest:f.state.quest,clears:f.state.clears,reputation:f.state.reputation},before)});
test('reward Potion remains canonical Action Item',()=>{const f=fixture();readyTalk(f);assert(f.p.turnInQuest(q('talk')).ok);f.p.setCurrentHP(1);const r=f.p.useConsumable('potion',{now:0,intent:'inventory'});assert(r.ok);assert.equal(f.p.getQuantity('potion'),0);assert.equal(f.p.getQuest(q('talk')).status,'COMPLETED')});
test('Box opening neither progresses Kill nor couples Quest to RNG',()=>{const f=fixture({}, {getBoxRng:()=>window.AstraeonCombatRuntime.sequenceRng([.5])});accepted(f,'kill');f.p.addStack('monster-box-proof',1);const before=f.p.getQuestState();assert(f.p.openMonsterBoxes('monster-box-proof',1).ok);assert.deepEqual(f.p.getQuestState(),before)});
test('turn-in does not change learned slots/ranks/cooldowns',()=>{const f=fixture();readyTalk(f);const before={skills:f.p.getLearnedSkills(),slots:f.p.getLoadout(),actions:f.p.getActionRuntime(),items:f.p.getActionItemRuntime()};assert(f.p.turnInQuest(q('talk')).ok);assert.deepEqual({skills:f.p.getLearnedSkills(),slots:f.p.getLoadout(),actions:f.p.getActionRuntime(),items:f.p.getActionItemRuntime()},before)});

test('Talk and accepted state persists without replay on reload',()=>{const f=fixture();readyTalk(f);const reload=fixture(Save.snapshot(f.state));assert.equal(reload.p.getQuest(q('talk')).status,'READY_TO_TURN_IN');assert.deepEqual(reload.p.getQuestState(),f.p.getQuestState());assert.equal(reload.state.gold,f.state.gold)});
test('partial Kill persists and new runtime rejects old evidence',()=>{const f=fixture();accepted(f,'kill');const k=f.kill(f.actor()),reload=fixture(Save.snapshot(f.state));assert.equal(reload.p.getQuest(q('kill')).objectives[0].progress,1);assert.equal(reload.p.observeQuestKill(k.result.evidence).code,'INVALID_QUEST_EVIDENCE');reload.kill(reload.actor());assert.equal(reload.p.getQuest(q('kill')).objectives[0].progress,2)});
test('Collect reload derives actual inventory, ignores stale saved READY/count',()=>{const f=fixture();accepted(f,'collect');f.p.addStack('herb',3);f.p.removeStack('herb',1);const raw=Save.snapshot(f.state);raw.questState.entries[q('collect')].progress['collect-herb']=3;const restored=fixture(raw);assert.equal(restored.p.getQuest(q('collect')).status,'ACTIVE');assert.equal(restored.p.getQuest(q('collect')).objectives[0].progress,2);assert.deepEqual(restored.p.getQuestState().entries[q('collect')].progress,{})});
test('completed identity/prerequisite chain survives reload without rewards',()=>{const f=fixture();readyTalk(f);assert(f.p.turnInQuest(q('talk')).ok);assert.equal(f.p.getQuest(q('chain')).status,'AVAILABLE');const restored=fixture(Save.snapshot(f.state));assert.equal(restored.p.getQuest(q('talk')).status,'COMPLETED');assert.equal(restored.p.getQuest(q('chain')).status,'AVAILABLE');assert.equal(restored.state.gold,f.state.gold);assert.deepEqual(restored.p.getInventory(),f.p.getInventory());accepted(restored,'chain');restored.talk();assert(restored.p.turnInQuest(q('chain')).ok)});
test('prepared ticket does not serialize and foreign recreated runtime rejects',()=>{const f=fixture();readyTalk(f);const t=f.p.prepareQuestTurnIn(q('talk')),raw=Save.snapshot(f.state);assert(!JSON.stringify(raw).includes('QUEST_TURN_IN'));const restored=fixture(raw);rejected(restored,()=>restored.p.commitQuestTurnIn(t),'INVALID_QUEST_TICKET')});
test('unknown stored quest/objective safely archived, never granted or activated',()=>{const f=fixture({questState:{entries:{unknown:{status:'COMPLETED',progress:{k:999}},[q('talk')]:{status:'ACTIVE',progress:{fake:100,'talk-registrar':NaN}}}}});assert(!f.p.getQuestState().entries.unknown);assert(f.p.getQuestState().history.unknown);assert.equal(f.p.getQuest(q('talk')).objectives[0].progress,0);assert.equal(f.state.gold,50)});
test('player death/respawn/travel invalidations retain durable progress',()=>{const f=fixture();accepted(f,'kill');accepted(f,'talk');f.talk();f.kill(f.actor());const durable=f.p.getQuestState();f.p.setCurrentHP(0);f.p.invalidatePreparedActions();f.p.setCurrentHP(f.p.snapshot().maxHP);for(let i=0;i<8;i++){f.state.zone=i%2;f.p.invalidatePreparedActions()}assert.deepEqual(f.p.getQuestState(),durable);f.kill(f.actor('leafmane-fox','spawn-2'));assert.equal(f.p.getQuest(q('kill')).objectives[0].progress,2)});
for(const cls of [0,12])test('twenty save/load cycles stable Quest ownership capacity Stats class '+cls,()=>{let f=fixture({cls});readyTalk(f);f.p.turnInQuest(q('talk'));accepted(f,'kill');f.kill(f.actor());const expected={q:f.p.getQuestState(),inv:f.p.getInventory(),eq:f.p.getEquipmentSlots(),stats:f.p.getDerivedStats(),cap:f.p.getInventoryCapacityState(),gold:f.state.gold};for(let i=0;i<20;i++){f=fixture(Save.snapshot(f.state));assert.deepEqual({q:f.p.getQuestState(),inv:f.p.getInventory(),eq:f.p.getEquipmentSlots(),stats:f.p.getDerivedStats(),cap:f.p.getInventoryCapacityState(),gold:f.state.gold},expected)}});
test('v5 remains intentional, pre-v5 starts no new fabricated Quest progress',()=>{const f=fixture({saveVersion:4,quest:{id:2,progress:1}});assert.equal(Save.version,5);assert.equal(f.state.quest.id,2);assert.deepEqual(f.p.getQuestState().entries,{})});
test('future save still rejects before Quest runtime',()=>assert.throws(()=>Save.normalize({name:'Future',saveVersion:6,questState:{}}),e=>e.code==='UNSUPPORTED_SAVE_VERSION'));
test('no quest RNG hidden time DOM inventory counters or damage formula',()=>{for(const file of ['quest-definitions.js','quest-state.js','quest-runtime.js','quest-evidence.js']){const source=fs.readFileSync(require.resolve('../'+file),'utf8');for(const forbidden of ['Math.random','Date.now','performance.now','document.','localStorage','finalDamage'])assert(!source.includes(forbidden),file+':'+forbidden)}});
test('Lifecycle Loot Box Capacity Save Equipment and visual cores byte unchanged from parent',()=>{const parent='a946ba4e51e20b45aaf83aa85fb08e49755f6fc6';for(const file of ['monster-lifecycle.js','monster-loot-runtime.js','monster-rewards.js','monster-box.js','monster-box-runtime.js','inventory-capacity.js','save-state.js','equipment-slots.js','item-equipment.js','item-inventory.js','stats.js','progression.js','combat-resolution.js','combat-runtime.js','action-item.js','action-item-runtime.js','action-loadout.js','style.css'])assert.equal(fs.readFileSync(require.resolve('../'+file),'utf8').replace(/\r\n/g,'\n'),child.execFileSync('git',['show',parent+':'+file]).toString().replace(/\r\n/g,'\n'));assert(!child.execFileSync('git',['diff','--name-only',parent]).toString().split('\n').some(p=>/^(assets|world|authoring|RO3 Ref)\//.test(p)))});

test('unknown dangerous stored ID is archived as own data without prototype mutation',()=>{const raw=JSON.parse('{"entries":{"__proto__":{"status":"ACTIVE","progress":{}},"constructor":{"status":"COMPLETED"}}}'),s=Q.normalize(raw,registry);assert(Object.hasOwn(s.history,'__proto__'));assert.equal(Object.getPrototypeOf(s.history),Object.prototype);assert.deepEqual(Q.normalize(s,registry),s);assert.deepEqual(s.entries,{})});
test('throwing evidence verifier rejects without progress or mutation',()=>{const f=fixture({}, {isQuestTalkEvidence(){throw Error('verifier fixture')}});accepted(f,'talk');rejected(f,()=>f.p.observeQuestTalk({type:'NPC_INTERACTED',targetId:'guild-registrar'}),'INVALID_QUEST_EVIDENCE')});
test('throwing turn-in target verifier safely rejects with no rewards',()=>{const f=fixture();readyTalk(f);const state=f.p.getQuestState(),owner={getInventory:f.p.getInventory,getInventoryRevision:f.p.getInventoryRevision,getEquipment:f.p.getEquipmentSlots,getCurrentHP:()=>10,preflight:()=>{throw Error('must not reach rewards')},rewardIdentity:()=>''};const runtime=window.AstraeonQuestRuntime.create(owner,{raw:state,isTalkEvidence(){throw Error('verifier fixture')}});assert.equal(runtime.prepare(q('talk'),{interaction:{}}).code,'WRONG_TURN_IN_TARGET');assert.deepEqual(runtime.getState(),state)});
test('weighted net Collect debit frees authoritative weight for reward',()=>{const catalog={getDefinition:id=>{const d=Items.getDefinition(id);return d?{...d,weight:id==='herb'?2:id==='potion'?1:0}:null}},inv=I.addStack(I.normalize(),'herb',3,catalog).inventory,f=fixture({itemInventory:inv},{itemCatalog:catalog,getCapacityPolicy:()=>({mode:'bounded',slotLimit:1,weightLimit:5,overLimitPolicy:'no-worse'})});accepted(f,'collect');f.talk();assert.equal(f.p.getInventoryCapacityState().totalWeight,6);const t=f.p.prepareQuestTurnIn(q('collect'));assert(t.ok);assert.equal(t.preflight.capacity.delta.weight,-5);assert(f.p.commitQuestTurnIn(t).ok);assert.equal(f.p.getInventoryCapacityState().totalWeight,1)});
test('non-consuming Collect with overweight reward rejects before EXP gold items',()=>{const d=definition('collect');d.objectives[0].consumeOnTurnIn=false;d.rewards.baseExp=2;d.rewards.jobExp=2;const catalog={getDefinition:id=>{const d=Items.getDefinition(id);return d?{...d,weight:id==='herb'?2:id==='potion'?1:0}:null}},f=custom(d,{}, {itemCatalog:catalog,getCapacityPolicy:()=>({mode:'bounded',slotLimit:2,weightLimit:6,overLimitPolicy:'no-worse'})});f.p.addStack('herb',3);accepted(f,'collect');f.talk();rejected(f,()=>f.p.turnInQuest(q('collect')),'WEIGHT_LIMIT_EXCEEDED')});
test('maxStack rejection preserves Collect sources and serial separately from capacity',()=>{const f=fixture();f.p.addStack('herb',3);f.p.addStack('potion',Items.getDefinition('potion').maxStack);accepted(f,'collect');f.talk();rejected(f,()=>f.p.turnInQuest(q('collect')),'STACK_OVERFLOW');assert.equal(f.p.getQuantity('herb'),3)});
test('harness and normal boot import shared Quest authority; no fake progress mutation',()=>{const harness=fs.readFileSync(require.resolve('../tools/quest-harness.js'),'utf8'),page=fs.readFileSync(require.resolve('../tools/quest.html'),'utf8'),game=fs.readFileSync(require.resolve('../game.js'),'utf8');assert(harness.includes('astraeon-quest-dev-v1'));assert(harness.includes('AstraeonCombatResolution.applyCombatResult'));assert(!harness.includes("state.questState="));for(const n of ['quest-definitions','quest-state','quest-evidence','quest-runtime'])assert(page.includes(n+'.js?v=95'));assert(game.includes("get('dev')==='1'"));assert(game.includes('questDeaths.deliver(m,death)'));assert(game.includes('questDeaths.deliver(m,output)'));assert(game.includes('player.observeQuestTalk(evidence)'))});

test('actual harness buttons use supported Combat HP API, new life and private recreated tickets',()=>{
 const previous={document:global.document,Option:global.Option,localStorage:global.localStorage},elements=new Map(),stored=new Map();
 const element=id=>{if(!elements.has(id))elements.set(id,{value:({quest:q('talk'),item:'herb',count:'3',slots:'60'})[id]||'',textContent:'',add(){}});return elements.get(id)};
 global.document={getElementById:element};global.Option=class{};global.localStorage={getItem:key=>stored.get(key)||null,setItem:(key,value)=>stored.set(key,value)};
 try{
  require('../tools/quest-harness.js');const click=id=>element(id).onclick(),result=()=>JSON.parse(element('result').textContent),snapshot=()=>window.AstraeonQuestHarness.snapshot();
  for(const id of ['accept','talk','prepare','commit'])click(id);assert(result().ok);click('duplicate');assert.equal(result().code,'ALREADY_COMMITTED');
  element('quest').value=q('kill');for(const id of ['accept','spawn','attack'])click(id);assert.equal(snapshot().objectives[1].objectives[0].progress,1);assert.equal(snapshot().actor.hp,0);
  for(const id of ['respawn','attack'])click(id);assert.equal(snapshot().actor.lifeGeneration,2);assert.equal(snapshot().objectives[1].objectives[0].progress,2);
  for(const id of ['talk','prepare','save'])click(id);assert(snapshot().ticket.ok);const saved=snapshot().save;click('reload');click('commit');assert.equal(result().code,'INVALID_QUEST_TICKET');assert.deepEqual(snapshot().save,saved);assert.equal(stored.has('astraeon-iso-v1'),false);
 }finally{for(const [key,value] of Object.entries(previous)){if(value===undefined)delete global[key];else global[key]=value}}
});

test('valid prototype-named quest identity reads only owned durable entries and prerequisites',()=>{
 const definitions=clone(D.definitions);definitions[0].id='toString';definitions[4].prerequisites=['toString'];const f=fixture({}, {questDefinitions:definitions});
 assert.equal(f.p.getQuest('toString').status,'AVAILABLE');assert.equal(f.p.getQuest(q('chain')).status,'LOCKED');f.talk();assert.deepEqual(f.p.getQuestState().entries,{});
 assert(f.p.acceptQuest('toString').ok);assert.equal(f.p.getQuest('toString').objectives[0].progress,0);f.talk();assert(f.p.turnInQuest('toString').ok);assert.equal(f.p.getQuest(q('chain')).status,'AVAILABLE');
 const restored=fixture(Save.snapshot(f.state),{questDefinitions:definitions});assert.equal(restored.p.getQuest('toString').status,'COMPLETED');assert.deepEqual(restored.p.getQuestState(),f.p.getQuestState());
});
test('prototype-named objective identity has explicit capped owned progress',()=>{const d=definition('talk');d.objectives[0].id='valueOf';const f=custom(d);accepted(f,'talk');assert.equal(f.p.getQuest(q('talk')).objectives[0].progress,0);f.talk();f.talk();assert.equal(f.p.getQuest(q('talk')).objectives[0].progress,1);assert(Object.hasOwn(f.p.getQuestState().entries[q('talk')].progress,'valueOf'))});
test('unknown prototype-named or coercing transition inputs reject without throwing',()=>{for(const from of ['toString','valueOf','constructor',null,{}, {toString(){throw Error('must not coerce')}}])assert.equal(Q.canTransition(from,'ACTIVE'),false);assert.equal(Q.canTransition('AVAILABLE',{}),false)});
