'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');
const M=require('../character-motion-template.js'),A=require('../character-assembly.js');
const read=p=>JSON.parse(fs.readFileSync(p));
const t=read('authoring/characters/motion-templates/ro1-swordsman-male/motion-template.json'),p=read('authoring/characters/appearance/swordsman-male-painted/appearance-pack.json'),r=read('authoring/characters/motion-templates/ro1-swordsman-male/rendered-reference.json'),build=read('authoring/characters/builds/swordsman-male/build-manifest.json');
const c=A.compileAssembly(t,p),clone=o=>structuredClone(o);
test('rendered RO production proof validates independently of missing raw ACT files',()=>{assert.deepEqual(M.validateMotionTemplate(t),[]);assert.deepEqual(A.validateAppearancePack(p,t),[]);assert.equal(t.provenance.rawACTInspected,false);assert.equal(t.provenance.exactACTTiming,false);assert.equal(t.provenance.kind,'RO1_DERIVED')});
test('render provenance manifest identity is deterministic and source frames exist',()=>{
 assert.equal(t.provenance.referenceManifestSHA256,crypto.createHash('sha256').update(fs.readFileSync('authoring/characters/motion-templates/ro1-swordsman-male/rendered-reference.json')).digest('hex'));
 for(const a of Object.values(t.actions))for(const d of M.DIRECTIONS)for(const k of a.directions[d].referenceKeys){const rec=r.records.find(x=>x.actionId===k.source.actionId&&x.direction===d);assert.ok(rec);assert.equal(k.source.sourceImageSHA256,rec.sha256);assert.ok(k.source.frameIndex<rec.frameCount);assert.equal(k.evidenceClass,'RENDERED_REFERENCE')}
});
test('one-handed sword variant follows inspected Swordman mapping',()=>{assert.equal(r.selectedAttack.family,80);assert.equal(r.selectedAttack.weaponView,2);assert.equal(r.attackMappingSources.length,2);assert.ok(r.records.some(x=>x.actionId===40));assert.ok(r.records.some(x=>x.actionId===88));assert.ok(r.records.some(x=>x.actionId===96))});
for(const [action,count,keys,duration]of [['Idle',9,2,3000],['Walk',16,8,600],['BasicAttack',16,10,450]])test(action+' has all eight registered authored directions and classified duration-preserving refinements',()=>{
 assert.deepEqual(Object.keys(t.actions[action].directions),M.DIRECTIONS);
 for(const d of M.DIRECTIONS){const s=t.actions[action].directions[d];assert.equal(s.frames.length,count);assert.equal(s.referenceKeys.length,keys);assert.equal(s.totalDurationMs,duration);assert.equal(s.frames.reduce((n,f)=>n+f.durationMs,0),duration);assert.equal(s.referenceKeys.reduce((n,f)=>n+f.durationMs,0),duration);assert.deepEqual(s.frames.filter(f=>f.role==='referenceKey').map(f=>f.id),s.referenceKeys.map(f=>f.id));for(const f of s.frames){assert.deepEqual(f.root,t.registration.root);assert.deepEqual(f.anchors.root,t.registration.root);assert.ok(f.evidenceClass=== (f.role==='referenceKey'?'RENDERED_REFERENCE':'ASTRAEON_INBETWEEN'));assert.ok(M.ANCHORS.every(n=>M.validTransform(f.anchors[n])))}}
});
test('Idle keys repeat the single observed stance instead of inventing RO breathing frames',()=>{for(const d of M.DIRECTIONS){const keys=t.actions.Idle.directions[d].referenceKeys;assert.ok(keys.every(k=>k.source.frameIndex===0));assert.equal(r.records.find(x=>x.action==='idle'&&x.direction===d).uniqueRenderedFrames,1)}});
test('attack contact and recovery are presentation-only markers at deterministic times',()=>{for(const d of M.DIRECTIONS){let time=0;const events={};for(const f of t.actions.BasicAttack.directions[d].frames){for(const e of f.events){assert.equal(e.authority,'presentation');events[e.name]=time}time+=f.durationMs}assert.deepEqual(events,{attackAnticipation:0,attackContact:170,attackRecovery:250});assert.equal(c.motion.sample('BasicAttack',d,1000).frameIndex,15)}});
for(const [name,edit,pattern]of [
 ['unclassified rendered key',t=>delete t.actions.Walk.directions.S.frames[0].evidenceClass,/classification/],
 ['exact ACT timing claimed from renderer',t=>t.provenance.exactACTTiming=true,/exact ACT timing/],
 ['in-between claims RO key evidence',t=>t.actions.Walk.directions.S.frames[1].evidenceClass='RENDERED_REFERENCE',/ASTRAEON_INBETWEEN/],
 ['unknown evidence kind',t=>t.actions.Walk.directions.S.frames[0].source.kind='GUESSED',/source-derived/],
 ['source URL missing',t=>delete t.actions.Walk.directions.S.frames[0].source.url,/source-derived/],
 ['invalid direction source',t=>t.actions.Walk.directions.S.frames[0].source.direction='N',/source-derived/],
 ['action expansion without approval',t=>t.actions.Run=clone(t.actions.Walk),/expansion/]
])test('provenance rejects '+name,()=>{const bad=clone(t);edit(bad);assert.throws(()=>M.compileMotionTemplate(bad),pattern)});
test('every atlas file exists and has its compiled identity; no RO files are runtime dependencies',()=>{for(const [id,a]of Object.entries(p.atlases)){assert.ok(fs.existsSync(a.file));assert.equal(crypto.createHash('sha256').update(fs.readFileSync(a.file)).digest('hex'),build.runtimeAtlases[id]);assert.ok(!/private-ro|\.act$|\.spr$/.test(a.file))}assert.equal(p.mirroring,'none');assert.equal(t.registration.mirroring,'none')});
for(const [slot,id]of [['Hair','hair-b'],['MainHand','weapon-b'],['OffHand','offhand'],['Headgear','headgear'],['Garment',null]])test(slot+' changes only its own independent sources on every painted pose',()=>{
 for(const [action,a]of Object.entries(t.actions))for(const d of M.DIRECTIONS)for(let frameIndex=0;frameIndex<a.directions[d].frames.length;frameIndex++){const before=c.sample(action,d,123,{frameIndex}),after=c.sample(action,d,123,{frameIndex,appearance:{[slot]:id}});assert.strictEqual(after.frame,before.frame);assert.equal(after.elapsedMs,before.elapsedMs);assert.deepEqual(after.layers.filter(l=>l.slot!==slot),before.layers.filter(l=>l.slot!==slot));assert.notDeepEqual(after.layers.filter(l=>l.slot===slot),before.layers.filter(l=>l.slot===slot))}
});
test('appearance swap keeps Walk SW frame5, clock and external gameplay state',()=>{const time=t.actions.Walk.directions.SW.frames.slice(0,5).reduce((n,f)=>n+f.durationMs,0),controller=A.createController(c,{action:'Walk',direction:'SW',elapsedMs:time});const external=Object.freeze({position:{x:2,y:7},target:'npc',collision:'capsule',combatPhase:'external'}),snapshot=JSON.stringify(external);for(const patch of [{Hair:'hair-b'},{MainHand:'weapon-b'},{OffHand:'offhand'},{Headgear:'headgear'},{Garment:null}]){controller.setAppearance(patch);assert.equal(controller.elapsedMs,time);assert.equal(controller.sample().frameIndex,5);assert.equal(controller.sample().direction,'SW');assert.equal(JSON.stringify(external),snapshot)}});
test('appearance cannot override production timing or create independent body resets',()=>{const bad=clone(p);bad.timing={Walk:3000};assert.throws(()=>A.compileAssembly(t,bad),/override motion/)});
test('painted hair and garment use reduced phase samples; equipment uses held direction views',()=>{for(const id of ['hair-a','hair-b','garment'])assert.equal(p.parts[id].mode,'PHASE_SYNC');for(const id of ['weapon-a','weapon-b','offhand','headgear'])assert.equal(p.parts[id].mode,'ANCHOR_HOLD');assert.equal(p.parts['body-swordsman'].mode,'BODY_SYNC');assert.equal(c.sample('Walk','S',0).layers.find(l=>l.layer==='Body').sampleIndex,0);assert.equal(c.sample('Walk','S',300).layers.find(l=>l.layer==='HairFront').sampleIndex,2)});
test('rear garment covers back torso; loaded frame and direction overrides resolve independently',()=>{const rear=c.sample('Walk','N',0).drawOrder;assert.ok(rear.indexOf('GarmentBack')>rear.indexOf('Body'));assert.ok(rear.indexOf('MainHand')<rear.indexOf('Body'));const loaded=c.sample('BasicAttack','S',0).drawOrder;assert.ok(loaded.indexOf('MainHand')<loaded.indexOf('Body'));assert.ok(c.sample('BasicAttack','S',170).drawOrder.indexOf('MainHand')>c.sample('BasicAttack','S',170).drawOrder.indexOf('Body'))});
test('owner approval cannot be inferred from structural tests',()=>{assert.equal(t.status,'REQUIRES_OWNER_VISUAL_REVIEW');assert.equal(p.status,'REQUIRES_OWNER_VISUAL_REVIEW');assert.equal(build.ownerVisualApproval,'PENDING')});
test('east profile cape stays behind the visible face and torso',()=>{for(const action of Object.keys(t.actions)){const s=c.sample(action,'E',180);assert.ok(s.drawOrder.indexOf('GarmentBack')<s.drawOrder.indexOf('Body'))}});
test('rear attack keeps cape over torso through loaded keys and strike frames',()=>{for(const d of ['NW','N','NE'])for(let i=0;i<16;i++){const s=c.sample('BasicAttack',d,0,{frameIndex:i});assert.ok(s.drawOrder.indexOf('GarmentBack')>s.drawOrder.indexOf('Body'))}});
test('rear contact sword crosses in front of cape while loaded hand stays behind body',()=>{for(const d of ['NW','N','NE']){const loaded=c.sample('BasicAttack',d,0),strike=c.sample('BasicAttack',d,170);assert.ok(loaded.drawOrder.indexOf('MainHand')<loaded.drawOrder.indexOf('Body'));assert.ok(strike.drawOrder.indexOf('MainHand')>strike.drawOrder.indexOf('GarmentBack'))}});
test('second dummy Body Hair and Weapon pack reuses the actual RO template without class branches',()=>{const pack=read('authoring/characters/appearance/ro1-reuse-dummy/appearance-pack.json'),other=A.compileAssembly(t,pack);assert.equal(pack.status,'DEV_ONLY');for(const action of Object.keys(t.actions))for(const d of M.DIRECTIONS){const a=c.sample(action,d,180),b=other.sample(action,d,180);assert.equal(a.motionTemplateId,b.motionTemplateId);assert.deepEqual(a.frame,b.frame);assert.equal(a.totalDurationMs,b.totalDurationMs);assert.notEqual(a.layers.find(l=>l.layer==='Body').atlasId,b.layers.find(l=>l.layer==='Body').atlasId);assert.notEqual(a.appearance.Hair,b.appearance.Hair);assert.notEqual(a.appearance.MainHand,b.appearance.MainHand)}for(const file of ['character-motion-template.js','character-assembly.js'])assert.ok(!/if\s*\([^)]*class/.test(fs.readFileSync(file,'utf8')))});
