"""Actual NPC sessions, Shop and exact Storage moves; disposable two-class saves."""
import argparse,json,os,tempfile
from pathlib import Path
from playwright.sync_api import sync_playwright
import town_service_navigation as nav
ap=argparse.ArgumentParser();ap.add_argument('--url',default='http://127.0.0.1:8011');ap.add_argument('--browser',default=os.environ.get('ASTRAEON_BROWSER',r'C:\Program Files\Google\Chrome\Application\chrome.exe'));ap.add_argument('--output',type=Path,default=Path(tempfile.gettempdir())/'astraeon-town-services-browser');ap.add_argument('--classes',default='0,12');args=ap.parse_args();args.output.mkdir(parents=True,exist_ok=True);nav.evidence_dir=args.output
checks,errors,http_errors,blocked=[],[],[],[];report={};page=None
def qa():return nav.qa(page)
def snap():return nav.snap(page)
def svc(code):return page.evaluate('()=>{const s=AstraeonTownServicesDev,d=AstraeonProgressionDev,q=AstraeonQuestDev;'+code+'}')
def passed(name,evidence=None):checks.append({'name':name,'evidence':evidence});print('PASS',name,flush=True);checkpoint()
def checkpoint():(args.output/'progress.json').write_text(json.dumps({'checks':checks,'errors':errors,'httpErrors':http_errors,'expectedRejections':blocked,'navigation':nav.observations},indent=2),encoding='utf-8')
def reject(fn,code):
 before=snap();result=fn();assert result['code']==code,(result,code);assert snap()==before;blocked.append(result);return result
def interact(target):
 print('WALK / INTERACT',target,flush=True);nav.npc_interaction(page,target)
 if target in ['merchant','housing-keeper']:assert qa()['townServices']['session']['valid'] and qa()['townServices']['session']['serviceId']==('town-merchant' if target=='merchant' else 'storage-proof')
def nearby(target):
 nav.close(page);page.keyboard.press('e');page.wait_for_selector('#modal:not([hidden])');assert qa()['townServices']['session']['serviceId']==('town-merchant' if target=='merchant' else 'storage-proof') and qa()['townServices']['session']['valid']
def click_storage(operation,item):page.locator('[data-storage-operation="'+operation+'"][data-storage-item="'+item+'"]').click()
def click_instance(operation,id):page.locator('[data-storage-operation="'+operation+'"][data-storage-instance="'+id+'"]').click()
try:
 with sync_playwright() as pw:
  browser=pw.chromium.launch(executable_path=args.browser,headless=True,args=['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-background-timer-throttling','--disable-renderer-backgrounding','--disable-backgrounding-occluded-windows'])
  for cls in args.classes.split(','):
   context=browser.new_context(viewport={'width':1280,'height':900});page=context.new_page();page.set_default_timeout(180000)
   page.on('pageerror',lambda e:errors.append(str(e)));page.on('console',lambda m:errors.append(m.text) if m.type=='error' else None);page.on('response',lambda r:http_errors.append(f'{r.status} {r.url}') if r.status>=400 else None)
   page.goto(args.url+'/?dev=1&qa=1',wait_until='load');page.wait_for_selector('#create');page.locator('#newname').fill('Services '+cls);page.locator('#newclass').select_option(cls);page.locator('#create').click();page.wait_for_selector('#world');nav.pause(page)
   assert snap()['saveVersion']==5 and not snap()['storageState']['stacks'];assert qa()['townServices']['session'] is None;passed('normal game boots with empty optional Storage and canonical five-slot gear',{'class':cls})
   reject(lambda:svc('return s.buy("herb")'),'SERVICE_ACCESS_REQUIRED');passed('remote menu/inspection grants no merchant authority',{'class':cls})
   interact('guild-registrar');page.locator('[data-quest-accept="quest-proof-collect"]').click();assert svc('return q.inspect("quest-proof-collect").status')=='READY_TO_TURN_IN';passed('actual registrar explicitly accepts Collect using carried Herbs',{'class':cls})
   interact('merchant');before=snap();page.locator('[data-buy="herb:5"]').click();assert snap()['gold']==before['gold']-5 and snap()['itemInventory']['stacks']['herb']==before['itemInventory']['stacks']['herb']+1
   page.locator('[data-sell="herb:2"]').click();assert snap()['gold']==before['gold']-3 and snap()['itemInventory']['nextItemSerial']==before['itemInventory']['nextItemSerial'];passed('actual Merchant UI buy/sell stack uses authored prices without serial allocation',{'class':cls})
   before=snap();prepared=svc('window.serviceTicket=s.prepareTownService({operation:"buy",itemId:"astral-blade",count:1});return window.serviceTicket');assert prepared['ok'] and snap()==before
   gear=svc('return s.commitTownService(window.serviceTicket)');assert gear['ok'];id=gear['instanceRewards'][0]['instanceId'];assert snap()['itemInventory']['nextItemSerial']==before['itemInventory']['nextItemSerial']+1 and id not in snap()['equippedItems'].values();reject(lambda:svc('return s.commitTownService(window.serviceTicket)'),'SERVICE_TICKET_USED');passed('owned live Shop ticket grants canonical unique instance once without auto-equip',{'class':cls,'instance':id})
   base=svc('return d.getDerivedStats()');cap=qa()['inventoryCapacity'];nav.close(page);page.locator('[data-open="inventory"]').click();page.locator('[data-equip-instance="'+id+'"]').click();assert svc('return d.getDerivedStats().physicalATK')==base['physicalATK']+6 and qa()['inventoryCapacity']==cap;passed('bought gear equips normally through Bag and changes Stats with zero capacity drift',{'class':cls})
   nearby('merchant');reject(lambda:svc('return s.sellItemInstance('+json.dumps(id)+')'),'ITEM_EQUIPPED');passed('equipped sale rejects without silently unequipping or changing ownership',{'class':cls})
   page.evaluate('n=>AstraeonInventoryCapacityDev.setTestPolicy({mode:"bounded",slotLimit:n,weightLimit:1000,overLimitPolicy:"no-worse"})',cap['occupiedSlots']);nearby('merchant');reject(lambda:svc('return s.buy("astral-blade")'),'SLOT_LIMIT_EXCEEDED');page.evaluate('AstraeonInventoryCapacityDev.restorePolicy()');nearby('merchant');passed('Shop capacity failure preserves gold ownership equipment and serial',{'class':cls})
   assert svc('return d.unequip("mainHand")')['ok'];before=snap();page.locator('[data-sell-instance="'+id+'"]').click();assert id not in snap()['itemInventory']['instances'] and snap()['gold']==before['gold']+4 and snap()['itemInventory']['nextItemSerial']==before['itemInventory']['nextItemSerial'];page.locator('[data-buy="astral-blade:20"]').click();ids=set(snap()['itemInventory']['instances'])-set(before['itemInventory']['instances']);assert len(ids)==1;id=ids.pop();passed('explicit unequip permits exact-instance sale; replacement purchase receives a new ID',{'class':cls,'replacement':id})
   interact('guild-registrar');ticket=svc('window.questServiceTicket=q.prepare("quest-proof-collect");return window.questServiceTicket');assert ticket['ok'];passed('actual registrar prepares net Quest turn-in before Storage movement',{'class':cls})
   interact('housing-keeper');assert page.locator('[data-storage-operation]').count()>0;before=snap();click_storage('depositStack','herb');assert snap()['itemInventory']['stacks']['herb']==2 and snap()['storageState']['stacks']['herb']==1 and svc('return q.inspect("quest-proof-collect").status')=='ACTIVE';reject(lambda:svc('return q.commit(window.questServiceTicket)'),'STALE_QUEST_TICKET');passed('real Storage deposit reduces carried Collect and invalidates prepared Quest ticket',{'class':cls})
   click_storage('withdrawStack','herb');assert snap()['itemInventory']['stacks']['herb']==3 and svc('return q.inspect("quest-proof-collect").status')=='READY_TO_TURN_IN';passed('actual Storage withdrawal restores Collect readiness without Quest item ledger',{'class':cls})
   assert svc('return d.equip('+json.dumps(id)+',"mainHand")')['ok'];reject(lambda:svc('return s.depositItemInstance('+json.dumps(id)+')'),'ITEM_EQUIPPED');assert svc('return d.unequip("mainHand")')['ok'];stored=snap()['itemInventory']['instances'][id];n=snap()['itemInventory']['nextItemSerial'];click_instance('depositItemInstance',id);assert id not in snap()['itemInventory']['instances'] and snap()['storageState']['instances'][id]==stored;assert snap()['itemInventory']['nextItemSerial']==n;passed('Storage moves unequipped exact instance and metadata without allocation or effects',{'class':cls,'instance':id})
   cap=qa()['inventoryCapacity'];page.evaluate('n=>AstraeonInventoryCapacityDev.setTestPolicy({mode:"bounded",slotLimit:n,weightLimit:1000,overLimitPolicy:"no-worse"})',cap['occupiedSlots']);nearby('housing-keeper');reject(lambda:svc('return s.withdrawItemInstance('+json.dumps(id)+')'),'SLOT_LIMIT_EXCEEDED');page.evaluate('AstraeonInventoryCapacityDev.restorePolicy()');nearby('housing-keeper');click_instance('withdrawItemInstance',id);assert snap()['itemInventory']['instances'][id]==stored and snap()['itemInventory']['nextItemSerial']==n;passed('withdrawal capacity failure changes neither container; successful retry retains same ID',{'class':cls})
   click_storage('depositStack','potion');click_storage('depositStack','potion');svc('d.setCurrentHP(1)');reject(lambda:svc('return d.useConsumable("potion")'),'INSUFFICIENT_ITEMS');click_storage('withdrawStack','potion');assert svc('return d.useConsumable("potion")')['ok'];passed('stored Potion cannot execute Action Item; withdrawn carried Potion can',{'class':cls})
   click_storage('depositStack','herb');click_instance('depositItemInstance',id);svc('d.save()');saved=snap();page.reload(wait_until='load');page.wait_for_selector('#world');nav.pause(page);assert snap()['storageState']==saved['storageState'] and snap()['itemInventory']==saved['itemInventory'];assert qa()['townServices']['session'] is None;assert svc('return q.inspect("quest-proof-collect").objectives[0].progress')==2;passed('actual save/reload preserves both containers identity serial and derived Collect; sessions discarded',{'class':cls})
   page.evaluate('navigator.serviceWorker.ready');page.wait_for_function('navigator.serviceWorker.controller');cached=page.evaluate('async()=>{const name=(await caches.keys()).find(k=>k.startsWith("astraeon-static-v")),cache=await caches.open(name);return {name,urls:(await cache.keys()).map(r=>r.url)}}');version=cached['name'].rsplit('v',1)[1];assert all(any(url.endswith('/'+n+'.js?v='+version) for url in cached['urls']) for n in ['town-service-definitions','storage-state','town-service-runtime']);context.set_offline(True);page.reload(wait_until='load');page.wait_for_selector('#world');nav.pause(page);assert snap()['storageState']==saved['storageState'] and snap()['itemInventory']==saved['itemInventory'] and qa()['townServices']['session'] is None;context.set_offline(False);passed('new service modules and both durable containers resume offline without replay or access authority',{'class':cls,'cache':cached['name']})
   nav.travel(page,2);nav.pause(page);assert snap()['storageState']==saved['storageState'] and snap()['itemInventory']==saved['itemInventory'];passed('ordinary field travel preserves both containers and invalidates remote service access',{'class':cls})
   durable=snap()['questState'];svc('d.setCurrentHP(1)');nav.close(page);s=qa();actor=min((e['lifecycle'] for e in s['enemies'] if e['hp']>0),key=lambda m:(m['position']['x']-s['save']['x'])**2+(m['position']['y']-s['save']['y'])**2);at=actor['position'];position=s['player']['position'];distance=((at['x']-position['x'])**2+(at['y']-position['y'])**2)**.5;goal={'x':at['x']+(position['x']-at['x'])/distance*5.5,'y':at['y']+(position['y']-at['y'])/distance*5.5}
   page.evaluate('''()=>{window.servicesDeathEvidence=null;window.servicesDeathObserver=()=>{const s=AstraeonQA.snapshot();if(s.save.currentHP===0){window.servicesDeathEvidence={save:s.save,incoming:s.incomingCombat.at(-1)};removeEventListener('astraeon-frame',window.servicesDeathObserver)}};addEventListener('astraeon-frame',window.servicesDeathObserver)}''')
   try:
    page.mouse.click(*nav.field_point(page,goal));page.wait_for_function('window.servicesDeathEvidence?.save.currentHP===0',timeout=90000);death=page.evaluate('window.servicesDeathEvidence');assert death['incoming']['hp']['killed'];assert death['save']['storageState']==saved['storageState'];page.wait_for_function('AstraeonQA.snapshot().save.zone===0&&AstraeonQA.snapshot().save.currentHP>0',timeout=30000);nav.pause(page);assert snap()['storageState']==saved['storageState'] and snap()['itemInventory']==saved['itemInventory'] and snap()['questState']==durable;assert qa()['townServices']['session'] is None;passed('real enemy-caused death and town respawn retain exact Storage carried gear serial and Quest progress',{'class':cls,'attackId':death['incoming']['attackId']})
   finally:page.evaluate("removeEventListener('astraeon-frame',window.servicesDeathObserver);delete window.servicesDeathObserver")
   context.close()
  context=browser.new_context();page=context.new_page();page.set_default_timeout(180000);page.on('pageerror',lambda e:errors.append(str(e)));page.on('console',lambda m:errors.append(m.text) if m.type=='error' else None);page.on('response',lambda r:http_errors.append(f'{r.status} {r.url}') if r.status>=400 else None);page.goto(args.url+'/tools/town-services.html');page.wait_for_selector('#inspection');page.locator('#merchant').click();page.locator('#buy').click();assert page.evaluate('AstraeonTownServicesHarness.snapshot().gold')==95;page.locator('#storage').click();page.locator('#depositStack').click();assert page.evaluate('AstraeonTownServicesHarness.snapshot().services.storage.stacks.herb')==1;page.locator('#operation').select_option('withdrawStack');page.locator('#prepare').click();page.locator('#commit').click();page.locator('#duplicate').click();assert page.evaluate('AstraeonTownServicesHarness.snapshot().lastResult.code')=='SERVICE_TICKET_USED';passed('isolated harness buttons use shared interaction and transaction authorities with duplicate protection');context.close()
  context=browser.new_context();page=context.new_page();page.set_default_timeout(180000);page.on('pageerror',lambda e:errors.append(str(e)));page.on('console',lambda m:errors.append(m.text) if m.type=='error' else None);page.on('response',lambda r:http_errors.append(f'{r.status} {r.url}') if r.status>=400 else None);page.goto(args.url+'/');page.wait_for_selector('#create');page.locator('#create').click();page.wait_for_selector('#world');assert page.evaluate('typeof AstraeonTownServicesDev')=='undefined' and page.evaluate('typeof AstraeonTownServicesHarness')=='undefined';passed('normal URL exposes no service mutation or harness globals');context.close();browser.close()
 assert not errors and not http_errors,(errors,http_errors);report={'result':'passed','checks':checks,'errors':errors,'httpErrors':http_errors,'expectedRejections':blocked,'navigation':nav.observations}
except Exception as e:
 report={'result':'failed','message':str(e),'checks':checks,'errors':errors,'httpErrors':http_errors,'expectedRejections':blocked,'navigation':nav.observations}
 try:report['lastState']=qa();page.screenshot(path=str(args.output/'failure.png'))
 except Exception:report['lastState']=nav.last_snapshot
 raise
finally:
 (args.output/'report.json').write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8');print('REPORT',args.output/'report.json',flush=True)
