const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
global.window={};for(const file of ['world-view.js','navigation.js','character-motion.js','world/v3/spatial.js','world/v3/locomotion.js'])require('../'+file);
const source=JSON.parse(fs.readFileSync(path.join(__dirname,'../world/v3/golden-proof.json'))),manifest=JSON.parse(fs.readFileSync(path.join(__dirname,'../world/v3/warrior-animation.json'))),spatial=window.AstraeonSpatialV3;
window.AstraeonLocomotionV3.configure(manifest);
test('gate collision contains pillars, not overhead span or passage',()=>{const w=spatial.compile(source);assert(w.blocked(2.6,10));assert(w.blocked(5.4,10));for(let y=8;y<=12;y+=.05)assert(!w.blocked(4,y));assert(w.route({x:4,y:12.2},{x:4,y:8}));});
test('authored route and entrances are reachable with actor clearance',()=>{const w=spatial.compile(source);let start={x:source.spawn[0],y:source.spawn[1]};for(const stop of source.route){const goal={x:stop.position[0],y:stop.position[1]},route=w.route(start,goal);assert(route,'unreachable '+stop.name);for(const waypoint of route)assert(!w.blocked(waypoint.x,waypoint.y));start=goal}for(const p of w.portals)assert(!w.blocked(...p.approach.slice(0,2)));});
test('one edited mesh moves visuals, collision, navigation and shadow together',()=>{const before=spatial.compile(source),changed=structuredClone(source),pillar=changed.objects.find(o=>o.id==='west-gate').parts.find(p=>p.id==='west-pillar');pillar.vertices.forEach(v=>v[0]-=1);const after=spatial.compile(changed);assert(before.blocked(2.6,10));assert(!after.blocked(2.6,10));assert(after.blocked(1.6,10));assert.notDeepEqual(after.shadowPolygons.find(p=>p.id===pillar.id),before.shadowPolygons.find(p=>p.id===pillar.id));assert.notDeepEqual(after.navCells,before.navCells);assert.deepEqual(after.parts.find(p=>p.id===pillar.id).vertices,pillar.vertices);});
test('roof/canopy are selective layers and remain independent shadow casters',()=>{const w=spatial.compile(source);for(const id of ['hall-roof','canopy','open-span']){assert(w.overheads.some(p=>p.id===id));assert(w.shadowPolygons.some(p=>p.id===id));assert(!w.solids.some(p=>p.id===id))}assert(w.solids.some(p=>p.id==='hall-body'));assert(w.solids.some(p=>p.id==='trunk'));});
test('shared schema rejects invalid/duplicate mesh identifiers and invalid indices',()=>{for(const edit of [s=>s.objects.push(s.objects[0]),s=>s.objects[0].parts[0].vertices[0][0]=NaN,s=>s.objects[0].parts[0].faces[0][0]=999]){const s=structuredClone(source);edit(s);assert.throws(()=>spatial.compile(s))}});
for(const mode of ['walk','run','sprint']){
 test(mode+' displacement, duty and visible contacts agree in all eight directions',()=>{const p=manifest.clips[mode];for(let row=0;row<8;row++){const angle=row*Math.PI/4,t=new window.AstraeonLocomotionV3.Locomotion(0,0,angle);t.setStrategy(mode);t.tick(0,0,.01);for(let tick=0;tick<240;tick++){const old=structuredClone(t.feet),gait=t.gait,d=.008*p.speed;t.tick(t.position.x+Math.cos(angle)*d,t.position.y+Math.sin(angle)*d,.008,{sprint:mode==='sprint'});assert(Math.abs(t.gait-gait-d/p.cycleDistance)<1e-8);for(let i=0;i<2;i++){const foot=t.feet[i];assert.equal(foot.swing,foot.phase>=p.duty);if(old[i]&&!old[i].swing&&!foot.swing){assert.equal(foot.x,old[i].x);assert.equal(foot.y,old[i].y)}assert(foot.z>=0)}}for(let col=0;col<8;col++){const frame=p.frames[row*8+col];assert.equal(frame.contacts[0].stance,(col/8)%1<p.duty);assert.equal(frame.contacts[1].stance,(col/8+.5)%1<p.duty);assert(frame.durationMs>0);assert.equal(frame.footAnchorY,204);assert.deepEqual(frame.contacts.map(c=>c.leg),['left','right'])}}});
}
test('three locomotion strategies have separate atlas geometry, stride and duty',()=>{const clips=Object.values(manifest.clips);for(const key of ['atlas','cycleDistance','duty','bodyPitch'])assert.equal(new Set(clips.map(c=>c[key])).size,3);for(const c of clips){assert(fs.existsSync(path.join(__dirname,'../'+c.atlas)));assert(c.frames.some(f=>f.events.includes('left-contact')));assert(c.frames.some(f=>f.events.includes('right-contact')))}assert.notDeepEqual(clips[0].frames[2].contacts,clips[1].frames[2].contacts)});
test('authored stance travel cancels root travel at the gameplay projection and scale',()=>{for(const p of Object.values(manifest.clips))for(let row=0;row<8;row++){const angle=Math.PI/2-row*Math.PI/4,heading=window.AstraeonView.inverse(Math.cos(angle),Math.sin(angle)),length=Math.hypot(heading.x,heading.y),root=window.AstraeonView.project(heading.x/length*p.cycleDistance/8,heading.y/length*p.cycleDistance/8),a=p.frames[row*8].contacts[0].foot,b=p.frames[row*8+1].contacts[0].foot;assert(Math.abs((b[0]-a[0])*.5+root.x)<1e-8);assert(Math.abs((b[1]-a[1])*.5+root.y)<1e-8)}});
test('start, stop, turn and strategy changes settle without teleports',()=>{const t=new window.AstraeonLocomotionV3.Locomotion(4,12);t.tick(4,12,.01);t.tick(4,11.98,.016);assert.equal(t.state,'start');t.setStrategy('sprint');for(let i=0;i<90;i++)t.tick(4,t.position.y-.02,.016,{sprint:true});assert.equal(t.activeStrategy,'sprint');t.tick(4,t.position.y,.016);assert.equal(t.state,'stop');t.face(1,0);for(let i=0;i<80;i++)t.tick(4,t.position.y,.016);assert.equal(t.state,'idle');assert(t.feet.every(f=>!f.swing&&f.z<.001));assert(Math.abs(t.rotation)<.001)});
test('current court import preserves painted placements and collision exactly',()=>{require('../world-content.js');require('../world/v3/town-import.js');const baseline=window.AstraeonContent,data=JSON.parse(fs.readFileSync(path.join(__dirname,'../world/v3/wayfarer-court.json'))),imported=window.AstraeonTownImportV3.content(data,baseline);const sorted=a=>a.toSorted((a,b)=>a.id.localeCompare(b.id));assert.deepEqual(sorted(imported.townObjects),sorted(baseline.townObjects));for(const b of baseline.townBlocks){const actual=imported.townBlocks.find(p=>p.id===b.id);for(const key of ['x','y','w','h'])assert(Math.abs(b[key]-actual[key])<1e-8)}assert.deepEqual(sorted(imported.forecourts),sorted(baseline.forecourts));assert.deepEqual(imported.goldenScene.plaza,baseline.goldenScene.plaza);assert.equal(imported.walkers,baseline.walkers);assert.equal(imported.atlas,baseline.atlas);assert.equal(imported.nativeWorld.id,'wayfarer-court');for(const road of imported.townRoads)assert(road.width>0)});
