"""Distinct run/sprint atlases + ACT-like manifest, using original painted costume.
Run python3 tools/build-locomotion-v3.py. All strategies have authored geometry
and explicit contacts. No generated art service is required.
"""
import json, math, subprocess
from pathlib import Path
from PIL import Image, ImageDraw
ROOT=Path(__file__).resolve().parents[1]
CELL=256;AX=128;AY=204;OX=32;OY=30;S=3
source=json.loads(subprocess.check_output(['node','-e',"global.window={};require('./directional-metadata.js');require('./hero-registration.js');require('./warrior-gait.js');require('./character-motion.js');require('./world/v3/locomotion.js');console.log(JSON.stringify({reg:window.AstraeonHeroRegistration['warrior-walk'],profiles:window.AstraeonLocomotionV3.profiles}))"],cwd=ROOT))
torso=Image.open(ROOT/'assets/warrior-torso-v1.webp').convert('RGBA')
manifest={'version':3,'actor':'golden-warrior','directions':['S','SE','E','NE','N','NW','W','SW'],'anchorSpace':'frame-pixel','distanceUnit':'world-unit','clips':{}}
registrations={};metas={}
for mode,p in source['profiles'].items():
 records=[];atlas=Image.new('RGBA',(CELL*8,CELL*8));torso_sheet=Image.new('RGBA',(CELL,CELL*8))
 for row in range(8):
  angle=math.pi/2-row*math.pi/4;fx,fy=math.cos(angle),math.sin(angle);lateral=(math.sin(angle),-math.cos(angle)*.38)
  original=torso.crop((0,row*192,192,(row+1)*192));pitched=Image.new('RGBA',(CELL,CELL));pitched.alpha_composite(original,(OX+round(fx*p['bodyPitch']),OY+round(fy*p['bodyPitch']*.3)))
  torso_sheet.alpha_composite(pitched,(0,row*CELL))
  det=1504;wx,wy=(22*fx+32*fy)/det,(48*fy-14*fx)/det
  # Half the stance displacement, in source pixels at the 0.5 gameplay scale.
  # Using a fixed half-cycle would miscalibrate the differing duty factors.
  travel=p['cycleDistance']*p['duty']*.5/math.hypot(wx,wy)/.5
  for col in range(8):
   phase=col/8;im=Image.new('RGBA',(CELL*S,CELL*S));d=ImageDraw.Draw(im);contacts=[]
   for i in range(2):
    q=(phase+i*.5)%1;stance=q<p['duty'];side=-1 if i==0 else 1
    along=travel*(1-2*q/p['duty']) if stance else -travel+2*travel*((q-p['duty'])/(1-p['duty']))
    lift=0 if stance else math.sin((q-p['duty'])/(1-p['duty'])*math.pi)*p['lift']*70
    base=source['reg']['frames'][row*8+col]['contacts'][i]
    hip=[base['hip'][0]+OX+fx*p['bodyPitch'],base['hip'][1]+OY+fy*p['bodyPitch']*.3]
    foot=[AX+lateral[0]*side*9+fx*along,AY+lateral[1]*side*9+fy*along-lift]
    assert 9<foot[0]<CELL-9 and 9<foot[1]<CELL-5,(mode,row,col,foot)
    knee=[(hip[0]+foot[0])*.5-fx*lift*.75,(hip[1]+foot[1])*.5-2-lift*.40]
    def line(a,b,w,color):d.line([(a[0]*3,a[1]*3),(b[0]*3,b[1]*3)],fill=color,width=w*3)
    line(hip,knee,16,'#302b28');line(hip,knee,12,'#62564a');line([hip[0]-2,hip[1]],[knee[0]-2,knee[1]],2,'#b59d67')
    line(knee,foot,14,'#282c2b');line(knee,foot,11,'#444541');line([knee[0]-2,knee[1]],[foot[0]-2,foot[1]-3],2,'#807454')
    kx,ky=knee;d.ellipse(((kx-6)*3,(ky-4)*3,(kx+6)*3,(ky+5)*3),fill='#756a50',outline='#b3a173',width=3)
    x,y=foot;d.polygon([((x-5)*3,(y-6)*3),((x+4)*3,(y-6)*3),((x+6+fx*5)*3,(y-1)*3),((x+5+fx*5)*3,(y+2)*3),((x-5)*3,(y+2)*3)],fill='#32332e')
    contacts.append({'leg':'left' if i==0 else 'right','hip':hip,'knee':knee,'foot':foot,'stance':stance,'gaitPhase':q})
   im.alpha_composite(pitched.resize((CELL*S,CELL*S),Image.Resampling.LANCZOS));im=im.resize((CELL,CELL),Image.Resampling.LANCZOS);atlas.alpha_composite(im,(col*CELL,row*CELL))
   records.append({'phase':phase,'durationMs':1000*p['cycleDistance']/p['speed']/8,'footAnchorX':AX,'footAnchorY':AY,'bodyAnchor':[AX,104+OY],'bodyClipY':source['reg']['frames'][row*8+col]['bodyClipY']+OY,'contacts':contacts,'events':(['left-contact'] if col==0 else ['right-contact'] if col==4 else []),'attachments':{'RightHand':[119+OX,123+OY],'Back':[91+OX,101+OY]}})
 atlas.save(ROOT/('assets/'+p['clip']+'.webp'),lossless=True);torso_sheet.save(ROOT/('assets/'+p['torso']+'.webp'),lossless=True)
 registrations[p['clip']]={'cellSize':CELL,'anchors':[[AX,AY]]*64,'heights':[140]*8,'frames':records}
 metas[p['clip']]={'cols':8,'rows':8,'frames':[[col*CELL,row*CELL,CELL,CELL] for row in range(8) for col in range(8)]}
 manifest['clips'][mode]={**p,'atlas':'assets/'+p['clip']+'.webp','phases':['left-contact','left-down','passing','left-push','right-contact','right-down','passing','right-push'],'frames':records}
(ROOT/'world/v3/warrior-animation.json').write_text(json.dumps(manifest,indent=2)+'\n')
js='/* Generated by tools/build-locomotion-v3.py; proof-only adapters. */\n'
for k,v in metas.items():js+='window.AstraeonDirectionalMetadata['+json.dumps(k)+']='+json.dumps(v,separators=(',',':'))+';\n'
for k,v in registrations.items():js+='window.AstraeonHeroRegistration['+json.dumps(k)+']='+json.dumps(v,separators=(',',':'))+';\n'
(ROOT/'world/v3/warrior-registration.js').write_text(js)
print('Authored walk/run/sprint: 192 frames and an explicit three-strategy contact manifest.')
